/**
 * Governance document template renderer.
 *
 * Generates operational compliance documents from provider registry data
 * and framework configuration. Templates produce Markdown output.
 */

interface TemplateProvider extends Record<string, unknown> {
  active: boolean;
  name?: string;
  provider_type?: string;
  data_location?: string | null;
  dpa_status?: string;
  transfer_mechanism?: string | null;
  tom_status?: string | null;
  metadata?: Record<string, unknown> | null;
  dpa_signed_at?: string | null;
  dpa_expires_at?: string | null;
}

interface TemplateFramework {
  id: string;
  name: string;
  description?: string;
}

interface TemplateContext {
  company_name: string;
  company_address: string;
  governance_owner: string;
  providers: TemplateProvider[];
  frameworks: TemplateFramework[];
  generated_at: string;
}

/**
 * Generate a subprocessor inventory document.
 * Maps to: nemoclaw-kanzlei-eu/compliance_docs/subprocessor_inventory.md
 */
export function generateSubprocessorInventory(ctx: TemplateContext): string {
  const lines: string[] = [
    "# Subprocessor Inventory",
    "",
    `Generated: ${ctx.generated_at}`,
    `Company: ${ctx.company_name}`,
    `Governance Owner: ${ctx.governance_owner}`,
    "",
    "## Active Subprocessors",
    "",
    "| # | Provider | Type | Location | DPA Status | Transfer Mechanism | TOM Status |",
    "|---|----------|------|----------|------------|-------------------|------------|",
  ];

  let idx = 1;
  for (const p of ctx.providers) {
    if (!p.active) continue;
    lines.push(
      `| ${idx++} | ${p.name} | ${p.provider_type} | ${p.data_location ?? "—"} | ${p.dpa_status} | ${p.transfer_mechanism ?? "—"} | ${p.tom_status ?? "—"} |`,
    );
  }

  lines.push("");
  lines.push("## Provider Details");
  lines.push("");

  idx = 1;
  for (const p of ctx.providers) {
    if (!p.active) continue;
    const meta = p.metadata as Record<string, unknown> | null;

    lines.push(`### ${idx++}. ${p.name}`);
    lines.push("");
    lines.push(`- **Type:** ${p.provider_type}`);
    lines.push(`- **Data Location:** ${p.data_location ?? "Unknown"}`);
    lines.push(`- **DPA Status:** ${p.dpa_status}`);

    if (p.dpa_signed_at) {
      lines.push(`- **DPA Signed:** ${p.dpa_signed_at}`);
    }
    if (p.dpa_expires_at) {
      lines.push(`- **DPA Expires:** ${p.dpa_expires_at}`);
    }

    lines.push(
      `- **Transfer Mechanism:** ${p.transfer_mechanism ?? "Not configured"}`,
    );
    lines.push(`- **TOM Status:** ${p.tom_status ?? "Unknown"}`);

    if (meta?.known_certifications) {
      const certs = meta.known_certifications as string[];
      if (certs.length > 0) {
        lines.push(`- **Certifications:** ${certs.join(", ")}`);
      }
    }

    if (meta?.dpa_url) {
      lines.push(`- **DPA URL:** ${meta.dpa_url}`);
    }
    if (meta?.subprocessor_list_url) {
      lines.push(`- **Subprocessor List:** ${meta.subprocessor_list_url}`);
    }
    if (meta?.notes) {
      lines.push(`- **Notes:** ${meta.notes}`);
    }

    lines.push("");
  }

  lines.push("## Applicable Frameworks");
  lines.push("");
  for (const f of ctx.frameworks) {
    lines.push(`- **${f.name}** (${f.id}) — ${f.description}`);
  }
  lines.push("");

  lines.push("---");
  lines.push(
    `*This document was auto-generated by the Compliance Engine on ${ctx.generated_at}.*`,
  );
  lines.push(
    `*Review owner: ${ctx.governance_owner}. Next review: 90 days from generation.*`,
  );

  return lines.join("\n");
}

/**
 * Generate a go-live checklist document.
 * Maps to: nemoclaw-kanzlei-eu/MVP_GO_LIVE_CHECKLIST.md
 */
export function generateGoLiveChecklist(ctx: TemplateContext): string {
  const lines: string[] = [
    "# Deployment Go-Live Checklist",
    "",
    `Generated: ${ctx.generated_at}`,
    `Company: ${ctx.company_name}`,
    `Governance Owner: ${ctx.governance_owner}`,
    "",
    "## Legal & Contractual",
    "",
  ];

  let idx = 1;

  // Per-provider legal items
  for (const p of ctx.providers) {
    if (!p.active) continue;
    const dpaOk = p.dpa_status === "signed";
    lines.push(
      `- [${dpaOk ? "x" : " "}] **E-LGL-${String(idx).padStart(3, "0")}**: Signed DPA/AVV with ${p.name}`,
    );
    idx++;
  }

  lines.push("");
  lines.push("## Technical Infrastructure");
  lines.push("");

  lines.push(
    `- [ ] **E-TECH-001**: Hosting encryption at rest verified`,
  );
  lines.push(
    `- [ ] **E-TECH-002**: Hosting encryption in transit verified`,
  );
  lines.push(
    `- [ ] **E-TECH-003**: Backup encryption verified`,
  );
  lines.push(
    `- [ ] **E-TECH-004**: Network boundary / firewall baseline documented`,
  );

  lines.push("");
  lines.push("## Operational Readiness");
  lines.push("");

  lines.push(
    `- [ ] **E-OPS-001**: Incident response plan published`,
  );
  lines.push(
    `- [ ] **E-OPS-002**: Incident contact matrix populated`,
  );
  lines.push(
    `- [ ] **E-OPS-003**: Incident drill executed and evidenced`,
  );
  lines.push(
    `- [ ] **E-OPS-004**: Restore drill executed and evidenced`,
  );
  lines.push(
    `- [ ] **E-OPS-005**: Data deletion capability verified`,
  );
  lines.push(
    `- [ ] **E-OPS-006**: Data export (portability) capability verified`,
  );

  lines.push("");
  lines.push("## Data Protection");
  lines.push("");

  lines.push(`- [ ] **E-DP-001**: Privacy policy published`);
  lines.push(
    `- [ ] **E-DP-002**: Consent mechanism implemented and tested`,
  );
  lines.push(
    `- [ ] **E-DP-003**: Data subject rights process documented`,
  );
  lines.push(
    `- [ ] **E-DP-004**: Retention policy defined and enforced`,
  );

  lines.push("");
  lines.push("## Release Decision");
  lines.push("");
  lines.push("| Criterion | Status |");
  lines.push("|-----------|--------|");
  lines.push("| All provider DPAs signed | PENDING |");
  lines.push("| All transfer mechanisms established | PENDING |");
  lines.push("| Incident readiness verified | PENDING |");
  lines.push("| Data protection controls active | PENDING |");
  lines.push("| **Overall Decision** | **NO_GO** |");

  lines.push("");
  lines.push("---");
  lines.push(
    `*Auto-generated by Compliance Engine on ${ctx.generated_at}.*`,
  );

  return lines.join("\n");
}

/**
 * Generate an incident contact matrix.
 * Maps to: nemoclaw-kanzlei-eu/compliance_docs/incident_contact_matrix.md
 */
export function generateIncidentMatrix(ctx: TemplateContext): string {
  const lines: string[] = [
    "# Incident Contact Matrix",
    "",
    `Generated: ${ctx.generated_at}`,
    `Company: ${ctx.company_name}`,
    `Governance Owner: ${ctx.governance_owner}`,
    "",
    "## Internal Contacts",
    "",
    "| Role | Name | Contact |",
    "|------|------|---------|",
    `| Governance Owner | ${ctx.governance_owner} | {{EMAIL}} |`,
    "| Technical Lead | {{NAME}} | {{EMAIL}} |",
    "| Legal Counsel | {{NAME}} | {{EMAIL}} |",
    "",
    "## Provider Incident Contacts",
    "",
    "| Provider | Type | DPA Contact | Emergency Contact |",
    "|----------|------|-------------|-------------------|",
  ];

  for (const p of ctx.providers) {
    if (!p.active) continue;
    const meta = p.metadata as Record<string, unknown> | null;
    const contact = (meta?.contact as string) ?? "{{CONTACT}}";
    lines.push(
      `| ${p.name} | ${p.provider_type} | ${contact} | {{EMERGENCY}} |`,
    );
  }

  lines.push("");
  lines.push("## Supervisory Authority");
  lines.push("");
  lines.push("| Authority | Contact |");
  lines.push("|-----------|---------|");
  lines.push(
    "| State Data Protection Authority | {{DPA_AUTHORITY}} |",
  );
  lines.push(
    "| Breach notification: within 72 hours (GDPR Art 33) | |",
  );

  lines.push("");
  lines.push("## Incident Severity Levels");
  lines.push("");
  lines.push("| Level | Description | Response Time | Notification |");
  lines.push("|-------|-------------|---------------|--------------|");
  lines.push(
    "| P0 — Critical | Data breach with personal data exposure | Immediate | DPA + affected subjects |",
  );
  lines.push(
    "| P1 — High | System compromise, potential data access | 4 hours | Internal + legal review |",
  );
  lines.push(
    "| P2 — Medium | Service disruption, no data exposure | 24 hours | Internal |",
  );
  lines.push(
    "| P3 — Low | Minor issue, no security impact | 72 hours | Log only |",
  );

  lines.push("");
  lines.push("---");
  lines.push(
    `*Auto-generated by Compliance Engine on ${ctx.generated_at}.*`,
  );

  return lines.join("\n");
}
