/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accountManagement from "../accountManagement.js";
import type * as actions_apiKeys from "../actions/apiKeys.js";
import type * as actions_betaAccessEmails from "../actions/betaAccessEmails.js";
import type * as actions_feedbackEmail from "../actions/feedbackEmail.js";
import type * as actions_mux from "../actions/mux.js";
import type * as actions_salesNotificationEmail from "../actions/salesNotificationEmail.js";
import type * as actions_subscriptionEmails from "../actions/subscriptionEmails.js";
import type * as actions_welcomeEmail from "../actions/welcomeEmail.js";
import type * as activityProtocol from "../activityProtocol.js";
import type * as addressValidation from "../addressValidation.js";
import type * as agentOntology from "../agentOntology.js";
import type * as ai_agentApprovals from "../ai/agentApprovals.js";
import type * as ai_agentExecution from "../ai/agentExecution.js";
import type * as ai_agentSessions from "../ai/agentSessions.js";
import type * as ai_billing from "../ai/billing.js";
import type * as ai_campaigns from "../ai/campaigns.js";
import type * as ai_chat from "../ai/chat.js";
import type * as ai_contactSyncs from "../ai/contactSyncs.js";
import type * as ai_conversations from "../ai/conversations.js";
import type * as ai_deadLetterQueue from "../ai/deadLetterQueue.js";
import type * as ai_drafts from "../ai/drafts.js";
import type * as ai_errorMessages from "../ai/errorMessages.js";
import type * as ai_escalation from "../ai/escalation.js";
import type * as ai_featureRequestEmail from "../ai/featureRequestEmail.js";
import type * as ai_harness from "../ai/harness.js";
import type * as ai_i18nHelper from "../ai/i18nHelper.js";
import type * as ai_interviewRunner from "../ai/interviewRunner.js";
import type * as ai_linearActions from "../ai/linearActions.js";
import type * as ai_linearClient from "../ai/linearClient.js";
import type * as ai_manualGrants from "../ai/manualGrants.js";
import type * as ai_modelAdapters from "../ai/modelAdapters.js";
import type * as ai_modelDiscovery from "../ai/modelDiscovery.js";
import type * as ai_openrouter from "../ai/openrouter.js";
import type * as ai_platformAlerts from "../ai/platformAlerts.js";
import type * as ai_platformModelManagement from "../ai/platformModelManagement.js";
import type * as ai_platformModels from "../ai/platformModels.js";
import type * as ai_prompts_layersBuilderSystem from "../ai/prompts/layersBuilderSystem.js";
import type * as ai_prompts_pageBuilderSystem from "../ai/prompts/pageBuilderSystem.js";
import type * as ai_resetAISettings from "../ai/resetAISettings.js";
import type * as ai_retryPolicy from "../ai/retryPolicy.js";
import type * as ai_selfImprovement from "../ai/selfImprovement.js";
import type * as ai_sessionPolicy from "../ai/sessionPolicy.js";
import type * as ai_settings from "../ai/settings.js";
import type * as ai_skills_index from "../ai/skills/index.js";
import type * as ai_soulEvolution from "../ai/soulEvolution.js";
import type * as ai_soulGenerator from "../ai/soulGenerator.js";
import type * as ai_systemKnowledge__content from "../ai/systemKnowledge/_content.js";
import type * as ai_systemKnowledge_index from "../ai/systemKnowledge/index.js";
import type * as ai_teamHarness from "../ai/teamHarness.js";
import type * as ai_toolBroker from "../ai/toolBroker.js";
import type * as ai_toolScoping from "../ai/toolScoping.js";
import type * as ai_tools_activeCampaignTool from "../ai/tools/activeCampaignTool.js";
import type * as ai_tools_activityProtocolTool from "../ai/tools/activityProtocolTool.js";
import type * as ai_tools_agencyTools from "../ai/tools/agencyTools.js";
import type * as ai_tools_benefitsTool from "../ai/tools/benefitsTool.js";
import type * as ai_tools_bookingTool from "../ai/tools/bookingTool.js";
import type * as ai_tools_bookingWorkflowTool from "../ai/tools/bookingWorkflowTool.js";
import type * as ai_tools_builderToolActions from "../ai/tools/builderToolActions.js";
import type * as ai_tools_builderTools from "../ai/tools/builderTools.js";
import type * as ai_tools_bulkCRMEmailTool from "../ai/tools/bulkCRMEmailTool.js";
import type * as ai_tools_connectionToolActions from "../ai/tools/connectionToolActions.js";
import type * as ai_tools_connectionTools from "../ai/tools/connectionTools.js";
import type * as ai_tools_contactSyncTool from "../ai/tools/contactSyncTool.js";
import type * as ai_tools_coordinatorTools from "../ai/tools/coordinatorTools.js";
import type * as ai_tools_crmTool from "../ai/tools/crmTool.js";
import type * as ai_tools_dataQueryInternal from "../ai/tools/dataQueryInternal.js";
import type * as ai_tools_dataQueryTool from "../ai/tools/dataQueryTool.js";
import type * as ai_tools_formsTool from "../ai/tools/formsTool.js";
import type * as ai_tools_internalToolMutations from "../ai/tools/internalToolMutations.js";
import type * as ai_tools_interviewTools from "../ai/tools/interviewTools.js";
import type * as ai_tools_layersWorkflowTool from "../ai/tools/layersWorkflowTool.js";
import type * as ai_tools_linkObjectsTool from "../ai/tools/linkObjectsTool.js";
import type * as ai_tools_mediaTools from "../ai/tools/mediaTools.js";
import type * as ai_tools_projectsTool from "../ai/tools/projectsTool.js";
import type * as ai_tools_registry from "../ai/tools/registry.js";
import type * as ai_tools_sequencesTool from "../ai/tools/sequencesTool.js";
import type * as ai_tools_soulEvolutionTools from "../ai/tools/soulEvolutionTools.js";
import type * as ai_tools_teamTools from "../ai/tools/teamTools.js";
import type * as ai_tools_unsplashTool from "../ai/tools/unsplashTool.js";
import type * as ai_tools_webinarTool from "../ai/tools/webinarTool.js";
import type * as ai_trainingData from "../ai/trainingData.js";
import type * as ai_trainingExport from "../ai/trainingExport.js";
import type * as ai_webReader from "../ai/webReader.js";
import type * as ai_workItemActions from "../ai/workItemActions.js";
import type * as ai_workItems from "../ai/workItems.js";
import type * as ai_workerPool from "../ai/workerPool.js";
import type * as api_auth from "../api/auth.js";
import type * as api_v1_accountLinking from "../api/v1/accountLinking.js";
import type * as api_v1_accountLinkingInternal from "../api/v1/accountLinkingInternal.js";
import type * as api_v1_activecampaign from "../api/v1/activecampaign.js";
import type * as api_v1_activityProtocol from "../api/v1/activityProtocol.js";
import type * as api_v1_activityProtocolInternal from "../api/v1/activityProtocolInternal.js";
import type * as api_v1_aiChat from "../api/v1/aiChat.js";
import type * as api_v1_aiChatInternal from "../api/v1/aiChatInternal.js";
import type * as api_v1_appManifestSchema from "../api/v1/appManifestSchema.js";
import type * as api_v1_auth from "../api/v1/auth.js";
import type * as api_v1_availability from "../api/v1/availability.js";
import type * as api_v1_benefits from "../api/v1/benefits.js";
import type * as api_v1_benefitsInternal from "../api/v1/benefitsInternal.js";
import type * as api_v1_bookings from "../api/v1/bookings.js";
import type * as api_v1_bookingsInternal from "../api/v1/bookingsInternal.js";
import type * as api_v1_certificates from "../api/v1/certificates.js";
import type * as api_v1_certificatesInternal from "../api/v1/certificatesInternal.js";
import type * as api_v1_checkout from "../api/v1/checkout.js";
import type * as api_v1_checkoutCrudInternal from "../api/v1/checkoutCrudInternal.js";
import type * as api_v1_checkoutInternal from "../api/v1/checkoutInternal.js";
import type * as api_v1_cliApplications from "../api/v1/cliApplications.js";
import type * as api_v1_cliApplicationsInternal from "../api/v1/cliApplicationsInternal.js";
import type * as api_v1_cliAuth from "../api/v1/cliAuth.js";
import type * as api_v1_cliAuthHttp from "../api/v1/cliAuthHttp.js";
import type * as api_v1_conversations from "../api/v1/conversations.js";
import type * as api_v1_conversationsInternal from "../api/v1/conversationsInternal.js";
import type * as api_v1_corsHeaders from "../api/v1/corsHeaders.js";
import type * as api_v1_crm from "../api/v1/crm.js";
import type * as api_v1_crmInternal from "../api/v1/crmInternal.js";
import type * as api_v1_customerAuth from "../api/v1/customerAuth.js";
import type * as api_v1_customerAuthInternal from "../api/v1/customerAuthInternal.js";
import type * as api_v1_domainLookup from "../api/v1/domainLookup.js";
import type * as api_v1_domainLookupInternal from "../api/v1/domainLookupInternal.js";
import type * as api_v1_emailAuth from "../api/v1/emailAuth.js";
import type * as api_v1_emailAuthInternal from "../api/v1/emailAuthInternal.js";
import type * as api_v1_events from "../api/v1/events.js";
import type * as api_v1_eventsInternal from "../api/v1/eventsInternal.js";
import type * as api_v1_externalDomains from "../api/v1/externalDomains.js";
import type * as api_v1_forms from "../api/v1/forms.js";
import type * as api_v1_formsInternal from "../api/v1/formsInternal.js";
import type * as api_v1_httpHelpers from "../api/v1/httpHelpers.js";
import type * as api_v1_invoices from "../api/v1/invoices.js";
import type * as api_v1_invoicesInternal from "../api/v1/invoicesInternal.js";
import type * as api_v1_locations from "../api/v1/locations.js";
import type * as api_v1_mobileOAuth from "../api/v1/mobileOAuth.js";
import type * as api_v1_mobileOAuthInternal from "../api/v1/mobileOAuthInternal.js";
import type * as api_v1_notifications from "../api/v1/notifications.js";
import type * as api_v1_oauthConnections from "../api/v1/oauthConnections.js";
import type * as api_v1_oauthConnectionsInternal from "../api/v1/oauthConnectionsInternal.js";
import type * as api_v1_oauthSignup from "../api/v1/oauthSignup.js";
import type * as api_v1_products from "../api/v1/products.js";
import type * as api_v1_productsInternal from "../api/v1/productsInternal.js";
import type * as api_v1_projects from "../api/v1/projects.js";
import type * as api_v1_projectsInternal from "../api/v1/projectsInternal.js";
import type * as api_v1_publishing from "../api/v1/publishing.js";
import type * as api_v1_publishingInternal from "../api/v1/publishingInternal.js";
import type * as api_v1_resourceBookings from "../api/v1/resourceBookings.js";
import type * as api_v1_resourceBookingsInternal from "../api/v1/resourceBookingsInternal.js";
import type * as api_v1_stripeInvoiceWebhooks from "../api/v1/stripeInvoiceWebhooks.js";
import type * as api_v1_subOrganizations from "../api/v1/subOrganizations.js";
import type * as api_v1_subOrganizationsInternal from "../api/v1/subOrganizationsInternal.js";
import type * as api_v1_templatesInternal from "../api/v1/templatesInternal.js";
import type * as api_v1_tickets from "../api/v1/tickets.js";
import type * as api_v1_ticketsInternal from "../api/v1/ticketsInternal.js";
import type * as api_v1_transactions from "../api/v1/transactions.js";
import type * as api_v1_transactionsInternal from "../api/v1/transactionsInternal.js";
import type * as api_v1_users from "../api/v1/users.js";
import type * as api_v1_webchatApi from "../api/v1/webchatApi.js";
import type * as api_v1_webinars from "../api/v1/webinars.js";
import type * as api_v1_webinarsInternal from "../api/v1/webinarsInternal.js";
import type * as api_v1_workflows from "../api/v1/workflows.js";
import type * as api_v1_workflowsCrudInternal from "../api/v1/workflowsCrudInternal.js";
import type * as api_v1_workflowsInternal from "../api/v1/workflowsInternal.js";
import type * as api_v1_workflowsInternal_OLD from "../api/v1/workflowsInternal_OLD.js";
import type * as apiKeysInternal from "../apiKeysInternal.js";
import type * as appAvailability from "../appAvailability.js";
import type * as applicationOntology from "../applicationOntology.js";
import type * as auditLogExport from "../auditLogExport.js";
import type * as auditTemplates from "../auditTemplates.js";
import type * as auth_identity from "../auth/identity.js";
import type * as auth from "../auth.js";
import type * as availabilityOntology from "../availabilityOntology.js";
import type * as b2bInvoiceHelper from "../b2bInvoiceHelper.js";
import type * as benefitsMemberSync from "../benefitsMemberSync.js";
import type * as benefitsOntology from "../benefitsOntology.js";
import type * as betaAccess from "../betaAccess.js";
import type * as bookingOntology from "../bookingOntology.js";
import type * as builderAppOntology from "../builderAppOntology.js";
import type * as calendarSyncOntology from "../calendarSyncOntology.js";
import type * as calendarSyncSubcalendars from "../calendarSyncSubcalendars.js";
import type * as certificateOntology from "../certificateOntology.js";
import type * as channels_infobipCpaasX from "../channels/infobipCpaasX.js";
import type * as channels_platformSms from "../channels/platformSms.js";
import type * as channels_providers_chatwoot from "../channels/providers/chatwoot.js";
import type * as channels_providers_infobipProvider from "../channels/providers/infobipProvider.js";
import type * as channels_providers_manychatAdapter from "../channels/providers/manychatAdapter.js";
import type * as channels_providers_telegramProvider from "../channels/providers/telegramProvider.js";
import type * as channels_providers_whatsappProvider from "../channels/providers/whatsappProvider.js";
import type * as channels_registry from "../channels/registry.js";
import type * as channels_router from "../channels/router.js";
import type * as channels_telegramBotSetup from "../channels/telegramBotSetup.js";
import type * as channels_telegramGroupMirror from "../channels/telegramGroupMirror.js";
import type * as channels_telegramGroupSetup from "../channels/telegramGroupSetup.js";
import type * as channels_types from "../channels/types.js";
import type * as channels_webhooks from "../channels/webhooks.js";
import type * as checkTemplateById from "../checkTemplateById.js";
import type * as checkoutOntology from "../checkoutOntology.js";
import type * as checkoutSessionOntology from "../checkoutSessionOntology.js";
import type * as checkoutSessions from "../checkoutSessions.js";
import type * as checkoutTemplateAvailability from "../checkoutTemplateAvailability.js";
import type * as commissionsOntology from "../commissionsOntology.js";
import type * as communicationTracking from "../communicationTracking.js";
import type * as compliance from "../compliance.js";
import type * as consolidatedInvoicing from "../consolidatedInvoicing.js";
import type * as createTransactionsFromCheckout from "../createTransactionsFromCheckout.js";
import type * as credits_index from "../credits/index.js";
import type * as credits_notifications from "../credits/notifications.js";
import type * as credits_sharing from "../credits/sharing.js";
import type * as crmAiTools from "../crmAiTools.js";
import type * as crmIntegrations from "../crmIntegrations.js";
import type * as crmOntology from "../crmOntology.js";
import type * as crmOrganizationPipelines from "../crmOrganizationPipelines.js";
import type * as crmPipeline from "../crmPipeline.js";
import type * as crmTags from "../crmTags.js";
import type * as crons from "../crons.js";
import type * as cryptoActions from "../cryptoActions.js";
import type * as departureOntology from "../departureOntology.js";
import type * as designEngine from "../designEngine.js";
import type * as domainConfigOntology from "../domainConfigOntology.js";
import type * as emailDelivery from "../emailDelivery.js";
import type * as emailQueue from "../emailQueue.js";
import type * as emailService from "../emailService.js";
import type * as emailService_plain_text from "../emailService_plain_text.js";
import type * as emailTemplateOntology from "../emailTemplateOntology.js";
import type * as emailTemplateRenderer from "../emailTemplateRenderer.js";
import type * as emailTemplateResolver from "../emailTemplateResolver.js";
import type * as emails from "../emails.js";
import type * as eventOntology from "../eventOntology.js";
import type * as feedback from "../feedback.js";
import type * as fileSystemOntology from "../fileSystemOntology.js";
import type * as files from "../files.js";
import type * as formTemplateAvailability from "../formTemplateAvailability.js";
import type * as formsOntology from "../formsOntology.js";
import type * as frontendUserQueries from "../frontendUserQueries.js";
import type * as growthTracking from "../growthTracking.js";
import type * as helpers_appHelpers from "../helpers/appHelpers.js";
import type * as helpers_backendTranslationHelper from "../helpers/backendTranslationHelper.js";
import type * as helpers_backendTranslationQueries from "../helpers/backendTranslationQueries.js";
import type * as helpers_orderEmailRenderer from "../helpers/orderEmailRenderer.js";
import type * as http from "../http.js";
import type * as icsGeneration from "../icsGeneration.js";
import type * as integrations_chatwoot from "../integrations/chatwoot.js";
import type * as integrations_github from "../integrations/github.js";
import type * as integrations_githubPR from "../integrations/githubPR.js";
import type * as integrations_infobip from "../integrations/infobip.js";
import type * as integrations_manychat from "../integrations/manychat.js";
import type * as integrations_pushover from "../integrations/pushover.js";
import type * as integrations_resend from "../integrations/resend.js";
import type * as integrations_resendResolver from "../integrations/resendResolver.js";
import type * as integrations_selfHealChat from "../integrations/selfHealChat.js";
import type * as integrations_selfHealDeploy from "../integrations/selfHealDeploy.js";
import type * as integrations_telegram from "../integrations/telegram.js";
import type * as integrations_v0 from "../integrations/v0.js";
import type * as integrations_vercel from "../integrations/vercel.js";
import type * as internal_ from "../internal.js";
import type * as interviewTemplateOntology from "../interviewTemplateOntology.js";
import type * as inventoryPricingOntology from "../inventoryPricingOntology.js";
import type * as invitationOntology from "../invitationOntology.js";
import type * as invoiceDataResolver from "../invoiceDataResolver.js";
import type * as invoiceEmailService from "../invoiceEmailService.js";
import type * as invoicingOntology from "../invoicingOntology.js";
import type * as layers_behaviorAdapter from "../layers/behaviorAdapter.js";
import type * as layers_executionLogger from "../layers/executionLogger.js";
import type * as layers_graphEngine from "../layers/graphEngine.js";
import type * as layers_layerWorkflowOntology from "../layers/layerWorkflowOntology.js";
import type * as layers_nodeExecutors from "../layers/nodeExecutors.js";
import type * as layers_nodeRegistry from "../layers/nodeRegistry.js";
import type * as layers_runWorkflow from "../layers/runWorkflow.js";
import type * as layers_types from "../layers/types.js";
import type * as legalEntityTypes from "../legalEntityTypes.js";
import type * as lib_addressFormatter from "../lib/addressFormatter.js";
import type * as lib_apiTemplateClient from "../lib/apiTemplateClient.js";
import type * as lib_connectionDetector from "../lib/connectionDetector.js";
import type * as lib_constants from "../lib/constants.js";
import type * as lib_currencyFormatter from "../lib/currencyFormatter.js";
import type * as lib_emailUrlHelpers from "../lib/emailUrlHelpers.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_generateInvoicePdf from "../lib/generateInvoicePdf.js";
import type * as lib_generatePdf from "../lib/generatePdf.js";
import type * as lib_generateTicketPdf from "../lib/generateTicketPdf.js";
import type * as lib_layerScope from "../lib/layerScope.js";
import type * as lib_ontologyHelpers from "../lib/ontologyHelpers.js";
import type * as lib_pdf_templates_badge_attendee from "../lib/pdf_templates/badge_attendee.js";
import type * as lib_pdf_templates_checklist_onepager from "../lib/pdf_templates/checklist_onepager.js";
import type * as lib_pdf_templates_ebook_guide from "../lib/pdf_templates/ebook_guide.js";
import type * as lib_pdf_templates_elegant_gold_ticket_template from "../lib/pdf_templates/elegant_gold_ticket_template.js";
import type * as lib_pdf_templates_invoice_b2b_single from "../lib/pdf_templates/invoice_b2b_single.js";
import type * as lib_pdf_templates_invoice_template from "../lib/pdf_templates/invoice_template.js";
import type * as lib_pdf_templates_modern_ticket_template from "../lib/pdf_templates/modern_ticket_template.js";
import type * as lib_pdf_templates_program_event from "../lib/pdf_templates/program_event.js";
import type * as lib_pdf_templates_quote_estimate from "../lib/pdf_templates/quote_estimate.js";
import type * as lib_pdf_templates_ticket_template from "../lib/pdf_templates/ticket_template.js";
import type * as lib_pdf_templates_vip_premium_ticket_template from "../lib/pdf_templates/vip_premium_ticket_template.js";
import type * as lib_vatValidation from "../lib/vatValidation.js";
import type * as licensing_appFeatureMapping from "../licensing/appFeatureMapping.js";
import type * as licensing_badgeVerification from "../licensing/badgeVerification.js";
import type * as licensing_helpers from "../licensing/helpers.js";
import type * as licensing_superAdmin from "../licensing/superAdmin.js";
import type * as licensing_tierConfigs from "../licensing/tierConfigs.js";
import type * as locationOntology from "../locationOntology.js";
import type * as manualOnboarding from "../manualOnboarding.js";
import type * as mediaFolderOntology from "../mediaFolderOntology.js";
import type * as meetingOntology from "../meetingOntology.js";
import type * as middleware_anomalyDetection from "../middleware/anomalyDetection.js";
import type * as middleware_anomalyDetectionDb from "../middleware/anomalyDetectionDb.js";
import type * as middleware_anomalyDetectionExample from "../middleware/anomalyDetectionExample.js";
import type * as middleware_auth from "../middleware/auth.js";
import type * as middleware_rateLimit from "../middleware/rateLimit.js";
import type * as middleware_rateLimitDb from "../middleware/rateLimitDb.js";
import type * as middleware_rateLimitExample from "../middleware/rateLimitExample.js";
import type * as migrateCleanupTemplates from "../migrateCleanupTemplates.js";
import type * as migratePdfTemplates from "../migratePdfTemplates.js";
import type * as migrateTemplateSubtypes from "../migrateTemplateSubtypes.js";
import type * as migrations_addOrganizationIdToSessions from "../migrations/addOrganizationIdToSessions.js";
import type * as migrations_betaAccessMigration from "../migrations/betaAccessMigration.js";
import type * as migrations_cleanupDuplicateOAuthConnections from "../migrations/cleanupDuplicateOAuthConnections.js";
import type * as migrations_cleanupExpiredOAuthStates from "../migrations/cleanupExpiredOAuthStates.js";
import type * as migrations_deleteOldSessions from "../migrations/deleteOldSessions.js";
import type * as migrations_migratePageTemplates from "../migrations/migratePageTemplates.js";
import type * as migrations_migratePaymentProviders from "../migrations/migratePaymentProviders.js";
import type * as migrations_updateExistingHaffForms from "../migrations/updateExistingHaffForms.js";
import type * as muxWebhookVerify from "../muxWebhookVerify.js";
import type * as oauth_activecampaign from "../oauth/activecampaign.js";
import type * as oauth_activecampaignSync from "../oauth/activecampaignSync.js";
import type * as oauth_activecampaignWebhook from "../oauth/activecampaignWebhook.js";
import type * as oauth_applications from "../oauth/applications.js";
import type * as oauth_authorize from "../oauth/authorize.js";
import type * as oauth_config from "../oauth/config.js";
import type * as oauth_emailSenderSelection from "../oauth/emailSenderSelection.js";
import type * as oauth_emailSending from "../oauth/emailSending.js";
import type * as oauth_encryption from "../oauth/encryption.js";
import type * as oauth_endpoints from "../oauth/endpoints.js";
import type * as oauth_github from "../oauth/github.js";
import type * as oauth_google from "../oauth/google.js";
import type * as oauth_googleClient from "../oauth/googleClient.js";
import type * as oauth_googleScopes from "../oauth/googleScopes.js";
import type * as oauth_graphClient from "../oauth/graphClient.js";
import type * as oauth_helpers from "../oauth/helpers.js";
import type * as oauth_microsoft from "../oauth/microsoft.js";
import type * as oauth_microsoftScopes from "../oauth/microsoftScopes.js";
import type * as oauth_queries from "../oauth/queries.js";
import type * as oauth_quotas from "../oauth/quotas.js";
import type * as oauth_scopes from "../oauth/scopes.js";
import type * as oauth_tokens from "../oauth/tokens.js";
import type * as oauth_vercel from "../oauth/vercel.js";
import type * as oauth_verifiedIntegrations from "../oauth/verifiedIntegrations.js";
import type * as oauth_whatsapp from "../oauth/whatsapp.js";
import type * as objectLinksInternal from "../objectLinksInternal.js";
import type * as objectsInternal from "../objectsInternal.js";
import type * as onboarding_agencySubOrgBootstrap from "../onboarding/agencySubOrgBootstrap.js";
import type * as onboarding_completeOnboarding from "../onboarding/completeOnboarding.js";
import type * as onboarding_orgBootstrap from "../onboarding/orgBootstrap.js";
import type * as onboarding_seedPlatformAgents from "../onboarding/seedPlatformAgents.js";
import type * as onboarding_telegramLinking from "../onboarding/telegramLinking.js";
import type * as onboarding_telegramResolver from "../onboarding/telegramResolver.js";
import type * as onboarding from "../onboarding.js";
import type * as ontologyHelpers from "../ontologyHelpers.js";
import type * as ontologyTranslations from "../ontologyTranslations.js";
import type * as organizationApiSettings from "../organizationApiSettings.js";
import type * as organizationInvoiceSettings from "../organizationInvoiceSettings.js";
import type * as organizationMedia from "../organizationMedia.js";
import type * as organizationMutations from "../organizationMutations.js";
import type * as organizationOntology from "../organizationOntology.js";
import type * as organizationPaymentSettings from "../organizationPaymentSettings.js";
import type * as organizationTaxSettings from "../organizationTaxSettings.js";
import type * as organizations from "../organizations.js";
import type * as pageAnalytics from "../pageAnalytics.js";
import type * as pageBuilder from "../pageBuilder.js";
import type * as passkeys from "../passkeys.js";
import type * as paymentProviderOntology from "../paymentProviderOntology.js";
import type * as paymentProviders_helpers from "../paymentProviders/helpers.js";
import type * as paymentProviders_index from "../paymentProviders/index.js";
import type * as paymentProviders_invoice from "../paymentProviders/invoice.js";
import type * as paymentProviders_invoiceAvailability from "../paymentProviders/invoiceAvailability.js";
import type * as paymentProviders_manager from "../paymentProviders/manager.js";
import type * as paymentProviders_stripe from "../paymentProviders/stripe.js";
import type * as paymentProviders_types from "../paymentProviders/types.js";
import type * as paymentRulesEngine from "../paymentRulesEngine.js";
import type * as pdf_invoicePdf from "../pdf/invoicePdf.js";
import type * as pdf_ticketPdf from "../pdf/ticketPdf.js";
import type * as pdfGeneration from "../pdfGeneration.js";
import type * as pdfGenerationTemplated from "../pdfGenerationTemplated.js";
import type * as pdfTemplateAvailability from "../pdfTemplateAvailability.js";
import type * as pdfTemplateQueries from "../pdfTemplateQueries.js";
import type * as pdfTemplateRegistry from "../pdfTemplateRegistry.js";
import type * as pdfTemplateResolver from "../pdfTemplateResolver.js";
import type * as pdfTemplates from "../pdfTemplates.js";
import type * as pdfTicketTemplateRenderer from "../pdfTicketTemplateRenderer.js";
import type * as permissionErrors from "../permissionErrors.js";
import type * as portalAuth from "../portalAuth.js";
import type * as portalInvitations from "../portalInvitations.js";
import type * as productOntology from "../productOntology.js";
import type * as projectAnalytics from "../projectAnalytics.js";
import type * as projectContent from "../projectContent.js";
import type * as projectDrawerAuth from "../projectDrawerAuth.js";
import type * as projectFileSystem from "../projectFileSystem.js";
import type * as projectFileSystemInternal from "../projectFileSystemInternal.js";
import type * as projectOntology from "../projectOntology.js";
import type * as projectSharing from "../projectSharing.js";
import type * as publishingFreelancerPortal from "../publishingFreelancerPortal.js";
import type * as publishingHelpers from "../publishingHelpers.js";
import type * as publishingOntology from "../publishingOntology.js";
import type * as purchaseOntology from "../purchaseOntology.js";
import type * as rbac from "../rbac.js";
import type * as rbacHelpers from "../rbacHelpers.js";
import type * as rbacQueries from "../rbacQueries.js";
import type * as registerAIAssistantApp from "../registerAIAssistantApp.js";
import type * as salesNotifications from "../salesNotifications.js";
import type * as schema_shapes from "../schema/shapes.js";
import type * as schemas_activityProtocolSchemas from "../schemas/activityProtocolSchemas.js";
import type * as schemas_agentSessionSchemas from "../schemas/agentSessionSchemas.js";
import type * as schemas_aiBillingSchemas from "../schemas/aiBillingSchemas.js";
import type * as schemas_aiSchemas from "../schemas/aiSchemas.js";
import type * as schemas_appDataSchemas from "../schemas/appDataSchemas.js";
import type * as schemas_appSchemaBase from "../schemas/appSchemaBase.js";
import type * as schemas_appStoreSchemas from "../schemas/appStoreSchemas.js";
import type * as schemas_benefitsSchemas from "../schemas/benefitsSchemas.js";
import type * as schemas_builderFileSchemas from "../schemas/builderFileSchemas.js";
import type * as schemas_contactSyncSchemas from "../schemas/contactSyncSchemas.js";
import type * as schemas_coreSchemas from "../schemas/coreSchemas.js";
import type * as schemas_creditSchemas from "../schemas/creditSchemas.js";
import type * as schemas_designPatternSchemas from "../schemas/designPatternSchemas.js";
import type * as schemas_emailQueueSchemas from "../schemas/emailQueueSchemas.js";
import type * as schemas_growthTrackingSchemas from "../schemas/growthTrackingSchemas.js";
import type * as schemas_interviewSchemas from "../schemas/interviewSchemas.js";
import type * as schemas_layerExecutionSchemas from "../schemas/layerExecutionSchemas.js";
import type * as schemas_messageQueueSchema from "../schemas/messageQueueSchema.js";
import type * as schemas_oauthSchemas from "../schemas/oauthSchemas.js";
import type * as schemas_ontologySchemas from "../schemas/ontologySchemas.js";
import type * as schemas_projectFileSchemas from "../schemas/projectFileSchemas.js";
import type * as schemas_rateLimitSchemas from "../schemas/rateLimitSchemas.js";
import type * as schemas_securitySchemas from "../schemas/securitySchemas.js";
import type * as schemas_soulEvolutionSchemas from "../schemas/soulEvolutionSchemas.js";
import type * as schemas_storageSchemas from "../schemas/storageSchemas.js";
import type * as schemas_telegramSchemas from "../schemas/telegramSchemas.js";
import type * as schemas_transactionStrictSchemas from "../schemas/transactionStrictSchemas.js";
import type * as schemas_translationSchemas from "../schemas/translationSchemas.js";
import type * as schemas_userQuotaSchemas from "../schemas/userQuotaSchemas.js";
import type * as schemas_utilitySchemas from "../schemas/utilitySchemas.js";
import type * as schemas_webchatSchemas from "../schemas/webchatSchemas.js";
import type * as security_actions from "../security/actions.js";
import type * as security_usageTracking from "../security/usageTracking.js";
import type * as security_usageTrackingExample from "../security/usageTrackingExample.js";
import type * as seed_seedSyntheticTraining from "../seed/seedSyntheticTraining.js";
import type * as seed_syntheticTemplates from "../seed/syntheticTemplates.js";
import type * as seedAdmin from "../seedAdmin.js";
import type * as seedAllSchemaTemplates from "../seedAllSchemaTemplates.js";
import type * as seedApps from "../seedApps.js";
import type * as seedCheckoutApp from "../seedCheckoutApp.js";
import type * as seedCheckoutTemplates from "../seedCheckoutTemplates.js";
import type * as seedConsolidatedInvoiceWorkflow from "../seedConsolidatedInvoiceWorkflow.js";
import type * as seedEmailTemplates from "../seedEmailTemplates.js";
import type * as seedEventConfirmationTemplate from "../seedEventConfirmationTemplate.js";
import type * as seedFormTemplates from "../seedFormTemplates.js";
import type * as seedInvoiceB2BTemplate from "../seedInvoiceB2BTemplate.js";
import type * as seedInvoiceEmailTemplate from "../seedInvoiceEmailTemplate.js";
import type * as seedInvoiceEmailTemplateV2 from "../seedInvoiceEmailTemplateV2.js";
import type * as seedNewsletterTemplate from "../seedNewsletterTemplate.js";
import type * as seedOntologyData from "../seedOntologyData.js";
import type * as seedPdfTemplates from "../seedPdfTemplates.js";
import type * as seedProjectDrawerTest from "../seedProjectDrawerTest.js";
import type * as seedSalesNotificationTemplate from "../seedSalesNotificationTemplate.js";
import type * as seedSystemDefaultTemplateSet from "../seedSystemDefaultTemplateSet.js";
import type * as seedSystemDomainConfig from "../seedSystemDomainConfig.js";
import type * as seedTemplateSet from "../seedTemplateSet.js";
import type * as seedTemplates from "../seedTemplates.js";
import type * as seedTicketPdfTemplate from "../seedTicketPdfTemplate.js";
import type * as seedTransactionReceiptTemplate from "../seedTransactionReceiptTemplate.js";
import type * as seedWorkflowTemplates from "../seedWorkflowTemplates.js";
import type * as seeds_interviewTemplates from "../seeds/interviewTemplates.js";
import type * as seeds_provisionTemplatesForExistingOrg from "../seeds/provisionTemplatesForExistingOrg.js";
import type * as seeds_seedFreelancerPortalTemplate from "../seeds/seedFreelancerPortalTemplate.js";
import type * as sequences_enrollmentOntology from "../sequences/enrollmentOntology.js";
import type * as sequences_exitHandler from "../sequences/exitHandler.js";
import type * as sequences_messageQueueProcessor from "../sequences/messageQueueProcessor.js";
import type * as sequences_messageSender from "../sequences/messageSender.js";
import type * as sequences_sequenceOntology from "../sequences/sequenceOntology.js";
import type * as sequences_sequenceProcessor from "../sequences/sequenceProcessor.js";
import type * as sequences_sequenceTriggers from "../sequences/sequenceTriggers.js";
import type * as sequences_stepExecutor from "../sequences/stepExecutor.js";
import type * as sequences_templateOntology from "../sequences/templateOntology.js";
import type * as stripe_aiCheckout from "../stripe/aiCheckout.js";
import type * as stripe_aiWebhooks from "../stripe/aiWebhooks.js";
import type * as stripe_creditCheckout from "../stripe/creditCheckout.js";
import type * as stripe_platformCheckout from "../stripe/platformCheckout.js";
import type * as stripe_platformWebhooks from "../stripe/platformWebhooks.js";
import type * as stripe_smsCheckout from "../stripe/smsCheckout.js";
import type * as stripe_stripePrices from "../stripe/stripePrices.js";
import type * as stripe_trialCheckout from "../stripe/trialCheckout.js";
import type * as stripe_trialCron from "../stripe/trialCron.js";
import type * as stripe_trialEmails from "../stripe/trialEmails.js";
import type * as stripe_trialHelpers from "../stripe/trialHelpers.js";
import type * as stripeCheckout from "../stripeCheckout.js";
import type * as stripeConnect from "../stripeConnect.js";
import type * as stripeInvoices from "../stripeInvoices.js";
import type * as stripeRefunds from "../stripeRefunds.js";
import type * as stripeWebhooks from "../stripeWebhooks.js";
import type * as templateAvailability from "../templateAvailability.js";
import type * as templateOntology from "../templateOntology.js";
import type * as templateSetAvailability from "../templateSetAvailability.js";
import type * as templateSetOntology from "../templateSetOntology.js";
import type * as templateSetQueries from "../templateSetQueries.js";
import type * as templateSetResolver from "../templateSetResolver.js";
import type * as templateUsageStats from "../templateUsageStats.js";
import type * as terminal_terminalFeed from "../terminal/terminalFeed.js";
import type * as testEmailTemplates from "../testEmailTemplates.js";
import type * as testHelpers from "../testHelpers.js";
import type * as testInspectTemplate from "../testInspectTemplate.js";
import type * as ticketEmailService from "../ticketEmailService.js";
import type * as ticketGeneration from "../ticketGeneration.js";
import type * as ticketOntology from "../ticketOntology.js";
import type * as transactionCorrections from "../transactionCorrections.js";
import type * as transactionHelpers from "../transactionHelpers.js";
import type * as transactionInvoicing from "../transactionInvoicing.js";
import type * as transactionOntology from "../transactionOntology.js";
import type * as transactionOntologyStrict from "../transactionOntologyStrict.js";
import type * as translationResolver from "../translationResolver.js";
import type * as translations__translationHelpers from "../translations/_translationHelpers.js";
import type * as translations_seedAIAssistant from "../translations/seedAIAssistant.js";
import type * as translations_seedAddressTranslations from "../translations/seedAddressTranslations.js";
import type * as translations_seedBenefitsWindowTranslations from "../translations/seedBenefitsWindowTranslations.js";
import type * as translations_seedCRM_01_OrganizationForm from "../translations/seedCRM_01_OrganizationForm.js";
import type * as translations_seedCRM_02_MainWindow from "../translations/seedCRM_02_MainWindow.js";
import type * as translations_seedCRM_03_ContactForm from "../translations/seedCRM_03_ContactForm.js";
import type * as translations_seedCRM_04_Pipeline from "../translations/seedCRM_04_Pipeline.js";
import type * as translations_seedCRM_05_SystemPipelineTemplate from "../translations/seedCRM_05_SystemPipelineTemplate.js";
import type * as translations_seedCRM_06_NotificationsAndPipelines from "../translations/seedCRM_06_NotificationsAndPipelines.js";
import type * as translations_seedCertificatesTranslations from "../translations/seedCertificatesTranslations.js";
import type * as translations_seedCheckoutFailed from "../translations/seedCheckoutFailed.js";
import type * as translations_seedCheckoutSuccess from "../translations/seedCheckoutSuccess.js";
import type * as translations_seedCheckoutTemplate_00_Main from "../translations/seedCheckoutTemplate_00_Main.js";
import type * as translations_seedCheckoutTemplate_00_Progress from "../translations/seedCheckoutTemplate_00_Progress.js";
import type * as translations_seedCheckoutTemplate_01_ProductSelection from "../translations/seedCheckoutTemplate_01_ProductSelection.js";
import type * as translations_seedCheckoutTemplate_02_RegistrationForm from "../translations/seedCheckoutTemplate_02_RegistrationForm.js";
import type * as translations_seedCheckoutTemplate_03_CustomerInfo from "../translations/seedCheckoutTemplate_03_CustomerInfo.js";
import type * as translations_seedCheckoutTemplate_04_ReviewOrder from "../translations/seedCheckoutTemplate_04_ReviewOrder.js";
import type * as translations_seedCheckoutTemplate_05_Payment from "../translations/seedCheckoutTemplate_05_Payment.js";
import type * as translations_seedCheckoutTemplate_05a_PaymentMethods from "../translations/seedCheckoutTemplate_05a_PaymentMethods.js";
import type * as translations_seedCheckoutTemplate_05b_PaymentForm from "../translations/seedCheckoutTemplate_05b_PaymentForm.js";
import type * as translations_seedCheckoutTemplate_06_Confirmation from "../translations/seedCheckoutTemplate_06_Confirmation.js";
import type * as translations_seedCheckoutTemplate_06a_ConfirmationSuccess from "../translations/seedCheckoutTemplate_06a_ConfirmationSuccess.js";
import type * as translations_seedCheckoutTemplate_06b_ConfirmationInvoice from "../translations/seedCheckoutTemplate_06b_ConfirmationInvoice.js";
import type * as translations_seedCheckoutWindow from "../translations/seedCheckoutWindow.js";
import type * as translations_seedCheckout_01_CustomerInfo from "../translations/seedCheckout_01_CustomerInfo.js";
import type * as translations_seedCheckout_01a_BasicInfo from "../translations/seedCheckout_01a_BasicInfo.js";
import type * as translations_seedCheckout_01b_Errors from "../translations/seedCheckout_01b_Errors.js";
import type * as translations_seedCheckout_01c_B2BFields from "../translations/seedCheckout_01c_B2BFields.js";
import type * as translations_seedCheckout_02_PaymentForm from "../translations/seedCheckout_02_PaymentForm.js";
import type * as translations_seedCheckout_03_Confirmation from "../translations/seedCheckout_03_Confirmation.js";
import type * as translations_seedCheckout_04_InvoiceEnforcement from "../translations/seedCheckout_04_InvoiceEnforcement.js";
import type * as translations_seedCheckout_05_RegistrationForm from "../translations/seedCheckout_05_RegistrationForm.js";
import type * as translations_seedCommonMonths from "../translations/seedCommonMonths.js";
import type * as translations_seedCompliance from "../translations/seedCompliance.js";
import type * as translations_seedContactModal from "../translations/seedContactModal.js";
import type * as translations_seedControlPanel from "../translations/seedControlPanel.js";
import type * as translations_seedDesktop from "../translations/seedDesktop.js";
import type * as translations_seedEmailTemplates from "../translations/seedEmailTemplates.js";
import type * as translations_seedEventLanding_00_Main from "../translations/seedEventLanding_00_Main.js";
import type * as translations_seedEventLanding_01_Navigation from "../translations/seedEventLanding_01_Navigation.js";
import type * as translations_seedEventLanding_02_HeroAndVenue from "../translations/seedEventLanding_02_HeroAndVenue.js";
import type * as translations_seedEventLanding_03_Checkout from "../translations/seedEventLanding_03_Checkout.js";
import type * as translations_seedEventLanding_04_AgendaAndDates from "../translations/seedEventLanding_04_AgendaAndDates.js";
import type * as translations_seedEventLanding_05_Format from "../translations/seedEventLanding_05_Format.js";
import type * as translations_seedEventsTranslations from "../translations/seedEventsTranslations.js";
import type * as translations_seedEvents_00_Main from "../translations/seedEvents_00_Main.js";
import type * as translations_seedEvents_01_FormBasics from "../translations/seedEvents_01_FormBasics.js";
import type * as translations_seedEvents_02_FormMedia from "../translations/seedEvents_02_FormMedia.js";
import type * as translations_seedEvents_03_FormAgenda from "../translations/seedEvents_03_FormAgenda.js";
import type * as translations_seedEvents_04_FormSponsors from "../translations/seedEvents_04_FormSponsors.js";
import type * as translations_seedEvents_05_FormDescription from "../translations/seedEvents_05_FormDescription.js";
import type * as translations_seedEvents_06_DetailModal from "../translations/seedEvents_06_DetailModal.js";
import type * as translations_seedFormsResponses_DE from "../translations/seedFormsResponses_DE.js";
import type * as translations_seedFormsResponses_EN from "../translations/seedFormsResponses_EN.js";
import type * as translations_seedFormsResponses_ES from "../translations/seedFormsResponses_ES.js";
import type * as translations_seedFormsResponses_FR from "../translations/seedFormsResponses_FR.js";
import type * as translations_seedFormsResponses_JA from "../translations/seedFormsResponses_JA.js";
import type * as translations_seedFormsResponses_PL from "../translations/seedFormsResponses_PL.js";
import type * as translations_seedFormsWindowTranslations from "../translations/seedFormsWindowTranslations.js";
import type * as translations_seedIntegrationsWindow from "../translations/seedIntegrationsWindow.js";
import type * as translations_seedInvoicingTranslations from "../translations/seedInvoicingTranslations.js";
import type * as translations_seedInvoicingWindow_Templates from "../translations/seedInvoicingWindow_Templates.js";
import type * as translations_seedLogin from "../translations/seedLogin.js";
import type * as translations_seedLogin_01_BasicAuth from "../translations/seedLogin_01_BasicAuth.js";
import type * as translations_seedLogin_02_Forms from "../translations/seedLogin_02_Forms.js";
import type * as translations_seedLogin_03_Buttons from "../translations/seedLogin_03_Buttons.js";
import type * as translations_seedLogin_03a_Buttons from "../translations/seedLogin_03a_Buttons.js";
import type * as translations_seedLogin_03b_Errors from "../translations/seedLogin_03b_Errors.js";
import type * as translations_seedLogin_04_Passkeys from "../translations/seedLogin_04_Passkeys.js";
import type * as translations_seedManage_01_MainWindow from "../translations/seedManage_01_MainWindow.js";
import type * as translations_seedManage_02_Organization from "../translations/seedManage_02_Organization.js";
import type * as translations_seedManage_03_Users from "../translations/seedManage_03_Users.js";
import type * as translations_seedManage_03b_DeleteAccount from "../translations/seedManage_03b_DeleteAccount.js";
import type * as translations_seedManage_04_RolesPermissions from "../translations/seedManage_04_RolesPermissions.js";
import type * as translations_seedManage_05_Security from "../translations/seedManage_05_Security.js";
import type * as translations_seedManage_06_DomainConfig from "../translations/seedManage_06_DomainConfig.js";
import type * as translations_seedManage_07_Integrations from "../translations/seedManage_07_Integrations.js";
import type * as translations_seedManage_08_AISettings from "../translations/seedManage_08_AISettings.js";
import type * as translations_seedMediaLibrary from "../translations/seedMediaLibrary.js";
import type * as translations_seedNotifications from "../translations/seedNotifications.js";
import type * as translations_seedOrganizations from "../translations/seedOrganizations.js";
import type * as translations_seedPaymentTranslations from "../translations/seedPaymentTranslations.js";
import type * as translations_seedPdfTemplates from "../translations/seedPdfTemplates.js";
import type * as translations_seedProcessingModal from "../translations/seedProcessingModal.js";
import type * as translations_seedProductTranslations from "../translations/seedProductTranslations.js";
import type * as translations_seedProductTranslations_es from "../translations/seedProductTranslations_es.js";
import type * as translations_seedProductTranslations_fr from "../translations/seedProductTranslations_fr.js";
import type * as translations_seedProductTranslations_ja from "../translations/seedProductTranslations_ja.js";
import type * as translations_seedProductTranslations_pl from "../translations/seedProductTranslations_pl.js";
import type * as translations_seedProfileTranslations from "../translations/seedProfileTranslations.js";
import type * as translations_seedSettings from "../translations/seedSettings.js";
import type * as translations_seedShoppingCart from "../translations/seedShoppingCart.js";
import type * as translations_seedStartMenu from "../translations/seedStartMenu.js";
import type * as translations_seedStore from "../translations/seedStore.js";
import type * as translations_seedStoreButtons from "../translations/seedStoreButtons.js";
import type * as translations_seedTemplatesTranslations from "../translations/seedTemplatesTranslations.js";
import type * as translations_seedTemplatesWindowTranslations from "../translations/seedTemplatesWindowTranslations.js";
import type * as translations_seedTicketsTranslations from "../translations/seedTicketsTranslations.js";
import type * as translations_seedWebPublishing from "../translations/seedWebPublishing.js";
import type * as translations_seedWelcomeTranslations from "../translations/seedWelcomeTranslations.js";
import type * as translations_seedWindowTitles from "../translations/seedWindowTitles.js";
import type * as translations_seedWorkflowsTranslations from "../translations/seedWorkflowsTranslations.js";
import type * as translations_updateBranding from "../translations/updateBranding.js";
import type * as tutorialOntology from "../tutorialOntology.js";
import type * as types_ontology from "../types/ontology.js";
import type * as userPreferences from "../userPreferences.js";
import type * as vatValidation from "../vatValidation.js";
import type * as venueOntology from "../venueOntology.js";
import type * as webinarOntology from "../webinarOntology.js";
import type * as webinarRegistrants from "../webinarRegistrants.js";
import type * as workflowExecutionLogs from "../workflowExecutionLogs.js";
import type * as workflowTemplateAvailability from "../workflowTemplateAvailability.js";
import type * as workflows_behaviorExecutor from "../workflows/behaviorExecutor.js";
import type * as workflows_behaviors_activeCampaignSync from "../workflows/behaviors/activeCampaignSync.js";
import type * as workflows_behaviors_calculatePricing from "../workflows/behaviors/calculatePricing.js";
import type * as workflows_behaviors_checkEventCapacity from "../workflows/behaviors/checkEventCapacity.js";
import type * as workflows_behaviors_consolidatedInvoiceGeneration from "../workflows/behaviors/consolidatedInvoiceGeneration.js";
import type * as workflows_behaviors_createContact from "../workflows/behaviors/createContact.js";
import type * as workflows_behaviors_createFormResponse from "../workflows/behaviors/createFormResponse.js";
import type * as workflows_behaviors_createTicket from "../workflows/behaviors/createTicket.js";
import type * as workflows_behaviors_createTransaction from "../workflows/behaviors/createTransaction.js";
import type * as workflows_behaviors_detectEmployerBilling from "../workflows/behaviors/detectEmployerBilling.js";
import type * as workflows_behaviors_generateInvoice from "../workflows/behaviors/generateInvoice.js";
import type * as workflows_behaviors_sendAdminNotification from "../workflows/behaviors/sendAdminNotification.js";
import type * as workflows_behaviors_sendConfirmationEmail from "../workflows/behaviors/sendConfirmationEmail.js";
import type * as workflows_behaviors_updateStatistics from "../workflows/behaviors/updateStatistics.js";
import type * as workflows_behaviors_validateRegistration from "../workflows/behaviors/validateRegistration.js";
import type * as workflows_workflowExecution from "../workflows/workflowExecution.js";
import type * as workflows_workflowOntology from "../workflows/workflowOntology.js";
import type * as workflows_workflowTemplates from "../workflows/workflowTemplates.js";
import type * as workflows_workflowTestExecution from "../workflows/workflowTestExecution.js";
import type * as workflows_workflowValidation from "../workflows/workflowValidation.js";
import type * as zapier_triggers from "../zapier/triggers.js";
import type * as zapier_webhooks from "../zapier/webhooks.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  accountManagement: typeof accountManagement;
  "actions/apiKeys": typeof actions_apiKeys;
  "actions/betaAccessEmails": typeof actions_betaAccessEmails;
  "actions/feedbackEmail": typeof actions_feedbackEmail;
  "actions/mux": typeof actions_mux;
  "actions/salesNotificationEmail": typeof actions_salesNotificationEmail;
  "actions/subscriptionEmails": typeof actions_subscriptionEmails;
  "actions/welcomeEmail": typeof actions_welcomeEmail;
  activityProtocol: typeof activityProtocol;
  addressValidation: typeof addressValidation;
  agentOntology: typeof agentOntology;
  "ai/agentApprovals": typeof ai_agentApprovals;
  "ai/agentExecution": typeof ai_agentExecution;
  "ai/agentSessions": typeof ai_agentSessions;
  "ai/billing": typeof ai_billing;
  "ai/campaigns": typeof ai_campaigns;
  "ai/chat": typeof ai_chat;
  "ai/contactSyncs": typeof ai_contactSyncs;
  "ai/conversations": typeof ai_conversations;
  "ai/deadLetterQueue": typeof ai_deadLetterQueue;
  "ai/drafts": typeof ai_drafts;
  "ai/errorMessages": typeof ai_errorMessages;
  "ai/escalation": typeof ai_escalation;
  "ai/featureRequestEmail": typeof ai_featureRequestEmail;
  "ai/harness": typeof ai_harness;
  "ai/i18nHelper": typeof ai_i18nHelper;
  "ai/interviewRunner": typeof ai_interviewRunner;
  "ai/linearActions": typeof ai_linearActions;
  "ai/linearClient": typeof ai_linearClient;
  "ai/manualGrants": typeof ai_manualGrants;
  "ai/modelAdapters": typeof ai_modelAdapters;
  "ai/modelDiscovery": typeof ai_modelDiscovery;
  "ai/openrouter": typeof ai_openrouter;
  "ai/platformAlerts": typeof ai_platformAlerts;
  "ai/platformModelManagement": typeof ai_platformModelManagement;
  "ai/platformModels": typeof ai_platformModels;
  "ai/prompts/layersBuilderSystem": typeof ai_prompts_layersBuilderSystem;
  "ai/prompts/pageBuilderSystem": typeof ai_prompts_pageBuilderSystem;
  "ai/resetAISettings": typeof ai_resetAISettings;
  "ai/retryPolicy": typeof ai_retryPolicy;
  "ai/selfImprovement": typeof ai_selfImprovement;
  "ai/sessionPolicy": typeof ai_sessionPolicy;
  "ai/settings": typeof ai_settings;
  "ai/skills/index": typeof ai_skills_index;
  "ai/soulEvolution": typeof ai_soulEvolution;
  "ai/soulGenerator": typeof ai_soulGenerator;
  "ai/systemKnowledge/_content": typeof ai_systemKnowledge__content;
  "ai/systemKnowledge/index": typeof ai_systemKnowledge_index;
  "ai/teamHarness": typeof ai_teamHarness;
  "ai/toolBroker": typeof ai_toolBroker;
  "ai/toolScoping": typeof ai_toolScoping;
  "ai/tools/activeCampaignTool": typeof ai_tools_activeCampaignTool;
  "ai/tools/activityProtocolTool": typeof ai_tools_activityProtocolTool;
  "ai/tools/agencyTools": typeof ai_tools_agencyTools;
  "ai/tools/benefitsTool": typeof ai_tools_benefitsTool;
  "ai/tools/bookingTool": typeof ai_tools_bookingTool;
  "ai/tools/bookingWorkflowTool": typeof ai_tools_bookingWorkflowTool;
  "ai/tools/builderToolActions": typeof ai_tools_builderToolActions;
  "ai/tools/builderTools": typeof ai_tools_builderTools;
  "ai/tools/bulkCRMEmailTool": typeof ai_tools_bulkCRMEmailTool;
  "ai/tools/connectionToolActions": typeof ai_tools_connectionToolActions;
  "ai/tools/connectionTools": typeof ai_tools_connectionTools;
  "ai/tools/contactSyncTool": typeof ai_tools_contactSyncTool;
  "ai/tools/coordinatorTools": typeof ai_tools_coordinatorTools;
  "ai/tools/crmTool": typeof ai_tools_crmTool;
  "ai/tools/dataQueryInternal": typeof ai_tools_dataQueryInternal;
  "ai/tools/dataQueryTool": typeof ai_tools_dataQueryTool;
  "ai/tools/formsTool": typeof ai_tools_formsTool;
  "ai/tools/internalToolMutations": typeof ai_tools_internalToolMutations;
  "ai/tools/interviewTools": typeof ai_tools_interviewTools;
  "ai/tools/layersWorkflowTool": typeof ai_tools_layersWorkflowTool;
  "ai/tools/linkObjectsTool": typeof ai_tools_linkObjectsTool;
  "ai/tools/mediaTools": typeof ai_tools_mediaTools;
  "ai/tools/projectsTool": typeof ai_tools_projectsTool;
  "ai/tools/registry": typeof ai_tools_registry;
  "ai/tools/sequencesTool": typeof ai_tools_sequencesTool;
  "ai/tools/soulEvolutionTools": typeof ai_tools_soulEvolutionTools;
  "ai/tools/teamTools": typeof ai_tools_teamTools;
  "ai/tools/unsplashTool": typeof ai_tools_unsplashTool;
  "ai/tools/webinarTool": typeof ai_tools_webinarTool;
  "ai/trainingData": typeof ai_trainingData;
  "ai/trainingExport": typeof ai_trainingExport;
  "ai/webReader": typeof ai_webReader;
  "ai/workItemActions": typeof ai_workItemActions;
  "ai/workItems": typeof ai_workItems;
  "ai/workerPool": typeof ai_workerPool;
  "api/auth": typeof api_auth;
  "api/v1/accountLinking": typeof api_v1_accountLinking;
  "api/v1/accountLinkingInternal": typeof api_v1_accountLinkingInternal;
  "api/v1/activecampaign": typeof api_v1_activecampaign;
  "api/v1/activityProtocol": typeof api_v1_activityProtocol;
  "api/v1/activityProtocolInternal": typeof api_v1_activityProtocolInternal;
  "api/v1/aiChat": typeof api_v1_aiChat;
  "api/v1/aiChatInternal": typeof api_v1_aiChatInternal;
  "api/v1/appManifestSchema": typeof api_v1_appManifestSchema;
  "api/v1/auth": typeof api_v1_auth;
  "api/v1/availability": typeof api_v1_availability;
  "api/v1/benefits": typeof api_v1_benefits;
  "api/v1/benefitsInternal": typeof api_v1_benefitsInternal;
  "api/v1/bookings": typeof api_v1_bookings;
  "api/v1/bookingsInternal": typeof api_v1_bookingsInternal;
  "api/v1/certificates": typeof api_v1_certificates;
  "api/v1/certificatesInternal": typeof api_v1_certificatesInternal;
  "api/v1/checkout": typeof api_v1_checkout;
  "api/v1/checkoutCrudInternal": typeof api_v1_checkoutCrudInternal;
  "api/v1/checkoutInternal": typeof api_v1_checkoutInternal;
  "api/v1/cliApplications": typeof api_v1_cliApplications;
  "api/v1/cliApplicationsInternal": typeof api_v1_cliApplicationsInternal;
  "api/v1/cliAuth": typeof api_v1_cliAuth;
  "api/v1/cliAuthHttp": typeof api_v1_cliAuthHttp;
  "api/v1/conversations": typeof api_v1_conversations;
  "api/v1/conversationsInternal": typeof api_v1_conversationsInternal;
  "api/v1/corsHeaders": typeof api_v1_corsHeaders;
  "api/v1/crm": typeof api_v1_crm;
  "api/v1/crmInternal": typeof api_v1_crmInternal;
  "api/v1/customerAuth": typeof api_v1_customerAuth;
  "api/v1/customerAuthInternal": typeof api_v1_customerAuthInternal;
  "api/v1/domainLookup": typeof api_v1_domainLookup;
  "api/v1/domainLookupInternal": typeof api_v1_domainLookupInternal;
  "api/v1/emailAuth": typeof api_v1_emailAuth;
  "api/v1/emailAuthInternal": typeof api_v1_emailAuthInternal;
  "api/v1/events": typeof api_v1_events;
  "api/v1/eventsInternal": typeof api_v1_eventsInternal;
  "api/v1/externalDomains": typeof api_v1_externalDomains;
  "api/v1/forms": typeof api_v1_forms;
  "api/v1/formsInternal": typeof api_v1_formsInternal;
  "api/v1/httpHelpers": typeof api_v1_httpHelpers;
  "api/v1/invoices": typeof api_v1_invoices;
  "api/v1/invoicesInternal": typeof api_v1_invoicesInternal;
  "api/v1/locations": typeof api_v1_locations;
  "api/v1/mobileOAuth": typeof api_v1_mobileOAuth;
  "api/v1/mobileOAuthInternal": typeof api_v1_mobileOAuthInternal;
  "api/v1/notifications": typeof api_v1_notifications;
  "api/v1/oauthConnections": typeof api_v1_oauthConnections;
  "api/v1/oauthConnectionsInternal": typeof api_v1_oauthConnectionsInternal;
  "api/v1/oauthSignup": typeof api_v1_oauthSignup;
  "api/v1/products": typeof api_v1_products;
  "api/v1/productsInternal": typeof api_v1_productsInternal;
  "api/v1/projects": typeof api_v1_projects;
  "api/v1/projectsInternal": typeof api_v1_projectsInternal;
  "api/v1/publishing": typeof api_v1_publishing;
  "api/v1/publishingInternal": typeof api_v1_publishingInternal;
  "api/v1/resourceBookings": typeof api_v1_resourceBookings;
  "api/v1/resourceBookingsInternal": typeof api_v1_resourceBookingsInternal;
  "api/v1/stripeInvoiceWebhooks": typeof api_v1_stripeInvoiceWebhooks;
  "api/v1/subOrganizations": typeof api_v1_subOrganizations;
  "api/v1/subOrganizationsInternal": typeof api_v1_subOrganizationsInternal;
  "api/v1/templatesInternal": typeof api_v1_templatesInternal;
  "api/v1/tickets": typeof api_v1_tickets;
  "api/v1/ticketsInternal": typeof api_v1_ticketsInternal;
  "api/v1/transactions": typeof api_v1_transactions;
  "api/v1/transactionsInternal": typeof api_v1_transactionsInternal;
  "api/v1/users": typeof api_v1_users;
  "api/v1/webchatApi": typeof api_v1_webchatApi;
  "api/v1/webinars": typeof api_v1_webinars;
  "api/v1/webinarsInternal": typeof api_v1_webinarsInternal;
  "api/v1/workflows": typeof api_v1_workflows;
  "api/v1/workflowsCrudInternal": typeof api_v1_workflowsCrudInternal;
  "api/v1/workflowsInternal": typeof api_v1_workflowsInternal;
  "api/v1/workflowsInternal_OLD": typeof api_v1_workflowsInternal_OLD;
  apiKeysInternal: typeof apiKeysInternal;
  appAvailability: typeof appAvailability;
  applicationOntology: typeof applicationOntology;
  auditLogExport: typeof auditLogExport;
  auditTemplates: typeof auditTemplates;
  "auth/identity": typeof auth_identity;
  auth: typeof auth;
  availabilityOntology: typeof availabilityOntology;
  b2bInvoiceHelper: typeof b2bInvoiceHelper;
  benefitsMemberSync: typeof benefitsMemberSync;
  benefitsOntology: typeof benefitsOntology;
  betaAccess: typeof betaAccess;
  bookingOntology: typeof bookingOntology;
  builderAppOntology: typeof builderAppOntology;
  calendarSyncOntology: typeof calendarSyncOntology;
  calendarSyncSubcalendars: typeof calendarSyncSubcalendars;
  certificateOntology: typeof certificateOntology;
  "channels/infobipCpaasX": typeof channels_infobipCpaasX;
  "channels/platformSms": typeof channels_platformSms;
  "channels/providers/chatwoot": typeof channels_providers_chatwoot;
  "channels/providers/infobipProvider": typeof channels_providers_infobipProvider;
  "channels/providers/manychatAdapter": typeof channels_providers_manychatAdapter;
  "channels/providers/telegramProvider": typeof channels_providers_telegramProvider;
  "channels/providers/whatsappProvider": typeof channels_providers_whatsappProvider;
  "channels/registry": typeof channels_registry;
  "channels/router": typeof channels_router;
  "channels/telegramBotSetup": typeof channels_telegramBotSetup;
  "channels/telegramGroupMirror": typeof channels_telegramGroupMirror;
  "channels/telegramGroupSetup": typeof channels_telegramGroupSetup;
  "channels/types": typeof channels_types;
  "channels/webhooks": typeof channels_webhooks;
  checkTemplateById: typeof checkTemplateById;
  checkoutOntology: typeof checkoutOntology;
  checkoutSessionOntology: typeof checkoutSessionOntology;
  checkoutSessions: typeof checkoutSessions;
  checkoutTemplateAvailability: typeof checkoutTemplateAvailability;
  commissionsOntology: typeof commissionsOntology;
  communicationTracking: typeof communicationTracking;
  compliance: typeof compliance;
  consolidatedInvoicing: typeof consolidatedInvoicing;
  createTransactionsFromCheckout: typeof createTransactionsFromCheckout;
  "credits/index": typeof credits_index;
  "credits/notifications": typeof credits_notifications;
  "credits/sharing": typeof credits_sharing;
  crmAiTools: typeof crmAiTools;
  crmIntegrations: typeof crmIntegrations;
  crmOntology: typeof crmOntology;
  crmOrganizationPipelines: typeof crmOrganizationPipelines;
  crmPipeline: typeof crmPipeline;
  crmTags: typeof crmTags;
  crons: typeof crons;
  cryptoActions: typeof cryptoActions;
  departureOntology: typeof departureOntology;
  designEngine: typeof designEngine;
  domainConfigOntology: typeof domainConfigOntology;
  emailDelivery: typeof emailDelivery;
  emailQueue: typeof emailQueue;
  emailService: typeof emailService;
  emailService_plain_text: typeof emailService_plain_text;
  emailTemplateOntology: typeof emailTemplateOntology;
  emailTemplateRenderer: typeof emailTemplateRenderer;
  emailTemplateResolver: typeof emailTemplateResolver;
  emails: typeof emails;
  eventOntology: typeof eventOntology;
  feedback: typeof feedback;
  fileSystemOntology: typeof fileSystemOntology;
  files: typeof files;
  formTemplateAvailability: typeof formTemplateAvailability;
  formsOntology: typeof formsOntology;
  frontendUserQueries: typeof frontendUserQueries;
  growthTracking: typeof growthTracking;
  "helpers/appHelpers": typeof helpers_appHelpers;
  "helpers/backendTranslationHelper": typeof helpers_backendTranslationHelper;
  "helpers/backendTranslationQueries": typeof helpers_backendTranslationQueries;
  "helpers/orderEmailRenderer": typeof helpers_orderEmailRenderer;
  http: typeof http;
  icsGeneration: typeof icsGeneration;
  "integrations/chatwoot": typeof integrations_chatwoot;
  "integrations/github": typeof integrations_github;
  "integrations/githubPR": typeof integrations_githubPR;
  "integrations/infobip": typeof integrations_infobip;
  "integrations/manychat": typeof integrations_manychat;
  "integrations/pushover": typeof integrations_pushover;
  "integrations/resend": typeof integrations_resend;
  "integrations/resendResolver": typeof integrations_resendResolver;
  "integrations/selfHealChat": typeof integrations_selfHealChat;
  "integrations/selfHealDeploy": typeof integrations_selfHealDeploy;
  "integrations/telegram": typeof integrations_telegram;
  "integrations/v0": typeof integrations_v0;
  "integrations/vercel": typeof integrations_vercel;
  internal: typeof internal_;
  interviewTemplateOntology: typeof interviewTemplateOntology;
  inventoryPricingOntology: typeof inventoryPricingOntology;
  invitationOntology: typeof invitationOntology;
  invoiceDataResolver: typeof invoiceDataResolver;
  invoiceEmailService: typeof invoiceEmailService;
  invoicingOntology: typeof invoicingOntology;
  "layers/behaviorAdapter": typeof layers_behaviorAdapter;
  "layers/executionLogger": typeof layers_executionLogger;
  "layers/graphEngine": typeof layers_graphEngine;
  "layers/layerWorkflowOntology": typeof layers_layerWorkflowOntology;
  "layers/nodeExecutors": typeof layers_nodeExecutors;
  "layers/nodeRegistry": typeof layers_nodeRegistry;
  "layers/runWorkflow": typeof layers_runWorkflow;
  "layers/types": typeof layers_types;
  legalEntityTypes: typeof legalEntityTypes;
  "lib/addressFormatter": typeof lib_addressFormatter;
  "lib/apiTemplateClient": typeof lib_apiTemplateClient;
  "lib/connectionDetector": typeof lib_connectionDetector;
  "lib/constants": typeof lib_constants;
  "lib/currencyFormatter": typeof lib_currencyFormatter;
  "lib/emailUrlHelpers": typeof lib_emailUrlHelpers;
  "lib/errors": typeof lib_errors;
  "lib/generateInvoicePdf": typeof lib_generateInvoicePdf;
  "lib/generatePdf": typeof lib_generatePdf;
  "lib/generateTicketPdf": typeof lib_generateTicketPdf;
  "lib/layerScope": typeof lib_layerScope;
  "lib/ontologyHelpers": typeof lib_ontologyHelpers;
  "lib/pdf_templates/badge_attendee": typeof lib_pdf_templates_badge_attendee;
  "lib/pdf_templates/checklist_onepager": typeof lib_pdf_templates_checklist_onepager;
  "lib/pdf_templates/ebook_guide": typeof lib_pdf_templates_ebook_guide;
  "lib/pdf_templates/elegant_gold_ticket_template": typeof lib_pdf_templates_elegant_gold_ticket_template;
  "lib/pdf_templates/invoice_b2b_single": typeof lib_pdf_templates_invoice_b2b_single;
  "lib/pdf_templates/invoice_template": typeof lib_pdf_templates_invoice_template;
  "lib/pdf_templates/modern_ticket_template": typeof lib_pdf_templates_modern_ticket_template;
  "lib/pdf_templates/program_event": typeof lib_pdf_templates_program_event;
  "lib/pdf_templates/quote_estimate": typeof lib_pdf_templates_quote_estimate;
  "lib/pdf_templates/ticket_template": typeof lib_pdf_templates_ticket_template;
  "lib/pdf_templates/vip_premium_ticket_template": typeof lib_pdf_templates_vip_premium_ticket_template;
  "lib/vatValidation": typeof lib_vatValidation;
  "licensing/appFeatureMapping": typeof licensing_appFeatureMapping;
  "licensing/badgeVerification": typeof licensing_badgeVerification;
  "licensing/helpers": typeof licensing_helpers;
  "licensing/superAdmin": typeof licensing_superAdmin;
  "licensing/tierConfigs": typeof licensing_tierConfigs;
  locationOntology: typeof locationOntology;
  manualOnboarding: typeof manualOnboarding;
  mediaFolderOntology: typeof mediaFolderOntology;
  meetingOntology: typeof meetingOntology;
  "middleware/anomalyDetection": typeof middleware_anomalyDetection;
  "middleware/anomalyDetectionDb": typeof middleware_anomalyDetectionDb;
  "middleware/anomalyDetectionExample": typeof middleware_anomalyDetectionExample;
  "middleware/auth": typeof middleware_auth;
  "middleware/rateLimit": typeof middleware_rateLimit;
  "middleware/rateLimitDb": typeof middleware_rateLimitDb;
  "middleware/rateLimitExample": typeof middleware_rateLimitExample;
  migrateCleanupTemplates: typeof migrateCleanupTemplates;
  migratePdfTemplates: typeof migratePdfTemplates;
  migrateTemplateSubtypes: typeof migrateTemplateSubtypes;
  "migrations/addOrganizationIdToSessions": typeof migrations_addOrganizationIdToSessions;
  "migrations/betaAccessMigration": typeof migrations_betaAccessMigration;
  "migrations/cleanupDuplicateOAuthConnections": typeof migrations_cleanupDuplicateOAuthConnections;
  "migrations/cleanupExpiredOAuthStates": typeof migrations_cleanupExpiredOAuthStates;
  "migrations/deleteOldSessions": typeof migrations_deleteOldSessions;
  "migrations/migratePageTemplates": typeof migrations_migratePageTemplates;
  "migrations/migratePaymentProviders": typeof migrations_migratePaymentProviders;
  "migrations/updateExistingHaffForms": typeof migrations_updateExistingHaffForms;
  muxWebhookVerify: typeof muxWebhookVerify;
  "oauth/activecampaign": typeof oauth_activecampaign;
  "oauth/activecampaignSync": typeof oauth_activecampaignSync;
  "oauth/activecampaignWebhook": typeof oauth_activecampaignWebhook;
  "oauth/applications": typeof oauth_applications;
  "oauth/authorize": typeof oauth_authorize;
  "oauth/config": typeof oauth_config;
  "oauth/emailSenderSelection": typeof oauth_emailSenderSelection;
  "oauth/emailSending": typeof oauth_emailSending;
  "oauth/encryption": typeof oauth_encryption;
  "oauth/endpoints": typeof oauth_endpoints;
  "oauth/github": typeof oauth_github;
  "oauth/google": typeof oauth_google;
  "oauth/googleClient": typeof oauth_googleClient;
  "oauth/googleScopes": typeof oauth_googleScopes;
  "oauth/graphClient": typeof oauth_graphClient;
  "oauth/helpers": typeof oauth_helpers;
  "oauth/microsoft": typeof oauth_microsoft;
  "oauth/microsoftScopes": typeof oauth_microsoftScopes;
  "oauth/queries": typeof oauth_queries;
  "oauth/quotas": typeof oauth_quotas;
  "oauth/scopes": typeof oauth_scopes;
  "oauth/tokens": typeof oauth_tokens;
  "oauth/vercel": typeof oauth_vercel;
  "oauth/verifiedIntegrations": typeof oauth_verifiedIntegrations;
  "oauth/whatsapp": typeof oauth_whatsapp;
  objectLinksInternal: typeof objectLinksInternal;
  objectsInternal: typeof objectsInternal;
  "onboarding/agencySubOrgBootstrap": typeof onboarding_agencySubOrgBootstrap;
  "onboarding/completeOnboarding": typeof onboarding_completeOnboarding;
  "onboarding/orgBootstrap": typeof onboarding_orgBootstrap;
  "onboarding/seedPlatformAgents": typeof onboarding_seedPlatformAgents;
  "onboarding/telegramLinking": typeof onboarding_telegramLinking;
  "onboarding/telegramResolver": typeof onboarding_telegramResolver;
  onboarding: typeof onboarding;
  ontologyHelpers: typeof ontologyHelpers;
  ontologyTranslations: typeof ontologyTranslations;
  organizationApiSettings: typeof organizationApiSettings;
  organizationInvoiceSettings: typeof organizationInvoiceSettings;
  organizationMedia: typeof organizationMedia;
  organizationMutations: typeof organizationMutations;
  organizationOntology: typeof organizationOntology;
  organizationPaymentSettings: typeof organizationPaymentSettings;
  organizationTaxSettings: typeof organizationTaxSettings;
  organizations: typeof organizations;
  pageAnalytics: typeof pageAnalytics;
  pageBuilder: typeof pageBuilder;
  passkeys: typeof passkeys;
  paymentProviderOntology: typeof paymentProviderOntology;
  "paymentProviders/helpers": typeof paymentProviders_helpers;
  "paymentProviders/index": typeof paymentProviders_index;
  "paymentProviders/invoice": typeof paymentProviders_invoice;
  "paymentProviders/invoiceAvailability": typeof paymentProviders_invoiceAvailability;
  "paymentProviders/manager": typeof paymentProviders_manager;
  "paymentProviders/stripe": typeof paymentProviders_stripe;
  "paymentProviders/types": typeof paymentProviders_types;
  paymentRulesEngine: typeof paymentRulesEngine;
  "pdf/invoicePdf": typeof pdf_invoicePdf;
  "pdf/ticketPdf": typeof pdf_ticketPdf;
  pdfGeneration: typeof pdfGeneration;
  pdfGenerationTemplated: typeof pdfGenerationTemplated;
  pdfTemplateAvailability: typeof pdfTemplateAvailability;
  pdfTemplateQueries: typeof pdfTemplateQueries;
  pdfTemplateRegistry: typeof pdfTemplateRegistry;
  pdfTemplateResolver: typeof pdfTemplateResolver;
  pdfTemplates: typeof pdfTemplates;
  pdfTicketTemplateRenderer: typeof pdfTicketTemplateRenderer;
  permissionErrors: typeof permissionErrors;
  portalAuth: typeof portalAuth;
  portalInvitations: typeof portalInvitations;
  productOntology: typeof productOntology;
  projectAnalytics: typeof projectAnalytics;
  projectContent: typeof projectContent;
  projectDrawerAuth: typeof projectDrawerAuth;
  projectFileSystem: typeof projectFileSystem;
  projectFileSystemInternal: typeof projectFileSystemInternal;
  projectOntology: typeof projectOntology;
  projectSharing: typeof projectSharing;
  publishingFreelancerPortal: typeof publishingFreelancerPortal;
  publishingHelpers: typeof publishingHelpers;
  publishingOntology: typeof publishingOntology;
  purchaseOntology: typeof purchaseOntology;
  rbac: typeof rbac;
  rbacHelpers: typeof rbacHelpers;
  rbacQueries: typeof rbacQueries;
  registerAIAssistantApp: typeof registerAIAssistantApp;
  salesNotifications: typeof salesNotifications;
  "schema/shapes": typeof schema_shapes;
  "schemas/activityProtocolSchemas": typeof schemas_activityProtocolSchemas;
  "schemas/agentSessionSchemas": typeof schemas_agentSessionSchemas;
  "schemas/aiBillingSchemas": typeof schemas_aiBillingSchemas;
  "schemas/aiSchemas": typeof schemas_aiSchemas;
  "schemas/appDataSchemas": typeof schemas_appDataSchemas;
  "schemas/appSchemaBase": typeof schemas_appSchemaBase;
  "schemas/appStoreSchemas": typeof schemas_appStoreSchemas;
  "schemas/benefitsSchemas": typeof schemas_benefitsSchemas;
  "schemas/builderFileSchemas": typeof schemas_builderFileSchemas;
  "schemas/contactSyncSchemas": typeof schemas_contactSyncSchemas;
  "schemas/coreSchemas": typeof schemas_coreSchemas;
  "schemas/creditSchemas": typeof schemas_creditSchemas;
  "schemas/designPatternSchemas": typeof schemas_designPatternSchemas;
  "schemas/emailQueueSchemas": typeof schemas_emailQueueSchemas;
  "schemas/growthTrackingSchemas": typeof schemas_growthTrackingSchemas;
  "schemas/interviewSchemas": typeof schemas_interviewSchemas;
  "schemas/layerExecutionSchemas": typeof schemas_layerExecutionSchemas;
  "schemas/messageQueueSchema": typeof schemas_messageQueueSchema;
  "schemas/oauthSchemas": typeof schemas_oauthSchemas;
  "schemas/ontologySchemas": typeof schemas_ontologySchemas;
  "schemas/projectFileSchemas": typeof schemas_projectFileSchemas;
  "schemas/rateLimitSchemas": typeof schemas_rateLimitSchemas;
  "schemas/securitySchemas": typeof schemas_securitySchemas;
  "schemas/soulEvolutionSchemas": typeof schemas_soulEvolutionSchemas;
  "schemas/storageSchemas": typeof schemas_storageSchemas;
  "schemas/telegramSchemas": typeof schemas_telegramSchemas;
  "schemas/transactionStrictSchemas": typeof schemas_transactionStrictSchemas;
  "schemas/translationSchemas": typeof schemas_translationSchemas;
  "schemas/userQuotaSchemas": typeof schemas_userQuotaSchemas;
  "schemas/utilitySchemas": typeof schemas_utilitySchemas;
  "schemas/webchatSchemas": typeof schemas_webchatSchemas;
  "security/actions": typeof security_actions;
  "security/usageTracking": typeof security_usageTracking;
  "security/usageTrackingExample": typeof security_usageTrackingExample;
  "seed/seedSyntheticTraining": typeof seed_seedSyntheticTraining;
  "seed/syntheticTemplates": typeof seed_syntheticTemplates;
  seedAdmin: typeof seedAdmin;
  seedAllSchemaTemplates: typeof seedAllSchemaTemplates;
  seedApps: typeof seedApps;
  seedCheckoutApp: typeof seedCheckoutApp;
  seedCheckoutTemplates: typeof seedCheckoutTemplates;
  seedConsolidatedInvoiceWorkflow: typeof seedConsolidatedInvoiceWorkflow;
  seedEmailTemplates: typeof seedEmailTemplates;
  seedEventConfirmationTemplate: typeof seedEventConfirmationTemplate;
  seedFormTemplates: typeof seedFormTemplates;
  seedInvoiceB2BTemplate: typeof seedInvoiceB2BTemplate;
  seedInvoiceEmailTemplate: typeof seedInvoiceEmailTemplate;
  seedInvoiceEmailTemplateV2: typeof seedInvoiceEmailTemplateV2;
  seedNewsletterTemplate: typeof seedNewsletterTemplate;
  seedOntologyData: typeof seedOntologyData;
  seedPdfTemplates: typeof seedPdfTemplates;
  seedProjectDrawerTest: typeof seedProjectDrawerTest;
  seedSalesNotificationTemplate: typeof seedSalesNotificationTemplate;
  seedSystemDefaultTemplateSet: typeof seedSystemDefaultTemplateSet;
  seedSystemDomainConfig: typeof seedSystemDomainConfig;
  seedTemplateSet: typeof seedTemplateSet;
  seedTemplates: typeof seedTemplates;
  seedTicketPdfTemplate: typeof seedTicketPdfTemplate;
  seedTransactionReceiptTemplate: typeof seedTransactionReceiptTemplate;
  seedWorkflowTemplates: typeof seedWorkflowTemplates;
  "seeds/interviewTemplates": typeof seeds_interviewTemplates;
  "seeds/provisionTemplatesForExistingOrg": typeof seeds_provisionTemplatesForExistingOrg;
  "seeds/seedFreelancerPortalTemplate": typeof seeds_seedFreelancerPortalTemplate;
  "sequences/enrollmentOntology": typeof sequences_enrollmentOntology;
  "sequences/exitHandler": typeof sequences_exitHandler;
  "sequences/messageQueueProcessor": typeof sequences_messageQueueProcessor;
  "sequences/messageSender": typeof sequences_messageSender;
  "sequences/sequenceOntology": typeof sequences_sequenceOntology;
  "sequences/sequenceProcessor": typeof sequences_sequenceProcessor;
  "sequences/sequenceTriggers": typeof sequences_sequenceTriggers;
  "sequences/stepExecutor": typeof sequences_stepExecutor;
  "sequences/templateOntology": typeof sequences_templateOntology;
  "stripe/aiCheckout": typeof stripe_aiCheckout;
  "stripe/aiWebhooks": typeof stripe_aiWebhooks;
  "stripe/creditCheckout": typeof stripe_creditCheckout;
  "stripe/platformCheckout": typeof stripe_platformCheckout;
  "stripe/platformWebhooks": typeof stripe_platformWebhooks;
  "stripe/smsCheckout": typeof stripe_smsCheckout;
  "stripe/stripePrices": typeof stripe_stripePrices;
  "stripe/trialCheckout": typeof stripe_trialCheckout;
  "stripe/trialCron": typeof stripe_trialCron;
  "stripe/trialEmails": typeof stripe_trialEmails;
  "stripe/trialHelpers": typeof stripe_trialHelpers;
  stripeCheckout: typeof stripeCheckout;
  stripeConnect: typeof stripeConnect;
  stripeInvoices: typeof stripeInvoices;
  stripeRefunds: typeof stripeRefunds;
  stripeWebhooks: typeof stripeWebhooks;
  templateAvailability: typeof templateAvailability;
  templateOntology: typeof templateOntology;
  templateSetAvailability: typeof templateSetAvailability;
  templateSetOntology: typeof templateSetOntology;
  templateSetQueries: typeof templateSetQueries;
  templateSetResolver: typeof templateSetResolver;
  templateUsageStats: typeof templateUsageStats;
  "terminal/terminalFeed": typeof terminal_terminalFeed;
  testEmailTemplates: typeof testEmailTemplates;
  testHelpers: typeof testHelpers;
  testInspectTemplate: typeof testInspectTemplate;
  ticketEmailService: typeof ticketEmailService;
  ticketGeneration: typeof ticketGeneration;
  ticketOntology: typeof ticketOntology;
  transactionCorrections: typeof transactionCorrections;
  transactionHelpers: typeof transactionHelpers;
  transactionInvoicing: typeof transactionInvoicing;
  transactionOntology: typeof transactionOntology;
  transactionOntologyStrict: typeof transactionOntologyStrict;
  translationResolver: typeof translationResolver;
  "translations/_translationHelpers": typeof translations__translationHelpers;
  "translations/seedAIAssistant": typeof translations_seedAIAssistant;
  "translations/seedAddressTranslations": typeof translations_seedAddressTranslations;
  "translations/seedBenefitsWindowTranslations": typeof translations_seedBenefitsWindowTranslations;
  "translations/seedCRM_01_OrganizationForm": typeof translations_seedCRM_01_OrganizationForm;
  "translations/seedCRM_02_MainWindow": typeof translations_seedCRM_02_MainWindow;
  "translations/seedCRM_03_ContactForm": typeof translations_seedCRM_03_ContactForm;
  "translations/seedCRM_04_Pipeline": typeof translations_seedCRM_04_Pipeline;
  "translations/seedCRM_05_SystemPipelineTemplate": typeof translations_seedCRM_05_SystemPipelineTemplate;
  "translations/seedCRM_06_NotificationsAndPipelines": typeof translations_seedCRM_06_NotificationsAndPipelines;
  "translations/seedCertificatesTranslations": typeof translations_seedCertificatesTranslations;
  "translations/seedCheckoutFailed": typeof translations_seedCheckoutFailed;
  "translations/seedCheckoutSuccess": typeof translations_seedCheckoutSuccess;
  "translations/seedCheckoutTemplate_00_Main": typeof translations_seedCheckoutTemplate_00_Main;
  "translations/seedCheckoutTemplate_00_Progress": typeof translations_seedCheckoutTemplate_00_Progress;
  "translations/seedCheckoutTemplate_01_ProductSelection": typeof translations_seedCheckoutTemplate_01_ProductSelection;
  "translations/seedCheckoutTemplate_02_RegistrationForm": typeof translations_seedCheckoutTemplate_02_RegistrationForm;
  "translations/seedCheckoutTemplate_03_CustomerInfo": typeof translations_seedCheckoutTemplate_03_CustomerInfo;
  "translations/seedCheckoutTemplate_04_ReviewOrder": typeof translations_seedCheckoutTemplate_04_ReviewOrder;
  "translations/seedCheckoutTemplate_05_Payment": typeof translations_seedCheckoutTemplate_05_Payment;
  "translations/seedCheckoutTemplate_05a_PaymentMethods": typeof translations_seedCheckoutTemplate_05a_PaymentMethods;
  "translations/seedCheckoutTemplate_05b_PaymentForm": typeof translations_seedCheckoutTemplate_05b_PaymentForm;
  "translations/seedCheckoutTemplate_06_Confirmation": typeof translations_seedCheckoutTemplate_06_Confirmation;
  "translations/seedCheckoutTemplate_06a_ConfirmationSuccess": typeof translations_seedCheckoutTemplate_06a_ConfirmationSuccess;
  "translations/seedCheckoutTemplate_06b_ConfirmationInvoice": typeof translations_seedCheckoutTemplate_06b_ConfirmationInvoice;
  "translations/seedCheckoutWindow": typeof translations_seedCheckoutWindow;
  "translations/seedCheckout_01_CustomerInfo": typeof translations_seedCheckout_01_CustomerInfo;
  "translations/seedCheckout_01a_BasicInfo": typeof translations_seedCheckout_01a_BasicInfo;
  "translations/seedCheckout_01b_Errors": typeof translations_seedCheckout_01b_Errors;
  "translations/seedCheckout_01c_B2BFields": typeof translations_seedCheckout_01c_B2BFields;
  "translations/seedCheckout_02_PaymentForm": typeof translations_seedCheckout_02_PaymentForm;
  "translations/seedCheckout_03_Confirmation": typeof translations_seedCheckout_03_Confirmation;
  "translations/seedCheckout_04_InvoiceEnforcement": typeof translations_seedCheckout_04_InvoiceEnforcement;
  "translations/seedCheckout_05_RegistrationForm": typeof translations_seedCheckout_05_RegistrationForm;
  "translations/seedCommonMonths": typeof translations_seedCommonMonths;
  "translations/seedCompliance": typeof translations_seedCompliance;
  "translations/seedContactModal": typeof translations_seedContactModal;
  "translations/seedControlPanel": typeof translations_seedControlPanel;
  "translations/seedDesktop": typeof translations_seedDesktop;
  "translations/seedEmailTemplates": typeof translations_seedEmailTemplates;
  "translations/seedEventLanding_00_Main": typeof translations_seedEventLanding_00_Main;
  "translations/seedEventLanding_01_Navigation": typeof translations_seedEventLanding_01_Navigation;
  "translations/seedEventLanding_02_HeroAndVenue": typeof translations_seedEventLanding_02_HeroAndVenue;
  "translations/seedEventLanding_03_Checkout": typeof translations_seedEventLanding_03_Checkout;
  "translations/seedEventLanding_04_AgendaAndDates": typeof translations_seedEventLanding_04_AgendaAndDates;
  "translations/seedEventLanding_05_Format": typeof translations_seedEventLanding_05_Format;
  "translations/seedEventsTranslations": typeof translations_seedEventsTranslations;
  "translations/seedEvents_00_Main": typeof translations_seedEvents_00_Main;
  "translations/seedEvents_01_FormBasics": typeof translations_seedEvents_01_FormBasics;
  "translations/seedEvents_02_FormMedia": typeof translations_seedEvents_02_FormMedia;
  "translations/seedEvents_03_FormAgenda": typeof translations_seedEvents_03_FormAgenda;
  "translations/seedEvents_04_FormSponsors": typeof translations_seedEvents_04_FormSponsors;
  "translations/seedEvents_05_FormDescription": typeof translations_seedEvents_05_FormDescription;
  "translations/seedEvents_06_DetailModal": typeof translations_seedEvents_06_DetailModal;
  "translations/seedFormsResponses_DE": typeof translations_seedFormsResponses_DE;
  "translations/seedFormsResponses_EN": typeof translations_seedFormsResponses_EN;
  "translations/seedFormsResponses_ES": typeof translations_seedFormsResponses_ES;
  "translations/seedFormsResponses_FR": typeof translations_seedFormsResponses_FR;
  "translations/seedFormsResponses_JA": typeof translations_seedFormsResponses_JA;
  "translations/seedFormsResponses_PL": typeof translations_seedFormsResponses_PL;
  "translations/seedFormsWindowTranslations": typeof translations_seedFormsWindowTranslations;
  "translations/seedIntegrationsWindow": typeof translations_seedIntegrationsWindow;
  "translations/seedInvoicingTranslations": typeof translations_seedInvoicingTranslations;
  "translations/seedInvoicingWindow_Templates": typeof translations_seedInvoicingWindow_Templates;
  "translations/seedLogin": typeof translations_seedLogin;
  "translations/seedLogin_01_BasicAuth": typeof translations_seedLogin_01_BasicAuth;
  "translations/seedLogin_02_Forms": typeof translations_seedLogin_02_Forms;
  "translations/seedLogin_03_Buttons": typeof translations_seedLogin_03_Buttons;
  "translations/seedLogin_03a_Buttons": typeof translations_seedLogin_03a_Buttons;
  "translations/seedLogin_03b_Errors": typeof translations_seedLogin_03b_Errors;
  "translations/seedLogin_04_Passkeys": typeof translations_seedLogin_04_Passkeys;
  "translations/seedManage_01_MainWindow": typeof translations_seedManage_01_MainWindow;
  "translations/seedManage_02_Organization": typeof translations_seedManage_02_Organization;
  "translations/seedManage_03_Users": typeof translations_seedManage_03_Users;
  "translations/seedManage_03b_DeleteAccount": typeof translations_seedManage_03b_DeleteAccount;
  "translations/seedManage_04_RolesPermissions": typeof translations_seedManage_04_RolesPermissions;
  "translations/seedManage_05_Security": typeof translations_seedManage_05_Security;
  "translations/seedManage_06_DomainConfig": typeof translations_seedManage_06_DomainConfig;
  "translations/seedManage_07_Integrations": typeof translations_seedManage_07_Integrations;
  "translations/seedManage_08_AISettings": typeof translations_seedManage_08_AISettings;
  "translations/seedMediaLibrary": typeof translations_seedMediaLibrary;
  "translations/seedNotifications": typeof translations_seedNotifications;
  "translations/seedOrganizations": typeof translations_seedOrganizations;
  "translations/seedPaymentTranslations": typeof translations_seedPaymentTranslations;
  "translations/seedPdfTemplates": typeof translations_seedPdfTemplates;
  "translations/seedProcessingModal": typeof translations_seedProcessingModal;
  "translations/seedProductTranslations": typeof translations_seedProductTranslations;
  "translations/seedProductTranslations_es": typeof translations_seedProductTranslations_es;
  "translations/seedProductTranslations_fr": typeof translations_seedProductTranslations_fr;
  "translations/seedProductTranslations_ja": typeof translations_seedProductTranslations_ja;
  "translations/seedProductTranslations_pl": typeof translations_seedProductTranslations_pl;
  "translations/seedProfileTranslations": typeof translations_seedProfileTranslations;
  "translations/seedSettings": typeof translations_seedSettings;
  "translations/seedShoppingCart": typeof translations_seedShoppingCart;
  "translations/seedStartMenu": typeof translations_seedStartMenu;
  "translations/seedStore": typeof translations_seedStore;
  "translations/seedStoreButtons": typeof translations_seedStoreButtons;
  "translations/seedTemplatesTranslations": typeof translations_seedTemplatesTranslations;
  "translations/seedTemplatesWindowTranslations": typeof translations_seedTemplatesWindowTranslations;
  "translations/seedTicketsTranslations": typeof translations_seedTicketsTranslations;
  "translations/seedWebPublishing": typeof translations_seedWebPublishing;
  "translations/seedWelcomeTranslations": typeof translations_seedWelcomeTranslations;
  "translations/seedWindowTitles": typeof translations_seedWindowTitles;
  "translations/seedWorkflowsTranslations": typeof translations_seedWorkflowsTranslations;
  "translations/updateBranding": typeof translations_updateBranding;
  tutorialOntology: typeof tutorialOntology;
  "types/ontology": typeof types_ontology;
  userPreferences: typeof userPreferences;
  vatValidation: typeof vatValidation;
  venueOntology: typeof venueOntology;
  webinarOntology: typeof webinarOntology;
  webinarRegistrants: typeof webinarRegistrants;
  workflowExecutionLogs: typeof workflowExecutionLogs;
  workflowTemplateAvailability: typeof workflowTemplateAvailability;
  "workflows/behaviorExecutor": typeof workflows_behaviorExecutor;
  "workflows/behaviors/activeCampaignSync": typeof workflows_behaviors_activeCampaignSync;
  "workflows/behaviors/calculatePricing": typeof workflows_behaviors_calculatePricing;
  "workflows/behaviors/checkEventCapacity": typeof workflows_behaviors_checkEventCapacity;
  "workflows/behaviors/consolidatedInvoiceGeneration": typeof workflows_behaviors_consolidatedInvoiceGeneration;
  "workflows/behaviors/createContact": typeof workflows_behaviors_createContact;
  "workflows/behaviors/createFormResponse": typeof workflows_behaviors_createFormResponse;
  "workflows/behaviors/createTicket": typeof workflows_behaviors_createTicket;
  "workflows/behaviors/createTransaction": typeof workflows_behaviors_createTransaction;
  "workflows/behaviors/detectEmployerBilling": typeof workflows_behaviors_detectEmployerBilling;
  "workflows/behaviors/generateInvoice": typeof workflows_behaviors_generateInvoice;
  "workflows/behaviors/sendAdminNotification": typeof workflows_behaviors_sendAdminNotification;
  "workflows/behaviors/sendConfirmationEmail": typeof workflows_behaviors_sendConfirmationEmail;
  "workflows/behaviors/updateStatistics": typeof workflows_behaviors_updateStatistics;
  "workflows/behaviors/validateRegistration": typeof workflows_behaviors_validateRegistration;
  "workflows/workflowExecution": typeof workflows_workflowExecution;
  "workflows/workflowOntology": typeof workflows_workflowOntology;
  "workflows/workflowTemplates": typeof workflows_workflowTemplates;
  "workflows/workflowTestExecution": typeof workflows_workflowTestExecution;
  "workflows/workflowValidation": typeof workflows_workflowValidation;
  "zapier/triggers": typeof zapier_triggers;
  "zapier/webhooks": typeof zapier_webhooks;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
