import { afterEach, describe, expect, it, vi } from "vitest";
import {
  extractCaptionSegmentsFromJson3,
  extractYouTubeVideoId,
  parseAudioStreamCandidatesFromPlayerResponse,
  parseAudioStreamsFromPlayerResponse,
  parseCaptionTracksXml,
  transcribeYoutubeVideoTool,
} from "../../../convex/ai/tools/youtubeTranscribeTool";

function jsonResponse(
  payload: unknown,
  init: { status?: number; headers?: Record<string, string> } = {}
): Response {
  return new Response(JSON.stringify(payload), {
    status: init.status ?? 200,
    headers: {
      "content-type": "application/json",
      ...init.headers,
    },
  });
}

function textResponse(
  body: string,
  init: { status?: number; headers?: Record<string, string> } = {}
): Response {
  return new Response(body, {
    status: init.status ?? 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      ...init.headers,
    },
  });
}

function buildWatchHtml(playerResponse: unknown): string {
  return `<html><head><title>Sample video - YouTube</title></head><body><script>var ytInitialPlayerResponse = ${JSON.stringify(playerResponse)};</script></body></html>`;
}

describe("youtube transcript tool helpers", () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
  });

  it("extracts video IDs from common YouTube URL formats", () => {
    expect(
      extractYouTubeVideoId("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    ).toBe("dQw4w9WgXcQ");
    expect(
      extractYouTubeVideoId("https://youtu.be/dQw4w9WgXcQ?t=10")
    ).toBe("dQw4w9WgXcQ");
    expect(
      extractYouTubeVideoId("https://www.youtube.com/shorts/dQw4w9WgXcQ")
    ).toBe("dQw4w9WgXcQ");
    expect(extractYouTubeVideoId("dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");
  });

  it("returns null for invalid YouTube URLs", () => {
    expect(extractYouTubeVideoId("https://example.com/video")).toBeNull();
    expect(extractYouTubeVideoId("https://youtube.com/watch?v=bad-id")).toBeNull();
  });

  it("parses timedtext XML tracks and detects auto-generated captions", () => {
    const xml = `<transcript_list>
      <track id="0" name="English" lang_code="en" vss_id=".en" />
      <track id="1" name="Auto &amp; generated" lang_code="de" vss_id="a.de" kind="asr" />
    </transcript_list>`;

    const tracks = parseCaptionTracksXml(xml);
    expect(tracks).toHaveLength(2);
    expect(tracks[0]).toMatchObject({
      languageCode: "en",
      name: "English",
      isAutoGenerated: false,
    });
    expect(tracks[1]).toMatchObject({
      languageCode: "de",
      name: "Auto & generated",
      isAutoGenerated: true,
      kind: "asr",
    });
  });

  it("extracts normalized transcript segments from json3 payload", () => {
    const segments = extractCaptionSegmentsFromJson3({
      events: [
        {
          tStartMs: 1200,
          dDurationMs: 800,
          segs: [{ utf8: "Hello\n" }, { utf8: "world" }],
        },
        {
          tStartMs: 2200,
          dDurationMs: 700,
          segs: [{ utf8: "How are you?" }],
        },
      ],
    });

    expect(segments).toEqual([
      { startMs: 1200, durationMs: 800, text: "Hello world" },
      { startMs: 2200, durationMs: 700, text: "How are you?" },
    ]);
  });

  it("extracts playable audio streams from player response metadata", () => {
    const streams = parseAudioStreamsFromPlayerResponse({
      streamingData: {
        adaptiveFormats: [
          {
            itag: 140,
            mimeType: 'audio/mp4; codecs="mp4a.40.2"',
            bitrate: 128000,
            url: "https://example.com/audio-direct.m4a",
          },
          {
            itag: 251,
            mimeType: 'audio/webm; codecs="opus"',
            bitrate: 160000,
            signatureCipher:
              "url=https%3A%2F%2Fexample.com%2Faudio-cipher.webm&sp=sig&sig=abc123",
          },
          {
            itag: 250,
            mimeType: 'audio/webm; codecs="opus"',
            bitrate: 70000,
            signatureCipher:
              "url=https%3A%2F%2Fexample.com%2Faudio-encrypted.webm&sp=sig&s=ENCRYPTED",
          },
        ],
      },
    });

    expect(streams).toHaveLength(2);
    expect(streams[0].url).toContain("audio-cipher.webm");
    expect(streams[0].url).toContain("sig=abc123");
    expect(streams[1]).toMatchObject({
      url: "https://example.com/audio-direct.m4a",
      itag: 140,
      fromSignatureCipher: false,
    });
  });

  it("tracks encrypted signatureCipher streams separately for deterministic fallback handling", () => {
    const parsed = parseAudioStreamCandidatesFromPlayerResponse({
      streamingData: {
        adaptiveFormats: [
          {
            itag: 250,
            mimeType: 'audio/webm; codecs="opus"',
            bitrate: 70000,
            signatureCipher:
              "url=https%3A%2F%2Fexample.com%2Faudio-encrypted.webm&sp=sig&s=ENCRYPTED",
          },
        ],
      },
    });

    expect(parsed.playableStreams).toHaveLength(0);
    expect(parsed.encryptedSignatureStreams).toHaveLength(1);
    expect(parsed.encryptedSignatureStreams[0]).toMatchObject({
      baseUrl: "https://example.com/audio-encrypted.webm",
      signatureParamName: "sig",
      encryptedSignature: "ENCRYPTED",
      itag: 250,
    });
  });
});

describe("transcribeYoutubeVideoTool execute", () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
  });

  it("returns caption transcript in captions mode", async () => {
    const playerResponse = {
      videoDetails: { title: "Caption video" },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              languageCode: "en",
              kind: "asr",
              baseUrl: "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en",
            },
          ],
        },
      },
    };

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url.includes("/api/timedtext?v=dQw4w9WgXcQ&lang=en")) {
        return jsonResponse({
          events: [
            { tStartMs: 0, dDurationMs: 1200, segs: [{ utf8: "Hello from captions" }] },
          ],
        });
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({} as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "captions",
      includeTimestamps: true,
    }) as Record<string, unknown>;

    expect(result.success).toBe(true);
    expect(result.sourceUsed).toBe("captions");
    expect(result.transcript).toBe("Hello from captions");
    expect(Array.isArray(result.segments)).toBe(true);
  });

  it("saves caption transcript to user files when requested", async () => {
    const playerResponse = {
      videoDetails: { title: "Caption video" },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              languageCode: "en",
              kind: "asr",
              baseUrl: "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en",
            },
          ],
        },
      },
    };
    const runMutation = vi.fn().mockResolvedValue({
      fileId: "pf_yt_1",
      path: "/yt-caption-transcript.md",
      parentPath: "/",
      name: "yt-caption-transcript.md",
      overwritten: false,
    });

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url.includes("/api/timedtext?v=dQw4w9WgXcQ&lang=en")) {
        return jsonResponse({
          events: [
            { tStartMs: 0, dDurationMs: 1200, segs: [{ utf8: "Saved captions text" }] },
          ],
        });
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({
      runMutation,
      organizationId: "org_1",
      userId: "user_1",
    } as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "captions",
      saveToUserFiles: true,
      saveFileName: "yt-caption-transcript.md",
    }) as Record<string, unknown>;

    expect(result.success).toBe(true);
    expect(result.sourceUsed).toBe("captions");
    expect((result.transcriptFile as Record<string, unknown>).saved).toBe(true);
    expect((result.transcriptFile as Record<string, unknown>).path).toBe(
      "/yt-caption-transcript.md"
    );
    expect(runMutation).toHaveBeenCalledTimes(1);
  });

  it("does not save transcript files in read-only sandbox autonomy mode", async () => {
    const playerResponse = {
      videoDetails: { title: "Caption video" },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              languageCode: "en",
              kind: "asr",
              baseUrl: "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en",
            },
          ],
        },
      },
    };
    const runMutation = vi.fn();

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url.includes("/api/timedtext?v=dQw4w9WgXcQ&lang=en")) {
        return jsonResponse({
          events: [
            { tStartMs: 0, dDurationMs: 1200, segs: [{ utf8: "Read-only captions text" }] },
          ],
        });
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({
      runMutation,
      organizationId: "org_1",
      userId: "user_1",
      runtimePolicy: {
        codeExecution: {
          autonomyLevel: "sandbox",
        },
      },
    } as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "captions",
      saveToUserFiles: true,
      saveFileName: "yt-caption-transcript.md",
    }) as Record<string, unknown>;

    expect(result.success).toBe(true);
    const transcriptFile = result.transcriptFile as Record<string, unknown>;
    expect(transcriptFile.saved).toBe(false);
    expect(String(transcriptFile.error)).toContain("read-only autonomy mode");
    expect(runMutation).not.toHaveBeenCalled();
  });

  it("uses audio mode and bypasses caption lookup", async () => {
    vi.stubEnv("OPENAI_API_KEY", "test-openai-key");

    const playerResponse = {
      videoDetails: { title: "Audio mode video" },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            {
              languageCode: "en",
              baseUrl: "https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en",
            },
          ],
        },
      },
      streamingData: {
        adaptiveFormats: [
          {
            itag: 140,
            mimeType: 'audio/mp4; codecs="mp4a.40.2"',
            bitrate: 128000,
            url: "https://media.example/audio-direct.m4a",
          },
        ],
      },
    };

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url === "https://media.example/audio-direct.m4a") {
        return new Response(new Uint8Array([1, 2, 3, 4, 5]), {
          status: 200,
          headers: {
            "content-type": "audio/mp4",
            "content-length": "5",
          },
        });
      }
      if (url === "https://api.openai.com/v1/audio/transcriptions") {
        return jsonResponse({
          text: "Audio mode transcript",
          language: "en",
          duration: 2.5,
          segments: [{ start: 0, end: 1.5, text: "Audio mode transcript" }],
        });
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({} as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "audio",
    }) as Record<string, unknown>;

    expect(result.success).toBe(true);
    expect(result.sourceUsed).toBe("audio");
    expect(result.transcript).toBe("Audio mode transcript");
  });

  it("falls back to audio in auto mode when captions are unavailable", async () => {
    vi.stubEnv("OPENAI_API_KEY", "test-openai-key");

    const playerResponse = {
      videoDetails: { title: "Fallback video" },
      streamingData: {
        adaptiveFormats: [
          {
            itag: 140,
            mimeType: 'audio/mp4; codecs="mp4a.40.2"',
            bitrate: 128000,
            url: "https://media.example/fallback-audio.m4a",
          },
        ],
      },
    };

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url.includes("/api/timedtext?type=list&v=dQw4w9WgXcQ")) {
        return textResponse("<transcript_list></transcript_list>");
      }
      if (url === "https://media.example/fallback-audio.m4a") {
        return new Response(new Uint8Array([1, 2, 3, 4, 5]), {
          status: 200,
          headers: {
            "content-type": "audio/mp4",
            "content-length": "5",
          },
        });
      }
      if (url === "https://api.openai.com/v1/audio/transcriptions") {
        return jsonResponse({
          text: "Auto mode fallback transcript",
          language: "en",
          duration: 4.1,
          segments: [{ start: 0, end: 1.2, text: "Auto mode fallback transcript" }],
        });
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({} as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "auto",
    }) as Record<string, unknown>;

    expect(result.success).toBe(true);
    expect(result.sourceUsed).toBe("audio");
    expect(result.transcript).toBe("Auto mode fallback transcript");
    expect(String(result.fallbackNote)).toContain("No transcript/captions were found");
  });

  it("returns deterministic encrypted signatureCipher failure when only s= streams are present", async () => {
    const playerResponse = {
      videoDetails: { title: "Encrypted stream video" },
      streamingData: {
        adaptiveFormats: [
          {
            itag: 251,
            mimeType: 'audio/webm; codecs="opus"',
            bitrate: 160000,
            signatureCipher:
              "url=https%3A%2F%2Fmedia.example%2Fencrypted.webm&sp=sig&s=ENCRYPTED_PAYLOAD",
          },
        ],
      },
    };

    const fetchSpy = vi.fn(async (input: RequestInfo | URL) => {
      const url = String(input);
      if (url.includes("/watch?v=dQw4w9WgXcQ")) {
        return textResponse(buildWatchHtml(playerResponse), {
          headers: { "content-type": "text/html" },
        });
      }
      if (url.includes("/api/timedtext?type=list&v=dQw4w9WgXcQ")) {
        return textResponse("<transcript_list></transcript_list>");
      }
      throw new Error(`Unexpected fetch URL: ${url}`);
    });
    vi.stubGlobal("fetch", fetchSpy);

    const result = await transcribeYoutubeVideoTool.execute({} as any, {
      videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      source: "audio",
    }) as Record<string, unknown>;

    expect(result.success).toBe(false);
    expect(result.error).toBe("YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED");
    expect(String(result.message)).toContain("signatureCipher s=");
    expect(result.encryptedSignatureStreamCount).toBe(1);
    expect(Array.isArray(result.actionableFallbacks)).toBe(true);
  });
});
