import type { AITool, ToolExecutionContext } from "./registry";
import { transcribeMediaAudio } from "./shared/transcribeMediaAudio";
import { saveTranscriptToUserFiles } from "./shared/saveTranscriptToUserFiles";

interface CaptionTrack {
  languageCode: string;
  name: string;
  kind?: string;
  isAutoGenerated: boolean;
  baseUrl?: string;
}

interface CaptionSegment {
  startMs: number;
  durationMs: number;
  text: string;
}

interface AudioStreamCandidate {
  url: string;
  mimeType?: string;
  bitrate?: number;
  contentLengthBytes?: number;
  itag?: number;
  fromSignatureCipher: boolean;
}

interface EncryptedSignatureAudioStreamCandidate {
  baseUrl: string;
  signatureParamName: string;
  encryptedSignature: string;
  mimeType?: string;
  bitrate?: number;
  contentLengthBytes?: number;
  itag?: number;
}

interface AudioStreamParseResult {
  playableStreams: AudioStreamCandidate[];
  encryptedSignatureStreams: EncryptedSignatureAudioStreamCandidate[];
}

interface VideoMetadata {
  title?: string;
  tracks: CaptionTrack[];
  audioStreams: AudioStreamCandidate[];
  encryptedSignatureStreams: EncryptedSignatureAudioStreamCandidate[];
}

type CaptionSelection = {
  track: CaptionTrack;
  fallbackReason?: string;
};

type TranscriptSource = "captions" | "audio" | "auto";
type YouTubeSignatureDecipherStrategyId = "none" | "external_service" | "yt_dlp";

interface SignatureCipherDecipherConfig {
  strategy: YouTubeSignatureDecipherStrategyId;
  enabled: boolean;
  externalServiceUrl?: string;
  ytDlpCommand?: string;
}

interface SignatureCipherDecipherRequest {
  videoId: string;
  stream: EncryptedSignatureAudioStreamCandidate;
}

interface SignatureCipherDecipherResult {
  resolvedUrl: string;
}

interface SignatureCipherDecipherStrategy {
  id: YouTubeSignatureDecipherStrategyId;
  enabled: boolean;
  description: string;
  decipher?: (
    request: SignatureCipherDecipherRequest
  ) => Promise<SignatureCipherDecipherResult | null>;
}

type AudioSignatureCipherExtractionResult =
  | {
      type: "resolved";
      url: string;
      fromSignatureCipher: true;
    }
  | {
      type: "encrypted_signature";
      baseUrl: string;
      signatureParamName: string;
      encryptedSignature: string;
    };

const YOUTUBE_VIDEO_ID_PATTERN = /^[a-zA-Z0-9_-]{11}$/;

function normalizeOptionalString(value: unknown): string | null {
  if (typeof value !== "string") {
    return null;
  }
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

function toFiniteNumber(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }
  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
  }
  return undefined;
}

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (match, code) => {
      const numeric = Number(code);
      return Number.isFinite(numeric) ? String.fromCharCode(numeric) : match;
    });
}

function normalizeCaptionText(value: string): string {
  return value
    .replace(/\r/g, " ")
    .replace(/\n/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function getUrlPathSegment(pathname: string, index: number): string | null {
  const segments = pathname
    .split("/")
    .map((segment) => segment.trim())
    .filter((segment) => segment.length > 0);
  if (index < 0 || index >= segments.length) {
    return null;
  }
  return segments[index];
}

function normalizeTranscriptSource(value: unknown): TranscriptSource {
  const normalized = normalizeOptionalString(value)?.toLowerCase();
  if (normalized === "captions" || normalized === "audio") {
    return normalized;
  }
  return "auto";
}

function normalizeBooleanEnvFlag(value: string | undefined): boolean {
  if (!value) {
    return false;
  }
  const normalized = value.trim().toLowerCase();
  return normalized === "1" || normalized === "true" || normalized === "yes";
}

function normalizeSignatureDecipherStrategy(
  value: string | undefined
): YouTubeSignatureDecipherStrategyId {
  const normalized = normalizeOptionalString(value)?.toLowerCase();
  if (
    normalized === "none"
    || normalized === "external_service"
    || normalized === "yt_dlp"
  ) {
    return normalized;
  }
  return "none";
}

function resolveSignatureCipherDecipherConfigFromEnv(): SignatureCipherDecipherConfig {
  const strategy = normalizeSignatureDecipherStrategy(
    process.env.YOUTUBE_SIGNATURE_DECIPHER_STRATEGY
  );
  const enabled = normalizeBooleanEnvFlag(
    process.env.YOUTUBE_SIGNATURE_DECIPHER_ENABLED
  );

  return {
    strategy,
    enabled: enabled && strategy !== "none",
    externalServiceUrl:
      normalizeOptionalString(process.env.YOUTUBE_SIGNATURE_DECIPHER_EXTERNAL_URL)
      || undefined,
    ytDlpCommand:
      normalizeOptionalString(process.env.YOUTUBE_SIGNATURE_DECIPHER_YT_DLP_COMMAND)
      || undefined,
  };
}

function createSignatureCipherDecipherStrategy(
  config: SignatureCipherDecipherConfig
): SignatureCipherDecipherStrategy {
  if (config.strategy === "external_service") {
    return {
      id: "external_service",
      enabled: config.enabled && Boolean(config.externalServiceUrl),
      description: config.externalServiceUrl
        ? "External signatureCipher decoder service (hook pending implementation)."
        : "External signatureCipher decoder selected but YOUTUBE_SIGNATURE_DECIPHER_EXTERNAL_URL is missing.",
    };
  }

  if (config.strategy === "yt_dlp") {
    return {
      id: "yt_dlp",
      enabled: config.enabled && Boolean(config.ytDlpCommand),
      description: config.ytDlpCommand
        ? "Local yt-dlp adapter selected (hook pending implementation)."
        : "yt-dlp decipher selected but YOUTUBE_SIGNATURE_DECIPHER_YT_DLP_COMMAND is missing.",
    };
  }

  return {
    id: "none",
    enabled: false,
    description:
      "No YouTube signatureCipher decipher strategy configured; encrypted s= streams are unsupported.",
  };
}

function maybeDecodeUriComponent(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

function appendSignatureParam(url: string, key: string, value: string): string {
  try {
    const parsed = new URL(url);
    parsed.searchParams.set(key, value);
    return parsed.toString();
  } catch {
    const separator = url.includes("?") ? "&" : "?";
    return `${url}${separator}${encodeURIComponent(key)}=${encodeURIComponent(value)}`;
  }
}

function extractAudioUrlFromCipherString(
  cipherString: string
): AudioSignatureCipherExtractionResult | null {
  const params = new URLSearchParams(cipherString);
  const encodedUrl = normalizeOptionalString(params.get("url"));
  if (!encodedUrl) {
    return null;
  }

  const baseUrl = maybeDecodeUriComponent(encodedUrl);
  const signatureParamName = normalizeOptionalString(params.get("sp")) || "signature";
  const directSignature = normalizeOptionalString(params.get("sig"));
  const encryptedSignature = normalizeOptionalString(params.get("s"));

  if (directSignature) {
    return {
      type: "resolved",
      url: appendSignatureParam(baseUrl, signatureParamName, directSignature),
      fromSignatureCipher: true,
    };
  }

  if (encryptedSignature) {
    return {
      type: "encrypted_signature",
      baseUrl,
      signatureParamName,
      encryptedSignature,
    };
  }

  return {
    type: "resolved",
    url: baseUrl,
    fromSignatureCipher: true,
  };
}

function audioContainerPreference(mimeType?: string): number {
  const normalized = (mimeType || "").toLowerCase();
  if (normalized.includes("audio/mp4") || normalized.includes("mp4a")) {
    return 3;
  }
  if (normalized.includes("audio/mpeg") || normalized.includes("audio/mp3")) {
    return 2;
  }
  if (normalized.includes("audio/webm") || normalized.includes("opus")) {
    return 1;
  }
  return 0;
}

function sortAudioStreamsByQuality<
  T extends { bitrate?: number; mimeType?: string; contentLengthBytes?: number }
>(streams: T[]): T[] {
  return [...streams].sort((left, right) => {
    const bitrateDiff = (right.bitrate || 0) - (left.bitrate || 0);
    if (bitrateDiff !== 0) {
      return bitrateDiff;
    }
    const preferenceDiff =
      audioContainerPreference(right.mimeType) - audioContainerPreference(left.mimeType);
    if (preferenceDiff !== 0) {
      return preferenceDiff;
    }
    return (right.contentLengthBytes || 0) - (left.contentLengthBytes || 0);
  });
}

function selectBestAudioStream(streams: AudioStreamCandidate[]): AudioStreamCandidate | null {
  if (streams.length === 0) {
    return null;
  }
  return sortAudioStreamsByQuality(streams)[0];
}

function buildEncryptedSignatureDecipherFailure(args: {
  strategy: SignatureCipherDecipherStrategy;
  encryptedStreamCount: number;
  errorCode: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED" | "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_FAILED";
  errorDetail?: string;
}): {
  success: false;
  code: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED" | "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_FAILED";
  message: string;
  actionableFallbacks: string[];
  decipherStrategy: YouTubeSignatureDecipherStrategyId;
  decipherEnabled: boolean;
} {
  const strategyStatus = args.strategy.enabled
    ? `Configured strategy '${args.strategy.id}' did not resolve the stream.`
    : `Decipher strategy '${args.strategy.id}' is not enabled in this runtime.`;
  const detail = args.errorDetail ? ` Details: ${args.errorDetail}` : "";

  return {
    success: false,
    code: args.errorCode,
    message:
      `Only encrypted YouTube audio streams were available (${args.encryptedStreamCount} candidate(s) with signatureCipher s=...). `
      + `${strategyStatus}${detail} This runtime cannot decode encrypted YouTube signatures without an explicit decipher integration.`,
    actionableFallbacks: [
      "Use source='captions' when captions are available.",
      "Ask the user to upload/share a direct audio file URL instead of a YouTube link.",
      "Enable a decipher-capable strategy behind feature flags (external decoder service or local yt-dlp adapter).",
    ],
    decipherStrategy: args.strategy.id,
    decipherEnabled: args.strategy.enabled,
  };
}

async function resolveEncryptedSignatureAudioStream(args: {
  videoId: string;
  streams: EncryptedSignatureAudioStreamCandidate[];
  strategy: SignatureCipherDecipherStrategy;
}): Promise<
  | {
      success: true;
      stream: AudioStreamCandidate;
      decipherStrategy: YouTubeSignatureDecipherStrategyId;
    }
  | {
      success: false;
      code: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED" | "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_FAILED";
      message: string;
      actionableFallbacks: string[];
      decipherStrategy: YouTubeSignatureDecipherStrategyId;
      decipherEnabled: boolean;
    }
> {
  if (args.streams.length === 0) {
    return buildEncryptedSignatureDecipherFailure({
      strategy: args.strategy,
      encryptedStreamCount: 0,
      errorCode: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED",
    });
  }

  if (!args.strategy.enabled || !args.strategy.decipher) {
    return buildEncryptedSignatureDecipherFailure({
      strategy: args.strategy,
      encryptedStreamCount: args.streams.length,
      errorCode: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_REQUIRED",
    });
  }

  let lastError: string | undefined;
  const sortedStreams = sortAudioStreamsByQuality(args.streams);
  for (const stream of sortedStreams) {
    try {
      const result = await args.strategy.decipher({
        videoId: args.videoId,
        stream,
      });
      if (result?.resolvedUrl) {
        return {
          success: true,
          stream: {
            url: result.resolvedUrl,
            mimeType: stream.mimeType,
            bitrate: stream.bitrate,
            contentLengthBytes: stream.contentLengthBytes,
            itag: stream.itag,
            fromSignatureCipher: true,
          },
          decipherStrategy: args.strategy.id,
        };
      }
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
    }
  }

  return buildEncryptedSignatureDecipherFailure({
    strategy: args.strategy,
    encryptedStreamCount: args.streams.length,
    errorCode: "YOUTUBE_SIGNATURE_CIPHER_DECIPHER_FAILED",
    errorDetail: lastError,
  });
}

export function extractYouTubeVideoId(input: string): string | null {
  const normalizedInput = input.trim();
  if (YOUTUBE_VIDEO_ID_PATTERN.test(normalizedInput)) {
    return normalizedInput;
  }

  let url: URL;
  try {
    url = new URL(normalizedInput);
  } catch {
    return null;
  }

  const host = url.hostname.toLowerCase();
  const isYoutubeHost =
    host === "youtube.com"
    || host === "www.youtube.com"
    || host === "m.youtube.com"
    || host === "youtube-nocookie.com"
    || host === "www.youtube-nocookie.com";
  const isShortHost = host === "youtu.be" || host === "www.youtu.be";

  let candidate: string | null = null;

  if (isShortHost) {
    candidate = getUrlPathSegment(url.pathname, 0);
  } else if (isYoutubeHost) {
    if (url.pathname === "/watch") {
      candidate = normalizeOptionalString(url.searchParams.get("v"));
    } else if (url.pathname.startsWith("/shorts/")) {
      candidate = getUrlPathSegment(url.pathname, 1);
    } else if (url.pathname.startsWith("/embed/")) {
      candidate = getUrlPathSegment(url.pathname, 1);
    } else if (url.pathname.startsWith("/live/")) {
      candidate = getUrlPathSegment(url.pathname, 1);
    }
  }

  if (!candidate) {
    return null;
  }

  return YOUTUBE_VIDEO_ID_PATTERN.test(candidate) ? candidate : null;
}

export function parseCaptionTracksXml(xml: string): CaptionTrack[] {
  const tracks: CaptionTrack[] = [];
  const trackPattern = /<track\b([^>]*)\/?>/g;
  let trackMatch: RegExpExecArray | null = trackPattern.exec(xml);

  while (trackMatch) {
    const attributeString = trackMatch[1] || "";
    const attributes: Record<string, string> = {};
    const attributePattern = /(\w+)="([^"]*)"/g;
    let attributeMatch: RegExpExecArray | null = attributePattern.exec(attributeString);

    while (attributeMatch) {
      attributes[attributeMatch[1]] = decodeHtmlEntities(attributeMatch[2]);
      attributeMatch = attributePattern.exec(attributeString);
    }

    const languageCode = normalizeOptionalString(attributes.lang_code);
    if (languageCode) {
      const kind = normalizeOptionalString(attributes.kind) || undefined;
      const name = normalizeOptionalString(attributes.name) || languageCode;
      const vssId = normalizeOptionalString(attributes.vss_id) || "";
      tracks.push({
        languageCode,
        name,
        kind,
        isAutoGenerated: kind === "asr" || vssId.startsWith("a."),
      });
    }

    trackMatch = trackPattern.exec(xml);
  }

  return tracks;
}

function extractJsonObjectAfterMarker(source: string, marker: string): string | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) {
    return null;
  }

  const objectStart = source.indexOf("{", markerIndex + marker.length);
  if (objectStart < 0) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let isEscaped = false;

  for (let index = objectStart; index < source.length; index += 1) {
    const char = source[index];

    if (inString) {
      if (isEscaped) {
        isEscaped = false;
      } else if (char === "\\") {
        isEscaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      continue;
    }

    if (char === "{") {
      depth += 1;
      continue;
    }

    if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(objectStart, index + 1);
      }
    }
  }

  return null;
}

function getTrackNameFromPlayerResponse(track: Record<string, unknown>): string {
  const rawName = track.name;
  if (rawName && typeof rawName === "object") {
    const asRecord = rawName as Record<string, unknown>;
    const simpleText = normalizeOptionalString(asRecord.simpleText);
    if (simpleText) {
      return simpleText;
    }
    const runs = Array.isArray(asRecord.runs) ? asRecord.runs : [];
    const joinedRuns = runs
      .map((run) => {
        if (!run || typeof run !== "object") {
          return "";
        }
        return normalizeOptionalString((run as Record<string, unknown>).text) || "";
      })
      .join("")
      .trim();
    if (joinedRuns.length > 0) {
      return joinedRuns;
    }
  }

  const languageCode = normalizeOptionalString(track.languageCode) || "unknown";
  return languageCode;
}

function parseCaptionTracksFromPlayerResponse(playerResponse: unknown): CaptionTrack[] {
  if (!playerResponse || typeof playerResponse !== "object") {
    return [];
  }

  const responseRecord = playerResponse as Record<string, unknown>;
  const captions = responseRecord.captions;
  if (!captions || typeof captions !== "object") {
    return [];
  }

  const renderer = (captions as Record<string, unknown>).playerCaptionsTracklistRenderer;
  if (!renderer || typeof renderer !== "object") {
    return [];
  }

  const captionTracksRaw = (renderer as Record<string, unknown>).captionTracks;
  if (!Array.isArray(captionTracksRaw)) {
    return [];
  }

  const tracks: CaptionTrack[] = [];
  for (const rawTrack of captionTracksRaw) {
    if (!rawTrack || typeof rawTrack !== "object") {
      continue;
    }
    const trackRecord = rawTrack as Record<string, unknown>;
    const languageCode = normalizeOptionalString(trackRecord.languageCode);
    if (!languageCode) {
      continue;
    }
    const baseUrl = normalizeOptionalString(trackRecord.baseUrl) || undefined;
    const kind = normalizeOptionalString(trackRecord.kind) || undefined;
    const vssId = normalizeOptionalString(trackRecord.vssId) || "";

    tracks.push({
      languageCode,
      name: getTrackNameFromPlayerResponse(trackRecord),
      baseUrl,
      kind,
      isAutoGenerated: kind === "asr" || vssId.startsWith("a."),
    });
  }

  return tracks;
}

export function parseAudioStreamCandidatesFromPlayerResponse(
  playerResponse: unknown
): AudioStreamParseResult {
  if (!playerResponse || typeof playerResponse !== "object") {
    return {
      playableStreams: [],
      encryptedSignatureStreams: [],
    };
  }

  const responseRecord = playerResponse as Record<string, unknown>;
  const streamingData = responseRecord.streamingData;
  if (!streamingData || typeof streamingData !== "object") {
    return {
      playableStreams: [],
      encryptedSignatureStreams: [],
    };
  }

  const streamRecord = streamingData as Record<string, unknown>;
  const formatArrays: unknown[] = [];
  if (Array.isArray(streamRecord.adaptiveFormats)) {
    formatArrays.push(...streamRecord.adaptiveFormats);
  }
  if (Array.isArray(streamRecord.formats)) {
    formatArrays.push(...streamRecord.formats);
  }

  const dedupedByUrl = new Map<string, AudioStreamCandidate>();
  const dedupedEncryptedByKey = new Map<string, EncryptedSignatureAudioStreamCandidate>();

  for (const rawFormat of formatArrays) {
    if (!rawFormat || typeof rawFormat !== "object") {
      continue;
    }

    const format = rawFormat as Record<string, unknown>;
    const mimeType = normalizeOptionalString(format.mimeType) || undefined;
    if (!mimeType || !mimeType.toLowerCase().includes("audio/")) {
      continue;
    }

    const directUrl = normalizeOptionalString(format.url);
    let resolvedUrl: string | null = directUrl;
    let fromSignatureCipher = false;

    if (!resolvedUrl) {
      const cipherPayload =
        normalizeOptionalString(format.signatureCipher)
        || normalizeOptionalString(format.cipher);
      if (cipherPayload) {
        const extracted = extractAudioUrlFromCipherString(cipherPayload);
        if (extracted) {
          if (extracted.type === "resolved") {
            resolvedUrl = extracted.url;
            fromSignatureCipher = extracted.fromSignatureCipher;
          } else {
            const contentLength = toFiniteNumber(format.contentLength);
            const bitrate = toFiniteNumber(format.bitrate);
            const itag = toFiniteNumber(format.itag);
            const dedupeKey = `${extracted.baseUrl}|${itag || ""}|${mimeType || ""}`;

            dedupedEncryptedByKey.set(dedupeKey, {
              baseUrl: extracted.baseUrl,
              signatureParamName: extracted.signatureParamName,
              encryptedSignature: extracted.encryptedSignature,
              mimeType,
              bitrate: bitrate && bitrate > 0 ? Math.floor(bitrate) : undefined,
              contentLengthBytes: contentLength && contentLength > 0
                ? Math.floor(contentLength)
                : undefined,
              itag: itag && itag > 0 ? Math.floor(itag) : undefined,
            });
          }
        }
      }
    }

    if (!resolvedUrl) {
      continue;
    }

    const contentLength = toFiniteNumber(format.contentLength);
    const bitrate = toFiniteNumber(format.bitrate);
    const itag = toFiniteNumber(format.itag);

    dedupedByUrl.set(resolvedUrl, {
      url: resolvedUrl,
      mimeType,
      bitrate: bitrate && bitrate > 0 ? Math.floor(bitrate) : undefined,
      contentLengthBytes: contentLength && contentLength > 0
        ? Math.floor(contentLength)
        : undefined,
      itag: itag && itag > 0 ? Math.floor(itag) : undefined,
      fromSignatureCipher,
    });
  }

  return {
    playableStreams: sortAudioStreamsByQuality(Array.from(dedupedByUrl.values())),
    encryptedSignatureStreams: sortAudioStreamsByQuality(
      Array.from(dedupedEncryptedByKey.values())
    ),
  };
}

export function parseAudioStreamsFromPlayerResponse(
  playerResponse: unknown
): AudioStreamCandidate[] {
  return parseAudioStreamCandidatesFromPlayerResponse(playerResponse).playableStreams;
}

function parseVideoMetadataFromPlayerResponse(playerResponse: unknown): VideoMetadata {
  const tracks = parseCaptionTracksFromPlayerResponse(playerResponse);
  const audioCandidates = parseAudioStreamCandidatesFromPlayerResponse(playerResponse);

  if (!playerResponse || typeof playerResponse !== "object") {
    return {
      tracks,
      audioStreams: audioCandidates.playableStreams,
      encryptedSignatureStreams: audioCandidates.encryptedSignatureStreams,
    };
  }

  const responseRecord = playerResponse as Record<string, unknown>;
  const videoDetails = responseRecord.videoDetails;
  if (!videoDetails || typeof videoDetails !== "object") {
    return {
      tracks,
      audioStreams: audioCandidates.playableStreams,
      encryptedSignatureStreams: audioCandidates.encryptedSignatureStreams,
    };
  }

  const title = normalizeOptionalString((videoDetails as Record<string, unknown>).title);
  return {
    title: title || undefined,
    tracks,
    audioStreams: audioCandidates.playableStreams,
    encryptedSignatureStreams: audioCandidates.encryptedSignatureStreams,
  };
}

async function fetchWatchPageMetadata(videoId: string): Promise<VideoMetadata> {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=en`);
  if (!response.ok) {
    return { tracks: [], audioStreams: [], encryptedSignatureStreams: [] };
  }

  const html = await response.text();
  const markers = [
    "ytInitialPlayerResponse = ",
    "var ytInitialPlayerResponse = ",
    "window[\"ytInitialPlayerResponse\"] = ",
  ];

  for (const marker of markers) {
    const objectLiteral = extractJsonObjectAfterMarker(html, marker);
    if (!objectLiteral) {
      continue;
    }
    try {
      const parsed = JSON.parse(objectLiteral);
      const metadata = parseVideoMetadataFromPlayerResponse(parsed);
      if (
        metadata.title
        || metadata.tracks.length > 0
        || metadata.audioStreams.length > 0
        || metadata.encryptedSignatureStreams.length > 0
      ) {
        return metadata;
      }
    } catch {
      // Ignore parser failures and continue with next marker.
    }
  }

  const titleMatch = html.match(/<title>([^<]+)<\/title>/i);
  const title = titleMatch
    ? decodeHtmlEntities(titleMatch[1]).replace(/\s+-\s+YouTube$/i, "").trim()
    : undefined;
  return {
    title: title && title.length > 0 ? title : undefined,
    tracks: [],
    audioStreams: [],
    encryptedSignatureStreams: [],
  };
}

function buildTimedTextJson3Url(videoId: string, track: CaptionTrack): string {
  const params = new URLSearchParams({
    v: videoId,
    lang: track.languageCode,
    fmt: "json3",
  });
  if (track.kind) {
    params.set("kind", track.kind);
  }
  if (track.name && track.name !== track.languageCode) {
    params.set("name", track.name);
  }
  return `https://www.youtube.com/api/timedtext?${params.toString()}`;
}

function normalizeTrackBaseUrl(baseUrl: string): string {
  try {
    const parsed = new URL(baseUrl);
    parsed.searchParams.set("fmt", "json3");
    return parsed.toString();
  } catch {
    return baseUrl.includes("fmt=")
      ? baseUrl.replace(/fmt=[^&]+/g, "fmt=json3")
      : `${baseUrl}&fmt=json3`;
  }
}

async function fetchVideoMetadata(videoId: string): Promise<VideoMetadata> {
  const watchMetadata = await fetchWatchPageMetadata(videoId);

  if (watchMetadata.tracks.length > 0) {
    return watchMetadata;
  }

  const listResponse = await fetch(
    `https://www.youtube.com/api/timedtext?type=list&v=${videoId}`
  );
  const listXml = listResponse.ok ? await listResponse.text() : "";
  const listTracks = listXml.includes("<track")
    ? parseCaptionTracksXml(listXml)
    : [];

  return {
    ...watchMetadata,
    tracks: listTracks,
  };
}

function selectCaptionTrack(tracks: CaptionTrack[], requestedLanguage?: string): CaptionSelection | null {
  if (tracks.length === 0) {
    return null;
  }

  const normalizedRequested = normalizeOptionalString(requestedLanguage)?.toLowerCase();

  const sortByPreferredOrder = (candidates: CaptionTrack[]): CaptionTrack[] =>
    [...candidates].sort((left, right) => {
      const leftScore = (left.isAutoGenerated ? 0 : 10) + (left.name === left.languageCode ? 0 : 1);
      const rightScore = (right.isAutoGenerated ? 0 : 10) + (right.name === right.languageCode ? 0 : 1);
      return rightScore - leftScore;
    });

  if (normalizedRequested) {
    const exact = sortByPreferredOrder(
      tracks.filter(
        (track) => track.languageCode.toLowerCase() === normalizedRequested
      )
    );
    if (exact.length > 0) {
      return { track: exact[0] };
    }

    const prefix = sortByPreferredOrder(
      tracks.filter((track) =>
        track.languageCode.toLowerCase().startsWith(`${normalizedRequested}-`)
      )
    );
    if (prefix.length > 0) {
      return { track: prefix[0] };
    }

    const requestedBaseLanguage = normalizedRequested.split("-")[0];
    const baseLanguage = sortByPreferredOrder(
      tracks.filter((track) => {
        const code = track.languageCode.toLowerCase();
        return (
          code === requestedBaseLanguage
          || code.startsWith(`${requestedBaseLanguage}-`)
        );
      })
    );
    if (baseLanguage.length > 0) {
      return {
        track: baseLanguage[0],
        fallbackReason:
          `No exact transcript for '${normalizedRequested}', using '${baseLanguage[0].languageCode}'.`,
      };
    }
  }

  const englishPreferred = sortByPreferredOrder(
    tracks.filter((track) => {
      const code = track.languageCode.toLowerCase();
      return code === "en" || code.startsWith("en-");
    })
  );
  if (englishPreferred.length > 0) {
    return {
      track: englishPreferred[0],
      fallbackReason: normalizedRequested
        ? `No transcript for '${normalizedRequested}', using '${englishPreferred[0].languageCode}'.`
        : undefined,
    };
  }

  const sortedAll = sortByPreferredOrder(tracks);
  return {
    track: sortedAll[0],
    fallbackReason: normalizedRequested
      ? `No transcript for '${normalizedRequested}', using '${sortedAll[0].languageCode}'.`
      : undefined,
  };
}

export function extractCaptionSegmentsFromJson3(payload: unknown): CaptionSegment[] {
  if (!payload || typeof payload !== "object") {
    return [];
  }
  const payloadRecord = payload as Record<string, unknown>;
  const events = payloadRecord.events;
  if (!Array.isArray(events)) {
    return [];
  }

  const segments: CaptionSegment[] = [];
  for (const rawEvent of events) {
    if (!rawEvent || typeof rawEvent !== "object") {
      continue;
    }
    const eventRecord = rawEvent as Record<string, unknown>;
    const segs = eventRecord.segs;
    if (!Array.isArray(segs)) {
      continue;
    }

    const text = normalizeCaptionText(
      segs
        .map((segment) => {
          if (!segment || typeof segment !== "object") {
            return "";
          }
          return normalizeOptionalString((segment as Record<string, unknown>).utf8) || "";
        })
        .join(" ")
    );
    if (!text) {
      continue;
    }

    const startMsRaw = eventRecord.tStartMs;
    const durationMsRaw = eventRecord.dDurationMs;
    const startMs =
      typeof startMsRaw === "number" && Number.isFinite(startMsRaw)
        ? Math.max(0, Math.floor(startMsRaw))
        : 0;
    const durationMs =
      typeof durationMsRaw === "number" && Number.isFinite(durationMsRaw)
        ? Math.max(0, Math.floor(durationMsRaw))
        : 0;

    segments.push({
      startMs,
      durationMs,
      text,
    });
  }

  return segments;
}

function formatTimestamp(startMs: number): string {
  const totalSeconds = Math.floor(startMs / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${hours.toString().padStart(2, "0")}:${minutes
      .toString()
      .padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
  }
  return `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`;
}

function clampNumber(
  value: unknown,
  options: { min: number; max: number; fallback: number }
): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return options.fallback;
  }
  return Math.min(options.max, Math.max(options.min, Math.floor(value)));
}

function truncateTranscript(
  transcript: string,
  maxCharacters: number
): { transcript: string; isTruncated: boolean } {
  if (transcript.length <= maxCharacters) {
    return {
      transcript,
      isTruncated: false,
    };
  }

  return {
    transcript: `${transcript.slice(0, maxCharacters).trimEnd()}...`,
    isTruncated: true,
  };
}

async function transcribeAudioUrlWithSharedUtility(args: {
  audioUrl: string;
  preferredMimeType?: string;
  language?: string;
  includeTimestamps: boolean;
}) {
  return transcribeMediaAudio({
    audioUrl: args.audioUrl,
    preferredMimeType: args.preferredMimeType,
    language: args.language,
    timestamps: args.includeTimestamps ? "segment" : "none",
    filenameBase: "youtube_audio",
  });
}

export const transcribeYoutubeVideoTool: AITool = {
  name: "transcribe_youtube_video",
  description:
    "Extract transcript text from a YouTube video URL. Supports captions-first mode and audio transcription fallback when captions are unavailable.",
  status: "ready",
  readOnly: true,
  parameters: {
    type: "object",
    properties: {
      videoUrl: {
        type: "string",
        description:
          "YouTube video URL (watch, youtu.be, shorts, live, or embed format).",
      },
      source: {
        type: "string",
        enum: ["auto", "captions", "audio"],
        description:
          "Transcript source mode: auto (captions first, then audio fallback), captions only, or audio only.",
      },
      language: {
        type: "string",
        description:
          "Optional preferred language code (e.g., 'en', 'es', 'de'). Used for caption selection and passed to audio transcription when provided.",
      },
      includeTimestamps: {
        type: "boolean",
        description:
          "When true, include timestamped transcript segments.",
      },
      maxCharacters: {
        type: "number",
        description:
          "Maximum transcript characters to return (500-50000). Defaults to 12000.",
      },
      maxSegments: {
        type: "number",
        description:
          "Maximum timestamped segments to return when includeTimestamps=true (10-500). Defaults to 120.",
      },
      saveToUserFiles: {
        type: "boolean",
        description:
          "When true, save transcript into the user's files as a markdown note.",
      },
      saveParentPath: {
        type: "string",
        description:
          "Optional destination folder path in user files (default '/').",
      },
      saveFileName: {
        type: "string",
        description:
          "Optional transcript filename (for example, 'meeting-transcript.md').",
      },
    },
    required: ["videoUrl"],
  },
  execute: async (
    ctx: ToolExecutionContext,
    args: {
      videoUrl: string;
      source?: TranscriptSource;
      language?: string;
      includeTimestamps?: boolean;
      maxCharacters?: number;
      maxSegments?: number;
      saveToUserFiles?: boolean;
      saveParentPath?: string;
      saveFileName?: string;
    }
  ) => {
    const videoUrl = normalizeOptionalString(args.videoUrl);
    if (!videoUrl) {
      return {
        success: false,
        error: "MISSING_VIDEO_URL",
        message: "Provide a YouTube URL in `videoUrl`.",
      };
    }

    const videoId = extractYouTubeVideoId(videoUrl);
    if (!videoId) {
      return {
        success: false,
        error: "INVALID_YOUTUBE_URL",
        message:
          "Could not extract a valid YouTube video ID from the provided URL.",
      };
    }

    const source = normalizeTranscriptSource(args.source);
    const maxCharacters = clampNumber(args.maxCharacters, {
      min: 500,
      max: 50_000,
      fallback: 12_000,
    });
    const maxSegments = clampNumber(args.maxSegments, {
      min: 10,
      max: 500,
      fallback: 120,
    });

    try {
      const metadata = await fetchVideoMetadata(videoId);
      const availableLanguages = Array.from(
        new Set(metadata.tracks.map((item) => item.languageCode))
      );
      const canonicalUrl = `https://www.youtube.com/watch?v=${videoId}`;
      let captionFailureMessage: string | undefined;

      if (source !== "audio") {
        if (metadata.tracks.length > 0) {
          const selection = selectCaptionTrack(metadata.tracks, args.language);
          if (selection) {
            const track = selection.track;
            const captionUrl = track.baseUrl
              ? normalizeTrackBaseUrl(track.baseUrl)
              : buildTimedTextJson3Url(videoId, track);

            const captionResponse = await fetch(captionUrl);
            if (captionResponse.ok) {
              const captionPayload = await captionResponse.json();
              const segments = extractCaptionSegmentsFromJson3(captionPayload);
              if (segments.length > 0) {
                const fullTranscript = normalizeCaptionText(
                  segments.map((segment) => segment.text).join(" ")
                );
                const truncated = truncateTranscript(fullTranscript, maxCharacters);
                const transcriptFile = args.saveToUserFiles
                  ? await saveTranscriptToUserFiles(ctx, {
                      transcript: fullTranscript,
                      source: "youtube_captions",
                      title: metadata.title,
                      language: track.languageCode,
                      parentPath: args.saveParentPath,
                      fileName: args.saveFileName,
                      metadata: {
                        videoId,
                        canonicalUrl,
                        sourceUsed: "captions",
                        isAutoGenerated: track.isAutoGenerated,
                      },
                    })
                  : undefined;

                return {
                  success: true,
                  sourceUsed: "captions",
                  videoId,
                  canonicalUrl,
                  title: metadata.title,
                  language: track.languageCode,
                  requestedLanguage: args.language || null,
                  isAutoGenerated: track.isAutoGenerated,
                  availableLanguages,
                  segmentCount: segments.length,
                  transcriptLength: fullTranscript.length,
                  maxCharacters,
                  isTruncated: truncated.isTruncated,
                  transcript: truncated.transcript,
                  fallbackNote: selection.fallbackReason,
                  transcriptFile,
                  segments: args.includeTimestamps
                    ? segments.slice(0, maxSegments).map((segment) => ({
                        startMs: segment.startMs,
                        durationMs: segment.durationMs,
                        startTime: formatTimestamp(segment.startMs),
                        text: segment.text,
                      }))
                    : undefined,
                };
              }

              captionFailureMessage =
                "Caption track exists, but no transcript text was returned.";
            } else {
              captionFailureMessage =
                `Failed to fetch captions (${captionResponse.status}).`;
            }
          } else {
            captionFailureMessage = "Could not select a caption track for this video.";
          }
        } else {
          captionFailureMessage =
            "No transcript/captions were found for this video.";
        }

        if (source === "captions") {
          return {
            success: false,
            error: "CAPTION_TRANSCRIPT_UNAVAILABLE",
            videoId,
            canonicalUrl,
            title: metadata.title,
            availableLanguages,
            audioFallbackAvailable:
              metadata.audioStreams.length > 0
              || metadata.encryptedSignatureStreams.length > 0,
            audioFallbackRequiresDecipher:
              metadata.audioStreams.length === 0
              && metadata.encryptedSignatureStreams.length > 0,
            message:
              captionFailureMessage
              || "Caption transcript unavailable for this video.",
          };
        }
      }

      let bestAudioStream = selectBestAudioStream(metadata.audioStreams);
      let decipherStrategyUsed: YouTubeSignatureDecipherStrategyId | null = null;

      if (!bestAudioStream && metadata.encryptedSignatureStreams.length > 0) {
        const decipherConfig = resolveSignatureCipherDecipherConfigFromEnv();
        const decipherStrategy = createSignatureCipherDecipherStrategy(decipherConfig);
        const decipherOutcome = await resolveEncryptedSignatureAudioStream({
          videoId,
          streams: metadata.encryptedSignatureStreams,
          strategy: decipherStrategy,
        });

        if (decipherOutcome.success) {
          bestAudioStream = decipherOutcome.stream;
          decipherStrategyUsed = decipherOutcome.decipherStrategy;
        } else {
          return {
            success: false,
            error: decipherOutcome.code,
            videoId,
            canonicalUrl,
            title: metadata.title,
            availableLanguages,
            encryptedSignatureStreamCount: metadata.encryptedSignatureStreams.length,
            decipherStrategy: decipherOutcome.decipherStrategy,
            decipherEnabled: decipherOutcome.decipherEnabled,
            message: decipherOutcome.message,
            fallbackNote: captionFailureMessage,
            actionableFallbacks: decipherOutcome.actionableFallbacks,
          };
        }
      }

      if (!bestAudioStream) {
        return {
          success: false,
          error: source === "audio"
            ? "AUDIO_STREAM_UNAVAILABLE"
            : "NO_CAPTIONS_AND_NO_AUDIO_STREAM",
          videoId,
          canonicalUrl,
          title: metadata.title,
          availableLanguages,
          encryptedSignatureStreamCount: metadata.encryptedSignatureStreams.length,
          message:
            captionFailureMessage
            ? `${captionFailureMessage} Audio fallback was not available for this video.`
            : "No playable audio stream was available for transcription.",
        };
      }

      const audioTranscription = await transcribeAudioUrlWithSharedUtility({
        audioUrl: bestAudioStream.url,
        preferredMimeType: bestAudioStream.mimeType,
        language: args.language,
        includeTimestamps: true,
      });

      if (!audioTranscription.success) {
        return {
          success: false,
          error: audioTranscription.code,
          videoId,
          canonicalUrl,
          title: metadata.title,
          availableLanguages,
          encryptedSignatureStreamCount: metadata.encryptedSignatureStreams.length,
          decipherStrategy: decipherStrategyUsed,
          message:
            audioTranscription.userMessage,
          details: audioTranscription.message,
          fallbackNote: captionFailureMessage,
        };
      }

      const fullTranscript = normalizeCaptionText(audioTranscription.text);
      const truncated = truncateTranscript(fullTranscript, maxCharacters);
      const segments = audioTranscription.segments;
      const transcriptFile = args.saveToUserFiles
        ? await saveTranscriptToUserFiles(ctx, {
            transcript: fullTranscript,
            source: "youtube_audio",
            title: metadata.title,
            language: audioTranscription.detectedLanguage || args.language || null,
            parentPath: args.saveParentPath,
            fileName: args.saveFileName,
            metadata: {
              videoId,
              canonicalUrl,
              sourceUsed: "audio",
            },
          })
        : undefined;

      return {
        success: true,
        sourceUsed: "audio",
        videoId,
        canonicalUrl,
        title: metadata.title,
        language: audioTranscription.detectedLanguage || args.language || null,
        requestedLanguage: args.language || null,
        availableLanguages,
        segmentCount: segments.length,
        transcriptLength: fullTranscript.length,
        maxCharacters,
        isTruncated: truncated.isTruncated,
        transcript: truncated.transcript,
        fallbackNote: captionFailureMessage,
        transcriptFile,
        audioStream: {
          mimeType: bestAudioStream.mimeType,
          bitrate: bestAudioStream.bitrate,
          itag: bestAudioStream.itag,
          fromSignatureCipher: bestAudioStream.fromSignatureCipher,
          audioBytes: audioTranscription.audioBytes,
          audioContentType: audioTranscription.audioContentType,
          decipherStrategy: decipherStrategyUsed,
        },
        segments: args.includeTimestamps
          ? segments.slice(0, maxSegments).map((segment) => ({
              startMs: segment.startMs,
              durationMs: segment.durationMs,
              startTime: formatTimestamp(segment.startMs),
              text: segment.text,
            }))
          : undefined,
      };
    } catch (error) {
      return {
        success: false,
        error: "YOUTUBE_TRANSCRIPT_ERROR",
        videoId,
        message:
          error instanceof Error
            ? error.message
            : "Unknown transcript error.",
      };
    }
  },
};
