/**
 * System Knowledge Registry
 *
 * Metadata registry + content access for all system knowledge documents.
 * Source of truth: .md files in this directory and ./frameworks/.
 * Content bundled via: _content.ts (auto-generated by scripts/generate-knowledge-content.mjs)
 *
 * Usage:
 *   import { getKnowledgeContent, getCustomerKnowledgeIds } from "./systemKnowledge";
 *   const content = getKnowledgeContent("customer"); // returns array of content strings
 *
 * Categories:
 *   - core: Foundational frameworks loaded in every setup conversation
 *   - framework: Specialized frameworks loaded on-demand based on triggers
 *   - composition: Builder mode composition patterns and recipes
 *   - skill: Detailed execution blueprints for specific template types (trigger-loaded)
 *
 * Usage modes:
 *   - ALWAYS_LOAD: Loaded in every conversation (meta-context only)
 *   - SETUP_MODE: Loaded when agency owner is configuring a client
 *   - CUSTOMER_MODE: Loaded when agent is talking to end customer
 */

import { KNOWLEDGE_CONTENT } from "./_content";

// ============================================================
// Types
// ============================================================

export type KnowledgeCategory = "core" | "framework" | "composition" | "skill";

export type UsageMode =
  | "ALWAYS_LOAD"
  | "SETUP_MODE"
  | "CUSTOMER_MODE"
  | "BUILDER_MODE"
  | "TRIGGER_ONLY";

export interface KnowledgeRegistryEntry {
  id: string;
  name: string;
  category: KnowledgeCategory;
  usage: UsageMode;
  triggers: string[];
  priority: number;
  /** Relative path to the .md file from this directory */
  filePath: string;
}

// ============================================================
// Registry
// ============================================================

export const KNOWLEDGE_REGISTRY: KnowledgeRegistryEntry[] = [
  // ---- Core System Knowledge ----
  {
    id: "meta-context",
    name: "Three-Layer Context Model",
    category: "core",
    usage: "ALWAYS_LOAD",
    triggers: ["every_conversation"],
    priority: 1,
    filePath: "meta-context.md",
  },
  {
    id: "hero-definition",
    name: "Hero Definition Framework",
    category: "core",
    usage: "SETUP_MODE",
    triggers: ["client_onboarding", "agent_creation", "knowledge_base_setup"],
    priority: 2,
    filePath: "hero-definition.md",
  },
  {
    id: "guide-positioning",
    name: "Guide Positioning Framework",
    category: "core",
    usage: "SETUP_MODE",
    triggers: ["client_onboarding", "agent_creation", "brand_voice_setup"],
    priority: 3,
    filePath: "guide-positioning.md",
  },
  {
    id: "plan-and-cta",
    name: "Plan and Call to Action Framework",
    category: "core",
    usage: "SETUP_MODE",
    triggers: ["agent_creation", "funnel_setup", "offer_design"],
    priority: 4,
    filePath: "plan-and-cta.md",
  },
  {
    id: "knowledge-base-structure",
    name: "Knowledge Base Structure Guide",
    category: "core",
    usage: "SETUP_MODE",
    triggers: ["client_onboarding", "knowledge_base_setup"],
    priority: 5,
    filePath: "knowledge-base-structure.md",
  },
  {
    id: "conversation-design",
    name: "Conversation Design Framework",
    category: "core",
    usage: "CUSTOMER_MODE",
    triggers: ["agent_deployed", "customer_conversation"],
    priority: 6,
    filePath: "conversation-design.md",
  },
  {
    id: "handoff-and-escalation",
    name: "Handoff and Escalation Framework",
    category: "core",
    usage: "CUSTOMER_MODE",
    triggers: [
      "agent_deployed",
      "customer_conversation",
      "escalation_needed",
    ],
    priority: 7,
    filePath: "handoff-and-escalation.md",
  },
  {
    id: "follow-up-sequences",
    name: "Follow-Up Sequences Framework",
    category: "core",
    usage: "SETUP_MODE",
    triggers: [
      "nurture_setup",
      "email_sequence_creation",
      "follow_up_design",
    ],
    priority: 8,
    filePath: "follow-up-sequences.md",
  },

  // ---- Adapted Frameworks ----
  {
    id: "storybrand",
    name: "StoryBrand Messaging Framework",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "brand_script_creation",
      "messaging_setup",
      "website_copy",
      "one_liner",
    ],
    priority: 10,
    filePath: "frameworks/storybrand.md",
  },
  {
    id: "icp-research",
    name: "ICP Research Framework",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "client_onboarding",
      "icp_research",
      "market_research",
      "audience_definition",
    ],
    priority: 11,
    filePath: "frameworks/icp-research.md",
  },
  {
    id: "marketing-made-simple",
    name: "Marketing Made Simple Framework",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "funnel_setup",
      "email_setup",
      "lead_generation",
      "website_setup",
      "nurture_sequence",
    ],
    priority: 12,
    filePath: "frameworks/marketing-made-simple.md",
  },
  {
    id: "funnels",
    name: "Funnel Framework Library",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "funnel_design",
      "lead_generation",
      "sales_funnel",
      "offer_design",
      "upsell_design",
    ],
    priority: 13,
    filePath: "frameworks/funnels.md",
  },
  {
    id: "mckinsey-consultant",
    name: "McKinsey Strategy Frameworks",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "market_analysis",
      "competitive_analysis",
      "positioning",
      "pricing_strategy",
      "growth_strategy",
    ],
    priority: 14,
    filePath: "frameworks/mckinsey-consultant.md",
  },
  {
    id: "perfect-webinar",
    name: "Perfect Webinar Content Framework",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "content_creation",
      "video_sales",
      "belief_breaking",
      "offer_design",
      "sales_content",
    ],
    priority: 15,
    filePath: "frameworks/perfect-webinar.md",
  },
  {
    id: "go-to-market-system",
    name: "Go-To-Market System",
    category: "framework",
    usage: "SETUP_MODE",
    triggers: [
      "new_client_launch",
      "offer_validation",
      "mvp_launch",
      "go_to_market",
    ],
    priority: 16,
    filePath: "frameworks/go-to-market-system.md",
  },

  // ---- Composition Knowledge (Builder Mode) ----
  {
    id: "ontology-primitives",
    name: "Platform Ontology Primitives",
    category: "composition",
    usage: "BUILDER_MODE",
    triggers: [
      "composition",
      "build_automation",
      "create_funnel",
      "create_workflow",
      "create_form",
      "create_product",
    ],
    priority: 20,
    filePath: "composition/ontology-primitives.md",
  },
  {
    id: "layers-composition",
    name: "Layers Workflow Composition Patterns",
    category: "composition",
    usage: "BUILDER_MODE",
    triggers: [
      "composition",
      "build_automation",
      "create_workflow",
      "workflow_design",
      "layers_builder",
    ],
    priority: 21,
    filePath: "composition/layers-composition.md",
  },
  {
    id: "use-case-recipes",
    name: "Use Case Recipes",
    category: "composition",
    usage: "BUILDER_MODE",
    triggers: [
      "composition",
      "lead_generation",
      "event_setup",
      "product_launch",
      "booking_system",
      "membership",
      "webinar",
      "ecommerce",
      "onboarding",
      "fundraising",
    ],
    priority: 22,
    filePath: "composition/use-case-recipes.md",
  },
  {
    id: "sequence-patterns",
    name: "Sequence Patterns",
    category: "composition",
    usage: "BUILDER_MODE",
    triggers: [
      "composition",
      "email_sequence_creation",
      "nurture_setup",
      "follow_up_design",
      "create_sequence",
      "launch_sequence",
    ],
    priority: 23,
    filePath: "composition/sequence-patterns.md",
  },

  // ---- Skill Shared Reference (trigger-loaded in Builder Mode) ----
  {
    id: "skill-shared",
    name: "Shared Ontology Reference",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "lead_generation",
      "event_setup",
      "product_launch",
      "booking_system",
      "membership",
      "webinar",
      "ecommerce",
      "onboarding",
      "fundraising",
    ],
    priority: 29,
    filePath: "skills/_SHARED.md",
  },

  // ---- Skills (Builder Mode, trigger-loaded) ----
  {
    id: "skill-lead-generation",
    name: "Lead Generation Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "lead_generation",
      "lead_gen",
      "capture_leads",
      "landing_page",
      "lead_magnet",
      "opt_in",
    ],
    priority: 30,
    filePath: "skills/lead-generation/SKILL.md",
  },
  {
    id: "skill-event-promotion",
    name: "Event Promotion Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "event_setup",
      "event_promotion",
      "workshop",
      "conference",
      "seminar",
      "meetup",
    ],
    priority: 31,
    filePath: "skills/event-promotion/SKILL.md",
  },
  {
    id: "skill-product-launch",
    name: "Product Launch Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "product_launch",
      "new_product",
      "launch_sequence",
      "product_release",
    ],
    priority: 32,
    filePath: "skills/product-launch/SKILL.md",
  },
  {
    id: "skill-booking-appointment",
    name: "Booking / Appointment Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "booking_system",
      "appointment",
      "scheduling",
      "calendar",
      "consultation",
    ],
    priority: 33,
    filePath: "skills/booking-appointment/SKILL.md",
  },
  {
    id: "skill-membership-subscription",
    name: "Membership / Subscription Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "membership",
      "subscription",
      "recurring",
      "community",
      "access",
    ],
    priority: 34,
    filePath: "skills/membership-subscription/SKILL.md",
  },
  {
    id: "skill-webinar-virtual-event",
    name: "Webinar / Virtual Event Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "webinar",
      "masterclass",
      "training",
      "presentation",
      "virtual_event",
    ],
    priority: 35,
    filePath: "skills/webinar-virtual-event/SKILL.md",
  },
  {
    id: "skill-ecommerce-storefront",
    name: "E-Commerce Storefront Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "ecommerce",
      "e_commerce",
      "online_store",
      "shop",
      "catalog",
      "sell_products",
    ],
    priority: 36,
    filePath: "skills/ecommerce-storefront/SKILL.md",
  },
  {
    id: "skill-client-onboarding",
    name: "Client Onboarding Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "onboarding",
      "client_setup",
      "new_client",
      "welcome_client",
      "intake",
    ],
    priority: 37,
    filePath: "skills/client-onboarding/SKILL.md",
  },
  {
    id: "skill-fundraising-donations",
    name: "Fundraising / Donations Skill",
    category: "skill",
    usage: "TRIGGER_ONLY",
    triggers: [
      "fundraising",
      "donations",
      "nonprofit",
      "charity",
      "crowdfunding",
    ],
    priority: 38,
    filePath: "skills/fundraising-donations/SKILL.md",
  },
];

// ============================================================
// Helper Functions
// ============================================================

export type KnowledgeCompositionMode = "setup" | "customer" | "builder";

export interface ComposedKnowledgeDocument extends KnowledgeRegistryEntry {
  content: string;
}

export interface KnowledgeLoadTelemetry {
  mode: KnowledgeCompositionMode;
  requestedTriggers: string[];
  matchedTriggers: string[];
  documentCount: number;
  totalBytes: number;
  documentIds: string[];
}

export interface KnowledgeCompositionContract {
  mode: KnowledgeCompositionMode;
  documents: ComposedKnowledgeDocument[];
  telemetry: KnowledgeLoadTelemetry;
}

const MODE_TO_USAGE: Record<KnowledgeCompositionMode, UsageMode> = {
  setup: "SETUP_MODE",
  customer: "CUSTOMER_MODE",
  builder: "BUILDER_MODE",
};

function normalizeTriggers(additionalTriggers: string[]): string[] {
  return Array.from(
    new Set(
      additionalTriggers
        .map((trigger) => trigger.trim())
        .filter((trigger) => trigger.length > 0)
    )
  );
}

function resolveEntriesForMode(
  mode: KnowledgeCompositionMode,
  additionalTriggers: string[] = []
): { entries: KnowledgeRegistryEntry[]; matchedTriggers: string[] } {
  const targetMode = MODE_TO_USAGE[mode];
  const baseEntries = KNOWLEDGE_REGISTRY.filter(
    (entry) => entry.usage === targetMode || entry.usage === "ALWAYS_LOAD"
  );

  const baseIds = new Set(baseEntries.map((entry) => entry.id));
  const triggerEntriesById = new Map<string, KnowledgeRegistryEntry>();
  const matchedTriggerSet = new Set<string>();

  for (const trigger of additionalTriggers) {
    const matchedEntries = getEntriesByTrigger(trigger);
    if (matchedEntries.length > 0) {
      matchedTriggerSet.add(trigger);
    }
    for (const entry of matchedEntries) {
      if (baseIds.has(entry.id) || triggerEntriesById.has(entry.id)) {
        continue;
      }
      triggerEntriesById.set(entry.id, entry);
    }
  }

  const entries = [...baseEntries, ...triggerEntriesById.values()].sort(
    (a, b) => a.priority - b.priority
  );

  return {
    entries,
    matchedTriggers: Array.from(matchedTriggerSet),
  };
}

export function composeKnowledgeContract(
  mode: KnowledgeCompositionMode,
  additionalTriggers: string[] = []
): KnowledgeCompositionContract {
  const requestedTriggers = normalizeTriggers(additionalTriggers);
  const { entries, matchedTriggers } = resolveEntriesForMode(
    mode,
    requestedTriggers
  );

  const documents = entries
    .map((entry) => ({
      ...entry,
      content: KNOWLEDGE_CONTENT[entry.id] || "",
    }))
    .filter((entry) => entry.content.length > 0);

  return {
    mode,
    documents,
    telemetry: {
      mode,
      requestedTriggers,
      matchedTriggers,
      documentCount: documents.length,
      totalBytes: documents.reduce((total, entry) => total + entry.content.length, 0),
      documentIds: documents.map((entry) => entry.id),
    },
  };
}

/** Get IDs of knowledge entries that should always be loaded. */
export function getAlwaysLoadIds(): string[] {
  return KNOWLEDGE_REGISTRY.filter((k) => k.usage === "ALWAYS_LOAD")
    .sort((a, b) => a.priority - b.priority)
    .map((k) => k.id);
}

/** Get IDs for setup-mode knowledge (core + frameworks). */
export function getSetupKnowledgeIds(): string[] {
  return resolveEntriesForMode("setup").entries.map((entry) => entry.id);
}

/** Get IDs for customer-mode knowledge. */
export function getCustomerKnowledgeIds(): string[] {
  return resolveEntriesForMode("customer").entries.map((entry) => entry.id);
}

/** Get IDs for builder-mode knowledge (composition docs). */
export function getBuilderKnowledgeIds(): string[] {
  return resolveEntriesForMode("builder").entries.map((entry) => entry.id);
}

/** Get entries matching specific triggers. */
export function getEntriesByTrigger(
  trigger: string
): KnowledgeRegistryEntry[] {
  return KNOWLEDGE_REGISTRY.filter((k) => k.triggers.includes(trigger)).sort(
    (a, b) => a.priority - b.priority
  );
}

/** Get a specific entry by ID. */
export function getEntryById(
  id: string
): KnowledgeRegistryEntry | undefined {
  return KNOWLEDGE_REGISTRY.find((k) => k.id === id);
}

/** Get all file paths for a given mode. */
export function getFilePaths(
  mode: KnowledgeCompositionMode,
  additionalTriggers: string[] = []
): string[] {
  return resolveEntriesForMode(mode, normalizeTriggers(additionalTriggers)).entries.map(
    (entry) => entry.filePath
  );
}

/**
 * Detect which skill triggers match a user message via keyword matching.
 * Returns an array of trigger strings that can be passed to getKnowledgeContent().
 */
export function detectSkillTriggers(message: string): string[] {
  const triggers: string[] = [];
  const lower = message.toLowerCase();

  if (/lead|opt.?in|landing|magnet|capture/i.test(lower))
    triggers.push("lead_generation");
  if (/event|workshop|conference|seminar|meetup/i.test(lower))
    triggers.push("event_setup");
  if (/launch|release|new product/i.test(lower))
    triggers.push("product_launch");
  if (/book|appoint|schedul|calendar|consult/i.test(lower))
    triggers.push("booking_system");
  if (/member|subscri|recurring|communit/i.test(lower))
    triggers.push("membership");
  if (/webinar|masterclass|training|presentation/i.test(lower))
    triggers.push("webinar");
  if (/shop|store|ecommerce|e-commerce|catalog/i.test(lower))
    triggers.push("ecommerce");
  if (/onboard|intake|welcome.+client|new.+client/i.test(lower))
    triggers.push("onboarding");
  if (/donat|fundrais|nonprofit|charity|crowdfund/i.test(lower))
    triggers.push("fundraising");

  return triggers;
}

// ============================================================
// Content Access
// ============================================================

/**
 * Get the actual knowledge content strings for a given mode.
 * Returns an array of { id, name, content } sorted by priority.
 *
 * - "customer" mode: meta-context + conversation-design + handoff-and-escalation (~13KB)
 * - "setup" mode: all core + all frameworks (~78KB)
 */
export function getKnowledgeContent(
  mode: KnowledgeCompositionMode,
  additionalTriggers: string[] = []
): Array<{ id: string; name: string; content: string }> {
  return composeKnowledgeContract(mode, additionalTriggers).documents.map(
    ({ id, name, content }) => ({ id, name, content })
  );
}

/**
 * Get a single knowledge document's content by ID.
 */
export function getKnowledgeContentById(id: string): string | undefined {
  return KNOWLEDGE_CONTENT[id];
}
