/**
 * EVENT LANDING PAGE TEMPLATE
 *
 * Full-featured event landing page structure with sticky sidebar checkout.
 * Theme-agnostic: Accepts any theme for styling.
 */

"use client";

import Image from "next/image";
import { Id } from "../../../../convex/_generated/dataModel";
import { TemplateProps } from "../../types";
import { EventLandingContent } from "./schema";
import { CheckoutEmbed } from "@/components/checkout/checkout-embed";
import { SafeHtmlRenderer } from "@/components/ui/safe-html-renderer";
import { RadarMap, GoogleMapFallback } from "@/components/ui/radar-map";
import { GalleryLightbox } from "@/components/ui/gallery-lightbox";
import { useNamespaceTranslations } from "@/hooks/use-namespace-translations";
import { generateMapLink, addToCalendar } from "@/lib/event-utils";
import styles from "./styles.module.css";
import {
  Users,
  Lightbulb,
  Network,
  Award,
  MapPin,
  Calendar,
  Clock,
} from "lucide-react";

// Icon mapping for dynamic icon names
const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  users: Users,
  lightbulb: Lightbulb,
  network: Network,
  award: Award,
  mappin: MapPin,
  calendar: Calendar,
  clock: Clock,
};

// Note: formatEventDate moved inside component to access translation context

// Helper to format time from timestamp (currently unused but may be needed for future enhancements)
/* function formatEventTime(timestamp: number | undefined): string {
  if (!timestamp) return '';
  const date = new Date(timestamp);
  return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
} */

export function EventLandingTemplate({
  page,
  data,
  organization,
  theme,
  sessionId,
}: TemplateProps) {
  // Translation hook
  const { t } = useNamespaceTranslations("ui.event_landing");

  // Helper to format date from timestamp with translations
  const formatEventDate = (timestamp: number | undefined, format: 'short' | 'long' = 'long'): string => {
    if (!timestamp) return '';
    const date = new Date(timestamp);

    const monthNames = [
      'january', 'february', 'march', 'april', 'may', 'june',
      'july', 'august', 'september', 'october', 'november', 'december'
    ];
    const monthShort = [
      'jan', 'feb', 'mar', 'apr', 'may', 'jun',
      'jul', 'aug', 'sep', 'oct', 'nov', 'dec'
    ];
    const dayNames = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

    const year = date.getFullYear();
    const day = date.getDate();
    const monthIndex = date.getMonth();
    const dayIndex = date.getDay();

    if (format === 'short') {
      const month = t(`ui.event_landing.date.month.${monthShort[monthIndex]}`);
      const pattern = t('ui.event_landing.date.format.short');
      return pattern
        .replace('{month}', month)
        .replace('{day}', String(day))
        .replace('{year}', String(year));
    }

    const month = t(`ui.event_landing.date.month_full.${monthNames[monthIndex]}`);
    const weekday = t(`ui.event_landing.date.day_full.${dayNames[dayIndex]}`);
    const pattern = t('ui.event_landing.date.format.long');
    return pattern
      .replace('{weekday}', weekday)
      .replace('{month}', month)
      .replace('{day}', String(day))
      .replace('{year}', String(year));
  };

  // Get template content from page.customProperties.templateContent
  // This is where the content is actually stored when creating/editing pages
  const content =
    (page.customProperties?.templateContent as unknown as EventLandingContent) ||
    ({} as EventLandingContent);

  // Extract event data from the source object
  const eventData = data?.customProperties as Record<string, unknown> | undefined;

  // Extract gallery/media items from event data
  // Media can be in customProperties.media.items or directly in media.items
  const mediaData = ((eventData?.customProperties as any)?.media || (eventData as any)?.media) as { items?: Array<{
    id: string;
    type?: string;
    url?: string;
    thumbnailUrl?: string;
    videoUrl?: string;
    alt?: string;
    filename?: string;
    storageId?: string;
    mimeType?: string;
  }> } | undefined;

  // Helper to get media URL - handles both direct URLs and Convex storage IDs
  const getMediaUrl = (item: any): string => {
    // If it has a videoUrl, it's a video
    if (item.videoUrl) return item.videoUrl;

    // If it has a direct URL (including URLs generated by Convex query), use it
    if (item.url) return item.url;

    // Fallback: if somehow storageId is still present without URL
    if (item.storageId) {
      const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL || '';
      return `${convexUrl}/api/storage/${item.storageId}`;
    }

    return '';
  };

  const galleryItems = mediaData?.items?.map(item => {
    const isVideo = item.type === 'video' || !!item.videoUrl;
    const url = getMediaUrl(item);
    const loopValue = (item as any).loop ?? false;
    const autostartValue = (item as any).autostart ?? false;

    // Debug logging for video settings
    if (isVideo) {
      console.log('[Event Landing] Video item:', {
        id: item.id,
        videoUrl: item.videoUrl,
        loop: loopValue,
        autostart: autostartValue,
        rawItem: item
      });
    }

    return {
      id: item.id,
      type: (isVideo ? 'video' : 'image') as 'image' | 'video',
      url,
      thumbnail: item.thumbnailUrl || (isVideo ? undefined : url),
      alt: item.alt || item.filename,
      loop: isVideo ? loopValue : undefined, // Pass loop setting for videos
      autostart: isVideo ? autostartValue : undefined, // Pass autostart setting for videos
    };
  }).filter(item => item.url) || [];

  // Debug log final gallery items
  console.log('[Event Landing] Gallery items:', galleryItems);


  // Convert event agenda to template format if available
  const eventAgenda = eventData?.agenda as Array<{
    id: string;
    date: number;
    startTime: string;
    endTime?: string;
    title: string;
    description?: string;
    location?: string;
    speaker?: string;
    badge?: {
      text: string;
      color: string;
      enabled: boolean;
    };
  }> | undefined;

  console.log('[Event Landing Template] Event agenda data:', eventAgenda);

  // Convert agenda after formatEventDate is defined
  const agendaDays = eventAgenda && eventAgenda.length > 0 ?
    // Group agenda items by date and sort by time
    Object.values(
      eventAgenda.reduce((acc, item) => {
        const dateKey = formatEventDate(item.date, 'short');
        if (!acc[dateKey]) {
          acc[dateKey] = {
            id: `day-${item.date}`,
            date: dateKey,
            dateTimestamp: item.date, // Keep timestamp for sorting days
            sessions: [],
          };
        }
        acc[dateKey].sessions.push({
          id: item.id,
          time: item.endTime
            ? `${item.startTime} - ${item.endTime}`
            : item.startTime,
          startTime: item.startTime, // Keep for sorting
          title: item.title,
          speaker: item.speaker || '',
          type: item.badge?.enabled && item.badge?.text ? item.badge.text.toLowerCase() : 'session',
          location: item.location,
          badge: item.badge, // Pass through badge config
        });
        return acc;
      }, {} as Record<string, { id: string; date: string; dateTimestamp: number; sessions: Array<{
        id: string;
        time: string;
        startTime: string;
        title: string;
        speaker: string;
        type: string;
        location?: string;
        badge?: {
          text: string;
          color: string;
          enabled: boolean;
        };
      }> }>)
    )
    // Sort days by date
    .sort((a, b) => a.dateTimestamp - b.dateTimestamp)
    // Sort sessions within each day by start time
    .map(day => ({
      ...day,
      sessions: day.sessions.sort((a, b) => {
        // Convert time strings (HH:MM) to comparable numbers
        const timeA = a.startTime.split(':').map(Number);
        const timeB = b.startTime.split(':').map(Number);
        const minutesA = timeA[0] * 60 + timeA[1];
        const minutesB = timeB[0] * 60 + timeB[1];
        return minutesA - minutesB;
      })
    })) : undefined;

  console.log('[Event Landing Template] Converted agenda days:', agendaDays);

  // Merge event data with template content (EVENT DATA TAKES PRECEDENCE - auto-populates as much as possible)
  const mergedContent = {
    ...content,
    hero: {
      headline: (data?.name as string) || content.hero?.headline || '',
      subheadline: (data?.description as string) || content.hero?.subheadline || '',
      date: formatEventDate(eventData?.startDate as number | undefined) || content.hero?.date || '',
      location: (eventData?.venueName as string) || (eventData?.location as string) || content.hero?.location || '',
      format: (eventData?.format === 'online' ? t('ui.event_landing.format.virtual') : eventData?.format === 'in-person' ? t('ui.event_landing.format.in_person') : eventData?.format === 'hybrid' ? t('ui.event_landing.format.hybrid') : undefined) || content.hero?.format || t('ui.event_landing.format.in_person'),
      videoUrl: (eventData?.media as { items?: Array<{ videoUrl?: string }> })?.items?.[0]?.videoUrl || content.hero?.videoUrl,
      imageUrl: content.hero?.imageUrl, // Keep template image as it's typically uploaded separately
      ctaButtons: content.hero?.ctaButtons || [],
    },
    agenda: agendaDays && agendaDays.length > 0
      ? {
          title: content.agenda?.title || t('ui.event_landing.agenda.title'),
          subtitle: content.agenda?.subtitle || t('ui.event_landing.agenda.subtitle'),
          days: agendaDays,
        }
      : content.agenda?.days && content.agenda.days.length > 0
        ? {
            ...content.agenda,
            title: content.agenda.title || t('ui.event_landing.agenda.title'),
            subtitle: content.agenda.subtitle || t('ui.event_landing.agenda.subtitle'),
          }
        : undefined,
  } as EventLandingContent;

  // Get detailed description from event (always use event data if available)
  const detailedDescription = (eventData?.detailedDescription as string | undefined);

  // Apply theme as CSS variables
  const cssVars = {
    "--color-primary": theme.colors.primary,
    "--color-secondary": theme.colors.secondary,
    "--color-accent": theme.colors.accent,
    "--color-background": theme.colors.background,
    "--color-surface": theme.colors.surface,
    "--color-text": theme.colors.text,
    "--color-textLight": theme.colors.textLight,
    "--color-textDark": theme.colors.textDark,
    "--color-border": theme.colors.border,
    "--color-success": theme.colors.success,
    "--color-error": theme.colors.error,
    "--color-warning": theme.colors.warning,
    "--color-info": theme.colors.info,
    "--font-heading": theme.typography.fontFamily.heading,
    "--font-body": theme.typography.fontFamily.body,
    "--font-mono": theme.typography.fontFamily.mono,
    "--font-size-h1": theme.typography.fontSize.h1,
    "--font-size-h2": theme.typography.fontSize.h2,
    "--font-size-h3": theme.typography.fontSize.h3,
    "--font-size-body": theme.typography.fontSize.body,
    "--font-size-small": theme.typography.fontSize.small,
    "--font-weight-normal": theme.typography.fontWeight.normal,
    "--font-weight-medium": theme.typography.fontWeight.medium,
    "--font-weight-semibold": theme.typography.fontWeight.semibold,
    "--font-weight-bold": theme.typography.fontWeight.bold,
    "--line-height-tight": theme.typography.lineHeight.tight,
    "--line-height-normal": theme.typography.lineHeight.normal,
    "--line-height-relaxed": theme.typography.lineHeight.relaxed,
    "--spacing-xs": theme.spacing.xs,
    "--spacing-sm": theme.spacing.sm,
    "--spacing-md": theme.spacing.md,
    "--spacing-lg": theme.spacing.lg,
    "--spacing-xl": theme.spacing.xl,
    "--spacing-2xl": theme.spacing["2xl"],
    "--spacing-3xl": theme.spacing["3xl"],
    "--spacing-4xl": theme.spacing["4xl"],
    "--border-radius-none": theme.borderRadius.none,
    "--border-radius-sm": theme.borderRadius.sm,
    "--border-radius-md": theme.borderRadius.md,
    "--border-radius-lg": theme.borderRadius.lg,
    "--border-radius-xl": theme.borderRadius.xl,
    "--border-radius-full": theme.borderRadius.full,
    "--shadow-none": theme.shadows.none,
    "--shadow-sm": theme.shadows.sm,
    "--shadow-md": theme.shadows.md,
    "--shadow-lg": theme.shadows.lg,
    "--shadow-xl": theme.shadows.xl,
    "--shadow-2xl": theme.shadows["2xl"],
    "--layout-maxWidth-sm": theme.layout.maxWidth.sm,
    "--layout-maxWidth-md": theme.layout.maxWidth.md,
    "--layout-maxWidth-lg": theme.layout.maxWidth.lg,
    "--layout-maxWidth-xl": theme.layout.maxWidth.xl,
    "--layout-maxWidth-2xl": theme.layout.maxWidth["2xl"],
  } as React.CSSProperties;

  return (
    <div className={styles.template} style={cssVars}>
      {/* Navigation - Sticky at top (conditionally rendered) */}
      {mergedContent.showNavigation !== false && (
        <nav className={styles.nav}>
          <div className={styles.navContainer}>
            <div className={styles.navLogo}>{organization.name}</div>
            <div className={styles.navLinks}>
              <a href="#about" className={styles.navLink}>
                {t('ui.event_landing.nav.about')}
              </a>
              <a href="#agenda" className={styles.navLink}>
                {t('ui.event_landing.nav.schedule')}
              </a>
              <a href="#speakers" className={styles.navLink}>
                {t('ui.event_landing.nav.speakers')}
              </a>
              <a href="#faq" className={styles.navLink}>
                {t('ui.event_landing.nav.faq')}
              </a>
            </div>
            <div className={styles.navActions}>
              <button className={styles.navButton}>{t('ui.event_landing.nav.login')}</button>
              <button className={styles.navButtonPrimary}>{t('ui.event_landing.nav.signup')}</button>
            </div>
          </div>
        </nav>
      )}

      {/* Two-column layout: Main content + Sticky sidebar */}
      <div className={styles.layoutGrid}>
        {/* Main Content */}
        <main className={`${styles.mainContent} lg:pr-8`}>
          {/* Hero Section */}
          {mergedContent.hero && (
            <section className={styles.hero} id="hero">
              {(content.hero.videoUrl || content.hero.imageUrl) && (
                <div className={styles.heroBackground}>
                  {mergedContent.hero.imageUrl && (
                    <Image
                      src={mergedContent.hero.imageUrl}
                      alt="Event"
                      fill
                      className={styles.heroBackgroundImage}
                      priority
                    />
                  )}
                </div>
              )}

              <div className={styles.heroGradientOverlay} />

              <div className={styles.heroContent}>
                <div className={styles.heroDateBadge}>{mergedContent.hero.date}</div>

                <h1 className={styles.heroTitle}>{mergedContent.hero.headline}</h1>

                <p className={styles.heroSubtitle}>
                  {mergedContent.hero.subheadline}
                </p>

                <div className={styles.heroInfo}>
                  <a
                    href={generateMapLink(
                      mergedContent.hero.location,
                      eventData?.latitude as number | undefined,
                      eventData?.longitude as number | undefined
                    )}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.heroInfoItem}
                    style={{ cursor: 'pointer', textDecoration: 'none', color: 'inherit' }}
                    title="Open in maps"
                  >
                    <MapPin className={styles.heroIcon} />
                    <span style={{ textDecoration: 'underline' }}>{mergedContent.hero.location}</span>
                  </a>
                  <span className={styles.heroDivider}>•</span>
                  <button
                    onClick={() => {
                      if (eventData?.startDate && eventData?.endDate) {
                        addToCalendar({
                          title: (data?.name as string) || 'Event',
                          description: (data?.description as string),
                          location: mergedContent.hero.location,
                          startDate: eventData.startDate as number,
                          endDate: eventData.endDate as number,
                          url: typeof window !== 'undefined' ? window.location.href : undefined,
                        });
                      }
                    }}
                    className={styles.heroInfoItem}
                    style={{
                      cursor: 'pointer',
                      background: 'none',
                      border: 'none',
                      padding: 0,
                      font: 'inherit',
                      color: 'inherit',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem'
                    }}
                    title="Add to calendar"
                  >
                    <Calendar className={styles.heroIcon} />
                    <span style={{ textDecoration: 'underline' }}>{mergedContent.hero.format}</span>
                  </button>
                </div>

                {mergedContent.hero.ctaButtons &&
                  content.hero.ctaButtons.length > 0 && (
                    <div className={styles.heroButtons}>
                      {mergedContent.hero.ctaButtons.map((btn) => (
                        <a
                          key={btn.id}
                          href={btn.url}
                          className={
                            btn.variant === "primary"
                              ? styles.ctaButtonPrimary
                              : styles.ctaButtonOutline
                          }
                        >
                          {btn.text}
                        </a>
                      ))}
                    </div>
                  )}
              </div>
            </section>
          )}

          {/* Gallery Section - Photo/Video Slideshow */}
          {galleryItems.length > 0 && (
            <section className={styles.section} id="gallery">
              <div className="max-w-6xl mx-auto">
                <h2 className={styles.sectionTitle}>{t('ui.event_landing.gallery.title')}</h2>
                <GalleryLightbox items={galleryItems} />
              </div>
            </section>
          )}

          {/* Venue Details Section - from Event Object */}
          {(eventData?.location || eventData?.formattedAddress) ? (
            <section className={styles.section} id="venue">
              <div className={styles.venueSection}>
                <h2 className={styles.venueTitle}>
                  {t('ui.event_landing.venue.title')}
                </h2>
                {(eventData.formattedAddress || eventData.location) ? (
                  <div className={styles.venueAddress}>
                    <MapPin className="flex-shrink-0 mt-1" size={20} />
                    <div>
                      <div>{String(eventData.formattedAddress || eventData.location)}</div>
                    </div>
                  </div>
                ) : null}
                {eventData.latitude && eventData.longitude ? (
                  <div className={styles.venueMap}>
                    {process.env.NEXT_PUBLIC_RADAR_PUBLISHABLE_KEY ? (
                      <RadarMap
                        latitude={eventData.latitude as number}
                        longitude={eventData.longitude as number}
                        title={String(eventData.formattedAddress || eventData.location || 'Event Location')}
                        height="100%"
                        zoom={15}
                        showMarker={true}
                      />
                    ) : (
                      <GoogleMapFallback
                        latitude={eventData.latitude as number}
                        longitude={eventData.longitude as number}
                        height="100%"
                      />
                    )}
                  </div>
                ) : null}
                {eventData.latitude && eventData.longitude ? (
                  <div className="flex flex-wrap gap-3 mt-4">
                    {/* Google Maps Link */}
                    <a
                      href={`https://www.google.com/maps/dir/?api=1&destination=${eventData.latitude},${eventData.longitude}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border-2 border-gray-800 text-gray-800 hover:bg-gray-800 hover:text-white transition-colors shadow-sm"
                    >
                      <MapPin size={16} />
                      <span>{t('ui.event_landing.venue.google_maps')}</span>
                    </a>

                    {/* Apple Maps Link */}
                    <a
                      href={`https://maps.apple.com/?daddr=${eventData.latitude},${eventData.longitude}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border-2 border-gray-800 text-gray-800 hover:bg-gray-800 hover:text-white transition-colors shadow-sm"
                    >
                      <MapPin size={16} />
                      <span>{t('ui.event_landing.venue.apple_maps')}</span>
                    </a>
                  </div>
                ) : null}
              </div>
            </section>
          ) : null}

          {/* Detailed Description Section - from Event Object */}
          {detailedDescription && !content.about?.description ? (
            <section className={styles.section} id="description">
              <div className={styles.detailedDescription}>
                <SafeHtmlRenderer html={String(detailedDescription)} />
              </div>
            </section>
          ) : null}

          {/* About Section */}
          {mergedContent.about ? (
            <section className={styles.section} id="about">
              <div className={styles.sectionHeader}>
                <h2 className={styles.sectionTitle}>{String(mergedContent.about.title || '')}</h2>
                <div className={styles.sectionDescription}>
                  <SafeHtmlRenderer html={String(mergedContent.about.description || '')} />
                </div>
              </div>

              {mergedContent.about.stats && content.about.stats.length > 0 && (
                <div className={styles.statsGrid}>
                  {mergedContent.about.stats.map((stat) => {
                    const IconComponent =
                      iconMap[stat.icon.toLowerCase()] || Users;
                    return (
                      <div key={stat.id} className={styles.statCard}>
                        <IconComponent className={styles.statIcon} />
                        <div className={styles.statValue}>{stat.value}</div>
                        <div className={styles.statLabel}>{stat.label}</div>
                      </div>
                    );
                  })}
                </div>
              )}

              {mergedContent.about.highlights && content.about.highlights.length > 0 && (
                <div className={styles.highlightsGrid}>
                  {mergedContent.about.highlights.map((highlight) => {
                    const IconComponent =
                      iconMap[highlight.icon.toLowerCase()] || Lightbulb;
                    return (
                      <div key={highlight.id} className={styles.highlightCard}>
                        <div className={styles.highlightIconWrapper}>
                          <IconComponent className={styles.highlightIcon} />
                        </div>
                        <h3 className={styles.highlightTitle}>
                          {highlight.title}
                        </h3>
                        <p className={styles.highlightDescription}>
                          {highlight.description}
                        </p>
                      </div>
                    );
                  })}
                </div>
              )}
            </section>
          ) : null}

          {/* Agenda Section */}
          {mergedContent.agenda &&
            mergedContent.agenda.days &&
            mergedContent.agenda.days.length > 0 && (
              <section className={styles.section} id="agenda">
                <h2 className={styles.sectionTitle}>{mergedContent.agenda.title}</h2>
                <p className={styles.sectionSubtitle}>
                  {mergedContent.agenda.subtitle}
                </p>

                <div className={styles.agendaDays}>
                  {mergedContent.agenda.days.map((day) => (
                    <div key={day.id} className={styles.agendaDayContainer}>
                      <h3 className={styles.agendaDayTitle}>{day.date}</h3>
                      <div className={styles.agendaSessions}>
                        {day.sessions.map((session) => (
                          <div
                            key={session.id}
                            className={styles.agendaSessionCard}
                          >
                            <div className={styles.sessionTimeWrapper}>
                              <Clock className={styles.sessionIcon} />
                              <span className={styles.sessionTime}>
                                {session.time}
                              </span>
                            </div>

                            <div className={styles.sessionContent}>
                              <div className={styles.sessionHeader}>
                                <h4 className={styles.sessionTitle}>
                                  {session.title}
                                </h4>
                                {session.badge?.enabled ? (
                                  <span
                                    className={styles.sessionType}
                                    style={{
                                      backgroundColor: session.badge.color,
                                      color: 'white',
                                    }}
                                  >
                                    {session.badge.text}
                                  </span>
                                ) : (
                                  <span
                                    className={`${styles.sessionType} ${styles[`sessionType-${session.type}`]}`}
                                  >
                                    {t(`ui.event_landing.session_type.${session.type}`)}
                                  </span>
                                )}
                              </div>

                              {session.speaker && (
                                <p className={styles.sessionSpeaker}>
                                  {session.speaker}
                                </p>
                              )}

                              {session.location && (
                                <div className={styles.sessionLocation}>
                                  <MapPin className={styles.sessionIcon} />
                                  <span>{session.location}</span>
                                </div>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

          {/* Speakers, Testimonials, FAQ sections continue... */}
          {/* (keeping original code for these sections) */}
          {mergedContent.speakers &&
            content.speakers.speakers &&
            content.speakers.speakers.length > 0 && (
              <section className={styles.section} id="speakers">
                <h2 className={styles.sectionTitle}>
                  {mergedContent.speakers.title}
                </h2>
                <p className={styles.sectionSubtitle}>
                  {mergedContent.speakers.subtitle}
                </p>

                <div className={styles.speakersGrid}>
                  {mergedContent.speakers.speakers.map((speaker) => (
                    <div key={speaker.id} className={styles.speakerCard}>
                      <div className={styles.speakerImageWrapper}>
                        <Image
                          src={speaker.imageUrl}
                          alt={speaker.name}
                          width={200}
                          height={200}
                          className={styles.speakerImage}
                        />
                      </div>

                      <div className={styles.speakerContent}>
                        <h3 className={styles.speakerName}>{speaker.name}</h3>
                        <p className={styles.speakerTitle}>
                          {speaker.role}
                          {speaker.company && `, ${speaker.company}`}
                        </p>
                        <p className={styles.speakerBio}>{speaker.bio}</p>

                        {speaker.socialLinks && (
                          <div className={styles.speakerSocial}>
                            {speaker.socialLinks.twitter && (
                              <a
                                href={speaker.socialLinks.twitter}
                                className={styles.socialLink}
                                target="_blank"
                                rel="noopener noreferrer"
                                aria-label="Twitter"
                              >
                                <svg
                                  className={styles.socialIcon}
                                  viewBox="0 0 24 24"
                                  fill="none"
                                  stroke="currentColor"
                                  strokeWidth="2"
                                >
                                  <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
                                </svg>
                              </a>
                            )}
                            {speaker.socialLinks.linkedin && (
                              <a
                                href={speaker.socialLinks.linkedin}
                                className={styles.socialLink}
                                target="_blank"
                                rel="noopener noreferrer"
                                aria-label="LinkedIn"
                              >
                                <svg
                                  className={styles.socialIcon}
                                  viewBox="0 0 24 24"
                                  fill="none"
                                  stroke="currentColor"
                                  strokeWidth="2"
                                >
                                  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
                                  <rect x="2" y="9" width="4" height="12" />
                                  <circle cx="4" cy="4" r="2" />
                                </svg>
                              </a>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

          {mergedContent.testimonials &&
            content.testimonials.testimonials &&
            content.testimonials.testimonials.length > 0 && (
              <section className={styles.section} id="testimonials">
                <h2 className={styles.sectionTitle}>
                  {mergedContent.testimonials.title}
                </h2>
                <p className={styles.sectionSubtitle}>
                  {mergedContent.testimonials.subtitle}
                </p>

                <div className={styles.testimonialsGrid}>
                  {mergedContent.testimonials.testimonials.map((testimonial) => (
                    <div key={testimonial.id} className={styles.testimonialCard}>
                      <div className={styles.testimonialStars}>
                        {[...Array(5)].map((_, i) => (
                          <svg
                            key={i}
                            className={styles.starIcon}
                            viewBox="0 0 24 24"
                            fill="currentColor"
                          >
                            <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                          </svg>
                        ))}
                      </div>

                      <p className={styles.testimonialQuote}>
                        &ldquo;{testimonial.quote}&rdquo;
                      </p>

                      <div className={styles.testimonialAuthor}>
                        {testimonial.imageUrl && (
                          <Image
                            src={testimonial.imageUrl}
                            alt={testimonial.author}
                            width={60}
                            height={60}
                            className={styles.testimonialImage}
                          />
                        )}
                        <div className={styles.testimonialAuthorInfo}>
                          <div className={styles.testimonialName}>
                            {testimonial.author}
                          </div>
                          <div className={styles.testimonialRole}>
                            {testimonial.role}
                            {testimonial.company && `, ${testimonial.company}`}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

          {mergedContent.faq &&
            content.faq.questions &&
            content.faq.questions.length > 0 && (
              <section className={styles.section} id="faq">
                <h2 className={styles.sectionTitle}>{mergedContent.faq.title}</h2>
                <p className={styles.sectionSubtitle}>{mergedContent.faq.subtitle}</p>

                <div className={styles.faqList}>
                  {mergedContent.faq.questions.map((faq) => (
                    <div key={faq.id} className={styles.faqItem}>
                      <h3 className={styles.faqQuestion}>{faq.question}</h3>
                      <p className={styles.faqAnswer}>{faq.answer}</p>
                    </div>
                  ))}
                </div>

                {mergedContent.faq.contactEmail && (
                  <div className={styles.faqContact}>
                    <h3 className={styles.faqContactTitle}>{t('ui.event_landing.faq.still_have_questions')}</h3>
                    <p className={styles.faqContactText}>
                      {t('ui.event_landing.faq.contact_text')}
                    </p>
                    <a href={`mailto:${mergedContent.faq.contactEmail}`} className={styles.faqContactLink}>
                      {mergedContent.faq.contactEmail}
                    </a>
                  </div>
                )}
              </section>
            )}
        </main>

        {/* Checkout Sidebar (Desktop only) */}
        <aside className="hidden lg:block w-full max-w-[400px]">
          <div className="pt-8">
            {content.linkedCheckoutId ? (
              <CheckoutEmbed
                checkoutInstanceId={content.linkedCheckoutId as Id<"objects">}
                organizationId={organization._id as Id<"organizations">}
                sessionId={sessionId}
                className="w-full"
                emptyState={
                  <div className={styles.checkoutPlaceholder}>
                    <div className={styles.placeholderIcon}>🛒</div>
                    <h3 className={styles.placeholderTitle}>{t('ui.event_landing.checkout.no_products_linked_title')}</h3>
                    <p className={styles.placeholderText}>
                      {t('ui.event_landing.checkout.no_products_linked_text')}
                    </p>
                  </div>
                }
              />
            ) : (
              <div className={styles.checkoutPlaceholder}>
                <div className={styles.placeholderIcon}>🛒</div>
                <h3 className={styles.placeholderTitle}>{t('ui.event_landing.checkout.no_checkout_linked_title')}</h3>
                <p className={styles.placeholderText}>
                  {t('ui.event_landing.checkout.no_checkout_linked_text')}
                </p>
              </div>
            )}
          </div>
        </aside>
      </div>

      {/* Mobile-only Checkout Section */}
      {content.linkedCheckoutId && (
        <section className="lg:hidden px-4 pt-8 pb-32 bg-gray-50" id="checkout">
          <div className="max-w-2xl mx-auto">
            <h2 className="text-2xl font-bold mb-2 text-center">
              {mergedContent.checkout.title}
            </h2>
            {mergedContent.checkout.description && (
              <p className="text-gray-600 text-center mb-6">
                {mergedContent.checkout.description}
              </p>
            )}
            <CheckoutEmbed
              checkoutInstanceId={content.linkedCheckoutId as Id<"objects">}
              organizationId={organization._id as Id<"organizations">}
              sessionId={sessionId}
              className="w-full"
              emptyState={
                <div className={styles.checkoutPlaceholder}>
                  <div className={styles.placeholderIcon}>🛒</div>
                  <h3 className={styles.placeholderTitle}>{t('ui.event_landing.checkout.no_products_linked_title')}</h3>
                  <p className={styles.placeholderText}>
                    {t('ui.event_landing.checkout.no_products_linked_text')}
                  </p>
                </div>
              }
            />
          </div>
        </section>
      )}

      {/* Mobile Checkout - Fixed at bottom */}
      {content.linkedCheckoutId && (
        <div className={styles.mobileCheckout}>
          <div className={styles.mobileCheckoutContent}>
            <div>
              <div className={styles.mobileCheckoutTitle}>
                {t('ui.event_landing.checkout.get_ticket')}
              </div>
              <div className={styles.mobileCheckoutPrice}>
                {t('ui.event_landing.checkout.view_available_tickets')}
              </div>
            </div>
            <a
              href="#checkout"
              className={styles.mobileCheckoutButton}
              onClick={(e) => {
                e.preventDefault();
                const checkoutSection = document.getElementById('checkout');
                if (checkoutSection) {
                  checkoutSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
              }}
            >
              {t('ui.event_landing.checkout.view_tickets')}
            </a>
          </div>
        </div>
      )}
    </div>
  );
}
