/**
 * L4YERCAK3 API Client
 * Auto-generated by @l4yercak3/cli
 *
 * A fully-typed API client for the L4YERCAK3 platform.
 * Organization ID: ks76v27s40kzdqhf5x5ztqrdth83erpy
 */

import type {
  Contact, ContactCreateInput, ContactUpdateInput,
  Organization, OrganizationCreateInput,
  Event, EventCreateInput,
  Attendee,
  Form, FormSubmission,
  Product, Order, OrderItem,
  Invoice, InvoiceCreateInput,
  BenefitClaim, BenefitClaimInput,
  CommissionPayout,
  PaginatedResponse,
} from './types';

export class L4yercak3Client {
  private apiKey: string;
  private baseUrl: string;
  private organizationId: string;

  constructor(config: { apiKey: string; baseUrl?: string; organizationId?: string }) {
    this.apiKey = config.apiKey;
    this.baseUrl = config.baseUrl || 'https://agreeable-lion-828.convex.site';
    this.organizationId = config.organizationId || 'ks76v27s40kzdqhf5x5ztqrdth83erpy';
  }

  // ============ CRM: Contacts ============

  async listContacts(params?: {
    limit?: number;
    offset?: number;
    status?: 'active' | 'inactive' | 'archived';
    subtype?: 'customer' | 'lead' | 'prospect' | 'partner';
    search?: string;
    tags?: string[];
  }): Promise<PaginatedResponse<Contact>> {
    return this.request('GET', '/api/v1/crm/contacts', { params });
  }

  async getContact(id: string, options?: {
    includeActivities?: boolean;
    includeNotes?: boolean;
    includeOrganization?: boolean;
  }): Promise<Contact> {
    return this.request('GET', `/api/v1/crm/contacts/${id}`, { params: options });
  }

  async createContact(data: ContactCreateInput): Promise<Contact> {
    return this.request('POST', '/api/v1/crm/contacts', { body: data });
  }

  async updateContact(id: string, data: ContactUpdateInput): Promise<Contact> {
    return this.request('PATCH', `/api/v1/crm/contacts/${id}`, { body: data });
  }

  async deleteContact(id: string): Promise<void> {
    return this.request('DELETE', `/api/v1/crm/contacts/${id}`);
  }

  async addTagsToContact(id: string, tags: string[]): Promise<Contact> {
    return this.request('POST', `/api/v1/crm/contacts/${id}/tags`, { body: { tags } });
  }

  async removeTagsFromContact(id: string, tags: string[]): Promise<Contact> {
    return this.request('DELETE', `/api/v1/crm/contacts/${id}/tags`, { body: { tags } });
  }

  // ============ CRM: Organizations ============

  async listOrganizations(params?: {
    limit?: number;
    offset?: number;
    subtype?: 'customer' | 'prospect' | 'partner' | 'vendor';
    search?: string;
  }): Promise<PaginatedResponse<Organization>> {
    return this.request('GET', '/api/v1/crm/organizations', { params });
  }

  async getOrganization(id: string, options?: {
    includeContacts?: boolean;
  }): Promise<Organization> {
    return this.request('GET', `/api/v1/crm/organizations/${id}`, { params: options });
  }

  async createOrganization(data: OrganizationCreateInput): Promise<Organization> {
    return this.request('POST', '/api/v1/crm/organizations', { body: data });
  }

  // ============ Events ============

  async listEvents(params?: {
    status?: 'draft' | 'published' | 'cancelled' | 'completed';
    fromDate?: string;
    toDate?: string;
    limit?: number;
    offset?: number;
  }): Promise<PaginatedResponse<Event>> {
    return this.request('GET', '/api/v1/events', { params });
  }

  async getEvent(id: string, options?: {
    includeProducts?: boolean;
    includeSponsors?: boolean;
    includeForms?: boolean;
  }): Promise<Event> {
    return this.request('GET', `/api/v1/events/${id}`, { params: options });
  }

  async createEvent(data: EventCreateInput): Promise<Event> {
    return this.request('POST', '/api/v1/events', { body: data });
  }

  async updateEvent(id: string, data: Partial<EventCreateInput>): Promise<Event> {
    return this.request('PATCH', `/api/v1/events/${id}`, { body: data });
  }

  async getEventAttendees(eventId: string, params?: {
    status?: 'registered' | 'checked_in' | 'cancelled' | 'no_show';
    limit?: number;
    offset?: number;
  }): Promise<PaginatedResponse<Attendee>> {
    return this.request('GET', `/api/v1/events/${eventId}/attendees`, { params });
  }

  async checkInAttendee(eventId: string, attendeeId: string): Promise<Attendee> {
    return this.request('POST', `/api/v1/events/${eventId}/attendees/${attendeeId}/check-in`);
  }

  // ============ Forms ============

  async listForms(params?: {
    status?: 'draft' | 'published' | 'closed';
    eventId?: string;
    subtype?: 'registration' | 'survey' | 'application' | 'feedback' | 'contact';
    limit?: number;
  }): Promise<PaginatedResponse<Form>> {
    return this.request('GET', '/api/v1/forms', { params });
  }

  async getForm(id: string): Promise<Form> {
    return this.request('GET', `/api/v1/forms/${id}`);
  }

  async submitForm(formId: string, data: Record<string, unknown>): Promise<FormSubmission> {
    return this.request('POST', `/api/v1/forms/${formId}/submit`, { body: data });
  }

  async getFormResponses(formId: string, params?: {
    status?: 'submitted' | 'reviewed' | 'approved' | 'rejected';
    limit?: number;
    offset?: number;
  }): Promise<PaginatedResponse<FormSubmission>> {
    return this.request('GET', `/api/v1/forms/${formId}/responses`, { params });
  }

  // ============ Products ============

  async listProducts(params?: {
    eventId?: string;
    status?: 'active' | 'sold_out' | 'hidden';
    category?: string;
    limit?: number;
  }): Promise<PaginatedResponse<Product>> {
    return this.request('GET', '/api/v1/products', { params });
  }

  async getProduct(id: string): Promise<Product> {
    return this.request('GET', `/api/v1/products/${id}`);
  }

  // ============ Checkout ============

  async createCheckoutSession(data: {
    items: Array<{ productId: string; quantity: number }>;
    contactId?: string;
    email?: string;
    successUrl: string;
    cancelUrl: string;
    metadata?: Record<string, string>;
  }): Promise<{ sessionId: string; checkoutUrl: string }> {
    return this.request('POST', '/api/v1/checkout/sessions', { body: data });
  }

  async getCheckoutSession(sessionId: string): Promise<{
    sessionId: string;
    status: 'open' | 'complete' | 'expired';
    order?: Order;
  }> {
    return this.request('GET', `/api/v1/checkout/sessions/${sessionId}`);
  }

  // ============ Orders ============

  async listOrders(params?: {
    contactId?: string;
    status?: 'pending' | 'paid' | 'refunded' | 'cancelled';
    fromDate?: string;
    toDate?: string;
    limit?: number;
  }): Promise<PaginatedResponse<Order>> {
    return this.request('GET', '/api/v1/orders', { params });
  }

  async getOrder(id: string): Promise<Order> {
    return this.request('GET', `/api/v1/orders/${id}`);
  }

  // ============ Invoicing ============

  async listInvoices(params?: {
    contactId?: string;
    organizationId?: string;
    status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
    type?: 'b2b' | 'b2c';
    limit?: number;
  }): Promise<PaginatedResponse<Invoice>> {
    return this.request('GET', '/api/v1/invoices', { params });
  }

  async getInvoice(id: string): Promise<Invoice> {
    return this.request('GET', `/api/v1/invoices/${id}`);
  }

  async createInvoice(data: InvoiceCreateInput): Promise<Invoice> {
    return this.request('POST', '/api/v1/invoices', { body: data });
  }

  async sendInvoice(id: string, options?: {
    emailTo?: string;
    message?: string;
  }): Promise<void> {
    return this.request('POST', `/api/v1/invoices/${id}/send`, { body: options });
  }

  async markInvoicePaid(id: string, data?: {
    paidAt?: string;
    paymentMethod?: string;
    paymentReference?: string;
  }): Promise<Invoice> {
    return this.request('POST', `/api/v1/invoices/${id}/mark-paid`, { body: data });
  }

  async getInvoicePdf(id: string): Promise<{ pdfUrl: string }> {
    return this.request('GET', `/api/v1/invoices/${id}/pdf`);
  }

  // ============ Benefits ============

  async listBenefitClaims(params?: {
    memberId?: string;
    status?: 'pending' | 'approved' | 'rejected' | 'paid' | 'cancelled';
    benefitType?: string;
    limit?: number;
  }): Promise<PaginatedResponse<BenefitClaim>> {
    return this.request('GET', '/api/v1/benefits/claims', { params });
  }

  async getBenefitClaim(id: string): Promise<BenefitClaim> {
    return this.request('GET', `/api/v1/benefits/claims/${id}`);
  }

  async createBenefitClaim(data: BenefitClaimInput): Promise<BenefitClaim> {
    return this.request('POST', '/api/v1/benefits/claims', { body: data });
  }

  async approveBenefitClaim(id: string, notes?: string): Promise<BenefitClaim> {
    return this.request('POST', `/api/v1/benefits/claims/${id}/approve`, { body: { notes } });
  }

  async rejectBenefitClaim(id: string, reason: string): Promise<BenefitClaim> {
    return this.request('POST', `/api/v1/benefits/claims/${id}/reject`, { body: { reason } });
  }

  async listCommissionPayouts(params?: {
    memberId?: string;
    status?: 'pending' | 'processing' | 'completed' | 'failed';
    limit?: number;
  }): Promise<PaginatedResponse<CommissionPayout>> {
    return this.request('GET', '/api/v1/benefits/commissions', { params });
  }

  // ============ Projects ============

  async listProjects(params?: {
    status?: 'active' | 'completed' | 'archived';
    limit?: number;
  }): Promise<PaginatedResponse<{ id: string; name: string; status: string }>> {
    return this.request('GET', '/api/v1/projects', { params });
  }

  async getProject(id: string): Promise<{ id: string; name: string; status: string; tasks: unknown[] }> {
    return this.request('GET', `/api/v1/projects/${id}`);
  }

  // ============ Internal Request Handler ============

  private async request<T>(
    method: string,
    path: string,
    options?: {
      params?: Record<string, unknown>;
      body?: unknown;
    }
  ): Promise<T> {
    const url = new URL(path, this.baseUrl);

    if (options?.params) {
      Object.entries(options.params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          if (Array.isArray(value)) {
            value.forEach(v => url.searchParams.append(key, String(v)));
          } else {
            url.searchParams.set(key, String(value));
          }
        }
      });
    }

    const response = await fetch(url.toString(), {
      method,
      headers: {
        'Authorization': `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json',
        'X-Organization-Id': this.organizationId,
      },
      body: options?.body ? JSON.stringify(options.body) : undefined,
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new L4yercak3Error(
        response.status,
        error.message || `Request failed: ${response.status}`,
        error.code,
        error
      );
    }

    // Handle 204 No Content
    if (response.status === 204) {
      return undefined as T;
    }

    return response.json();
  }
}

export class L4yercak3Error extends Error {
  constructor(
    public status: number,
    message: string,
    public code?: string,
    public details?: unknown
  ) {
    super(message);
    this.name = 'L4yercak3Error';
  }
}

// Singleton instance
let client: L4yercak3Client | null = null;

export function getL4yercak3Client(): L4yercak3Client {
  if (!client) {
    const apiKey = process.env.L4YERCAK3_API_KEY;
    if (!apiKey) {
      throw new Error('L4YERCAK3_API_KEY environment variable is required');
    }
    client = new L4yercak3Client({ apiKey });
  }
  return client;
}
