/**
 * L4YERCAK3 API Types
 * Auto-generated by @l4yercak3/cli
 *
 * Comprehensive type definitions for the L4YERCAK3 platform.
 */

// ============ CRM Types ============

export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  company?: string;
  jobTitle?: string;
  status: 'active' | 'inactive' | 'unsubscribed' | 'archived';
  subtype: 'customer' | 'lead' | 'prospect' | 'partner';
  tags: string[];
  customFields?: Record<string, unknown>;
  organizationId?: string;
  organization?: Organization;
  avatarUrl?: string;
  notes?: ContactNote[];
  activities?: ContactActivity[];
  createdAt: string;
  updatedAt: string;
}

export interface ContactCreateInput {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  company?: string;
  jobTitle?: string;
  subtype?: 'customer' | 'lead' | 'prospect' | 'partner';
  tags?: string[];
  customFields?: Record<string, unknown>;
  organizationId?: string;
}

export interface ContactUpdateInput {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  company?: string;
  jobTitle?: string;
  status?: 'active' | 'inactive' | 'unsubscribed';
  subtype?: 'customer' | 'lead' | 'prospect' | 'partner';
  tags?: string[];
  customFields?: Record<string, unknown>;
}

export interface ContactNote {
  id: string;
  content: string;
  createdBy: string;
  createdAt: string;
}

export interface ContactActivity {
  id: string;
  type: 'email' | 'call' | 'meeting' | 'note' | 'task' | 'event';
  title: string;
  description?: string;
  occurredAt: string;
  metadata?: Record<string, unknown>;
}

export interface Organization {
  id: string;
  name: string;
  website?: string;
  industry?: string;
  size?: 'small' | 'medium' | 'large' | 'enterprise';
  subtype: 'customer' | 'prospect' | 'partner' | 'vendor';
  address?: Address;
  taxId?: string;
  billingEmail?: string;
  contacts?: Contact[];
  createdAt: string;
  updatedAt: string;
}

export interface OrganizationCreateInput {
  name: string;
  website?: string;
  industry?: string;
  size?: 'small' | 'medium' | 'large' | 'enterprise';
  subtype?: 'customer' | 'prospect' | 'partner' | 'vendor';
  address?: AddressInput;
  taxId?: string;
  billingEmail?: string;
}

// ============ Event Types ============

export interface Event {
  id: string;
  name: string;
  description?: string;
  shortDescription?: string;
  startDate: string;
  endDate: string;
  timezone: string;
  location: string;
  venue?: Venue;
  status: 'draft' | 'published' | 'cancelled' | 'completed';
  subtype: 'conference' | 'workshop' | 'webinar' | 'meetup' | 'seminar' | 'other';
  maxCapacity?: number;
  registeredCount?: number;
  imageUrl?: string;
  coverImageUrl?: string;
  products?: Product[];
  sponsors?: Sponsor[];
  forms?: Form[];
  tags?: string[];
  customFields?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface EventCreateInput {
  name: string;
  description?: string;
  shortDescription?: string;
  startDate: string;
  endDate: string;
  timezone?: string;
  location: string;
  venue?: VenueInput;
  subtype?: 'conference' | 'workshop' | 'webinar' | 'meetup' | 'seminar' | 'other';
  maxCapacity?: number;
  imageUrl?: string;
  tags?: string[];
}

export interface Attendee {
  id: string;
  contactId: string;
  contact: Contact;
  eventId: string;
  ticketId: string;
  ticketName: string;
  status: 'registered' | 'checked_in' | 'cancelled' | 'no_show';
  checkedInAt?: string;
  checkedInBy?: string;
  registeredAt: string;
  metadata?: Record<string, unknown>;
}

export interface Venue {
  name: string;
  address: Address;
  capacity?: number;
  website?: string;
  phone?: string;
  notes?: string;
}

export interface VenueInput {
  name: string;
  address: AddressInput;
  capacity?: number;
  website?: string;
  phone?: string;
}

export interface Sponsor {
  id: string;
  organizationId: string;
  organizationName: string;
  level: 'platinum' | 'gold' | 'silver' | 'bronze' | 'community';
  logoUrl?: string;
  websiteUrl?: string;
  description?: string;
  order?: number;
}

// ============ Form Types ============

export interface Form {
  id: string;
  name: string;
  description?: string;
  status: 'draft' | 'published' | 'closed';
  subtype: 'registration' | 'survey' | 'application' | 'feedback' | 'contact' | 'custom';
  eventId?: string;
  fields: FormField[];
  settings: FormSettings;
  responseCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface FormField {
  id: string;
  type: FormFieldType;
  label: string;
  name: string;
  required: boolean;
  placeholder?: string;
  helpText?: string;
  options?: FormFieldOption[];
  validation?: FormFieldValidation;
  conditionalLogic?: FormFieldConditional;
  order: number;
}

export type FormFieldType =
  | 'text'
  | 'email'
  | 'phone'
  | 'number'
  | 'textarea'
  | 'select'
  | 'multiselect'
  | 'checkbox'
  | 'radio'
  | 'date'
  | 'datetime'
  | 'time'
  | 'file'
  | 'image'
  | 'signature'
  | 'rating'
  | 'slider'
  | 'hidden';

export interface FormFieldOption {
  label: string;
  value: string;
}

export interface FormFieldValidation {
  min?: number;
  max?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  customMessage?: string;
}

export interface FormFieldConditional {
  action: 'show' | 'hide' | 'require';
  conditions: Array<{
    fieldId: string;
    operator: 'equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than';
    value: unknown;
  }>;
  logic: 'and' | 'or';
}

export interface FormSettings {
  submitButtonText: string;
  confirmationMessage: string;
  redirectUrl?: string;
  notifyEmails: string[];
  allowMultipleSubmissions: boolean;
  requireAuth: boolean;
  closedMessage?: string;
  limitResponses?: number;
}

export interface FormSubmission {
  id: string;
  formId: string;
  contactId?: string;
  contact?: Contact;
  data: Record<string, unknown>;
  status: 'submitted' | 'reviewed' | 'approved' | 'rejected';
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;
  submittedAt: string;
  metadata?: {
    ipAddress?: string;
    userAgent?: string;
    referrer?: string;
  };
}

// ============ Product & Checkout Types ============

export interface Product {
  id: string;
  name: string;
  description?: string;
  shortDescription?: string;
  priceInCents: number;
  currency: string;
  eventId?: string;
  category?: string;
  sku?: string;
  status: 'active' | 'sold_out' | 'hidden' | 'archived';
  inventory?: number;
  maxPerOrder?: number;
  minPerOrder?: number;
  salesStart?: string;
  salesEnd?: string;
  imageUrl?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface Order {
  id: string;
  orderNumber: string;
  contactId: string;
  contact?: Contact;
  items: OrderItem[];
  subtotalInCents: number;
  discountInCents?: number;
  taxInCents?: number;
  totalInCents: number;
  currency: string;
  status: 'pending' | 'paid' | 'partially_refunded' | 'refunded' | 'cancelled';
  paymentStatus: 'unpaid' | 'paid' | 'refunded';
  stripePaymentIntentId?: string;
  stripeCustomerId?: string;
  billingAddress?: Address;
  notes?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
  completedAt?: string;
}

export interface OrderItem {
  id: string;
  productId: string;
  productName: string;
  productSku?: string;
  quantity: number;
  unitPriceInCents: number;
  totalPriceInCents: number;
  metadata?: Record<string, unknown>;
}

// ============ Invoice Types ============

export interface Invoice {
  id: string;
  number: string;
  contactId?: string;
  contact?: Contact;
  organizationId?: string;
  organization?: Organization;
  type: 'b2b' | 'b2c';
  status: 'draft' | 'sent' | 'viewed' | 'paid' | 'overdue' | 'cancelled' | 'void';
  issueDate: string;
  dueDate: string;
  paidAt?: string;
  lineItems: InvoiceLineItem[];
  subtotalInCents: number;
  discountInCents?: number;
  discountDescription?: string;
  taxInCents: number;
  taxRate: number;
  totalInCents: number;
  currency: string;
  notes?: string;
  terms?: string;
  footer?: string;
  pdfUrl?: string;
  paymentLink?: string;
  billingAddress?: Address;
  paymentMethod?: string;
  paymentReference?: string;
  reminders?: InvoiceReminder[];
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceLineItem {
  id?: string;
  description: string;
  quantity: number;
  unitPriceInCents: number;
  totalInCents: number;
  productId?: string;
  taxable?: boolean;
}

export interface InvoiceCreateInput {
  contactId?: string;
  organizationId?: string;
  type: 'b2b' | 'b2c';
  dueDate: string;
  lineItems: Array<{
    description: string;
    quantity: number;
    unitPriceInCents: number;
    productId?: string;
    taxable?: boolean;
  }>;
  taxRate?: number;
  discountInCents?: number;
  discountDescription?: string;
  notes?: string;
  terms?: string;
  billingAddress?: AddressInput;
}

export interface InvoiceReminder {
  sentAt: string;
  type: 'upcoming' | 'due' | 'overdue';
  method: 'email' | 'sms';
}

// ============ Benefits Types ============

export interface BenefitClaim {
  id: string;
  claimNumber: string;
  memberId: string;
  memberName: string;
  memberEmail?: string;
  benefitType: string;
  benefitPlanId?: string;
  amountInCents: number;
  currency: string;
  status: 'pending' | 'under_review' | 'approved' | 'rejected' | 'paid' | 'cancelled';
  description?: string;
  receiptUrl?: string;
  supportingDocuments?: string[];
  submittedAt: string;
  processedAt?: string;
  processedBy?: string;
  paidAt?: string;
  paymentMethod?: string;
  paymentReference?: string;
  rejectionReason?: string;
  notes?: string;
  metadata?: Record<string, unknown>;
}

export interface BenefitClaimInput {
  memberId: string;
  benefitType: string;
  benefitPlanId?: string;
  amountInCents: number;
  currency?: string;
  description?: string;
  receiptUrl?: string;
  supportingDocuments?: string[];
  metadata?: Record<string, unknown>;
}

export interface CommissionPayout {
  id: string;
  payoutNumber: string;
  memberId: string;
  memberName: string;
  memberEmail?: string;
  commissionType: string;
  amountInCents: number;
  currency: string;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  sourceTransactionId?: string;
  sourceTransactionType?: string;
  calculationDetails?: {
    baseAmount: number;
    rate: number;
    adjustments?: Array<{ description: string; amount: number }>;
  };
  scheduledFor?: string;
  processedAt?: string;
  paymentMethod?: string;
  paymentReference?: string;
  failureReason?: string;
  notes?: string;
}

// ============ Certificate Types ============

export interface Certificate {
  id: string;
  certificateNumber: string;
  type: 'attendance' | 'completion' | 'cme' | 'ce' | 'achievement' | 'custom';
  recipientId: string;
  recipientName: string;
  recipientEmail?: string;
  eventId?: string;
  eventName?: string;
  courseName?: string;
  credits?: number;
  creditType?: string;
  issueDate: string;
  expiryDate?: string;
  status: 'draft' | 'issued' | 'revoked' | 'expired';
  pdfUrl?: string;
  verificationUrl?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

// ============ Common Types ============

export interface Address {
  street?: string;
  street2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
}

export interface AddressInput {
  street?: string;
  street2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
}

// ============ Pagination ============

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  hasMore: boolean;
  nextCursor?: string;
}

// ============ Webhook Types ============

export interface WebhookEvent {
  id: string;
  type: WebhookEventType;
  timestamp: string;
  data: Record<string, unknown>;
  organizationId: string;
}

export type WebhookEventType =
  | 'contact.created'
  | 'contact.updated'
  | 'contact.deleted'
  | 'organization.created'
  | 'organization.updated'
  | 'event.created'
  | 'event.updated'
  | 'event.published'
  | 'event.cancelled'
  | 'attendee.registered'
  | 'attendee.checked_in'
  | 'attendee.cancelled'
  | 'form.submitted'
  | 'order.created'
  | 'order.paid'
  | 'order.refunded'
  | 'invoice.created'
  | 'invoice.sent'
  | 'invoice.paid'
  | 'invoice.overdue'
  | 'benefit_claim.submitted'
  | 'benefit_claim.approved'
  | 'benefit_claim.rejected'
  | 'benefit_claim.paid'
  | 'commission.calculated'
  | 'commission.paid'
  | 'certificate.issued';
